// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO "Article" (id, title, slug, content, published, "isPremium", visibility,
                       "readingTime", "allowPublicAnnotations", "allowComments", status,
                       "publicationId", "authorId", "categoryId", "tierId", "seoTitle", "seoDescription", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, now())
RETURNING id
`

type CreateArticleParams struct {
	Title                  string            `json:"title"`
	Slug                   string            `json:"slug"`
	Content                string            `json:"content"`
	Published              bool              `json:"published"`
	IsPremium              bool              `json:"isPremium"`
	Visibility             ContentVisibility `json:"visibility"`
	ReadingTime            int32             `json:"readingTime"`
	AllowPublicAnnotations bool              `json:"allowPublicAnnotations"`
	AllowComments          bool              `json:"allowComments"`
	Status                 string            `json:"status"`
	PublicationId          string            `json:"publicationId"`
	AuthorId               pgtype.UUID       `json:"authorId"`
	CategoryId             pgtype.Text       `json:"categoryId"`
	TierId                 pgtype.Text       `json:"tierId"`
	SeoTitle               pgtype.Text       `json:"seoTitle"`
	SeoDescription         pgtype.Text       `json:"seoDescription"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (string, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Published,
		arg.IsPremium,
		arg.Visibility,
		arg.ReadingTime,
		arg.AllowPublicAnnotations,
		arg.AllowComments,
		arg.Status,
		arg.PublicationId,
		arg.AuthorId,
		arg.CategoryId,
		arg.TierId,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM "Article"
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT a.id, a.title, a.slug, a.content, a.published, a."isPremium", a.visibility,
       a."readingTime", a."allowPublicAnnotations", a."allowComments", a."scheduledAt",
       a.status, a."publicationId", a."authorId", a."categoryId", a."tierId",
       a."seoTitle", a."seoDescription", a."createdAt", a."updatedAt",
       u.id::text     AS author_id,
       u.name         AS author_name,
       u.username     AS author_username,
       u."logoUrl"    AS author_logo,
       p.name         AS publication_name,
       p.slug         AS publication_slug,
       p.subdomain    AS publication_subdomain
FROM "Article" a
JOIN "User" u ON u.id = a."authorId"
JOIN "Publication" p ON p.id = a."publicationId"
WHERE a.id = $1
`

type GetArticleByIDRow struct {
	ID                     string            `json:"id"`
	Title                  string            `json:"title"`
	Slug                   string            `json:"slug"`
	Content                string            `json:"content"`
	Published              bool              `json:"published"`
	IsPremium              bool              `json:"isPremium"`
	Visibility             ContentVisibility `json:"visibility"`
	ReadingTime            int32             `json:"readingTime"`
	AllowPublicAnnotations bool              `json:"allowPublicAnnotations"`
	AllowComments          bool              `json:"allowComments"`
	ScheduledAt            pgtype.Timestamp  `json:"scheduledAt"`
	Status                 string            `json:"status"`
	PublicationId          string            `json:"publicationId"`
	AuthorId               pgtype.UUID       `json:"authorId"`
	CategoryId             pgtype.Text       `json:"categoryId"`
	TierId                 pgtype.Text       `json:"tierId"`
	SeoTitle               pgtype.Text       `json:"seoTitle"`
	SeoDescription         pgtype.Text       `json:"seoDescription"`
	CreatedAt              pgtype.Timestamp  `json:"createdAt"`
	UpdatedAt              pgtype.Timestamp  `json:"updatedAt"`
	AuthorID               string            `json:"author_id"`
	AuthorName             pgtype.Text       `json:"author_name"`
	AuthorUsername         pgtype.Text       `json:"author_username"`
	AuthorLogo             pgtype.Text       `json:"author_logo"`
	PublicationName        string            `json:"publication_name"`
	PublicationSlug        string            `json:"publication_slug"`
	PublicationSubdomain   pgtype.Text       `json:"publication_subdomain"`
}

func (q *Queries) GetArticleByID(ctx context.Context, id string) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Published,
		&i.IsPremium,
		&i.Visibility,
		&i.ReadingTime,
		&i.AllowPublicAnnotations,
		&i.AllowComments,
		&i.ScheduledAt,
		&i.Status,
		&i.PublicationId,
		&i.AuthorId,
		&i.CategoryId,
		&i.TierId,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorLogo,
		&i.PublicationName,
		&i.PublicationSlug,
		&i.PublicationSubdomain,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT a.id, a.title, a.slug, a.content, a.published, a."isPremium", a.visibility,
       a."readingTime", a."allowPublicAnnotations", a."allowComments", a."scheduledAt",
       a.status, a."publicationId", a."authorId", a."categoryId", a."tierId",
       a."seoTitle", a."seoDescription", a."createdAt", a."updatedAt",
       u.id::text     AS author_id,
       u.name         AS author_name,
       u.username     AS author_username,
       u."logoUrl"    AS author_logo,
       p.name         AS publication_name,
       p.slug         AS publication_slug,
       p.subdomain    AS publication_subdomain
FROM "Article" a
JOIN "User" u ON u.id = a."authorId"
JOIN "Publication" p ON p.id = a."publicationId"
WHERE a.slug = $1 AND a."publicationId" = $2
`

type GetArticleBySlugParams struct {
	Slug          string `json:"slug"`
	PublicationId string `json:"publicationId"`
}

type GetArticleBySlugRow struct {
	ID                     string            `json:"id"`
	Title                  string            `json:"title"`
	Slug                   string            `json:"slug"`
	Content                string            `json:"content"`
	Published              bool              `json:"published"`
	IsPremium              bool              `json:"isPremium"`
	Visibility             ContentVisibility `json:"visibility"`
	ReadingTime            int32             `json:"readingTime"`
	AllowPublicAnnotations bool              `json:"allowPublicAnnotations"`
	AllowComments          bool              `json:"allowComments"`
	ScheduledAt            pgtype.Timestamp  `json:"scheduledAt"`
	Status                 string            `json:"status"`
	PublicationId          string            `json:"publicationId"`
	AuthorId               pgtype.UUID       `json:"authorId"`
	CategoryId             pgtype.Text       `json:"categoryId"`
	TierId                 pgtype.Text       `json:"tierId"`
	SeoTitle               pgtype.Text       `json:"seoTitle"`
	SeoDescription         pgtype.Text       `json:"seoDescription"`
	CreatedAt              pgtype.Timestamp  `json:"createdAt"`
	UpdatedAt              pgtype.Timestamp  `json:"updatedAt"`
	AuthorID               string            `json:"author_id"`
	AuthorName             pgtype.Text       `json:"author_name"`
	AuthorUsername         pgtype.Text       `json:"author_username"`
	AuthorLogo             pgtype.Text       `json:"author_logo"`
	PublicationName        string            `json:"publication_name"`
	PublicationSlug        string            `json:"publication_slug"`
	PublicationSubdomain   pgtype.Text       `json:"publication_subdomain"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, arg GetArticleBySlugParams) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, arg.Slug, arg.PublicationId)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Published,
		&i.IsPremium,
		&i.Visibility,
		&i.ReadingTime,
		&i.AllowPublicAnnotations,
		&i.AllowComments,
		&i.ScheduledAt,
		&i.Status,
		&i.PublicationId,
		&i.AuthorId,
		&i.CategoryId,
		&i.TierId,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorLogo,
		&i.PublicationName,
		&i.PublicationSlug,
		&i.PublicationSubdomain,
	)
	return i, err
}

const getMediaRoleForUser = `-- name: GetMediaRoleForUser :one
SELECT m.role
FROM "MediaMember" m
JOIN "Media" md ON md.id = m."mediaId"
WHERE md."publicationId" = $1 AND m."userId" = $2
LIMIT 1
`

type GetMediaRoleForUserParams struct {
	PublicationId string      `json:"publicationId"`
	UserId        pgtype.UUID `json:"userId"`
}

func (q *Queries) GetMediaRoleForUser(ctx context.Context, arg GetMediaRoleForUserParams) (string, error) {
	row := q.db.QueryRow(ctx, getMediaRoleForUser, arg.PublicationId, arg.UserId)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getSubscriberEntitlement = `-- name: GetSubscriberEntitlement :one
SELECT s."isPremium", s."isActive", s."tierId"
FROM "Subscriber" s
WHERE s."publicationId" = $1
  AND (s."userId" = $2 OR s.email = $3)
LIMIT 1
`

type GetSubscriberEntitlementParams struct {
	PublicationId string      `json:"publicationId"`
	UserId        pgtype.UUID `json:"userId"`
	Email         string      `json:"email"`
}

type GetSubscriberEntitlementRow struct {
	IsPremium bool        `json:"isPremium"`
	IsActive  bool        `json:"isActive"`
	TierId    pgtype.Text `json:"tierId"`
}

func (q *Queries) GetSubscriberEntitlement(ctx context.Context, arg GetSubscriberEntitlementParams) (GetSubscriberEntitlementRow, error) {
	row := q.db.QueryRow(ctx, getSubscriberEntitlement, arg.PublicationId, arg.UserId, arg.Email)
	var i GetSubscriberEntitlementRow
	err := row.Scan(&i.IsPremium, &i.IsActive, &i.TierId)
	return i, err
}

const getUserPersonalPublication = `-- name: GetUserPersonalPublication :one
SELECT "publicationId" AS id
FROM "User"
WHERE id = $1
`

func (q *Queries) GetUserPersonalPublication(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserPersonalPublication, id)
	var id_2 pgtype.Text
	err := row.Scan(&id_2)
	return id_2, err
}

const listArticlesByPublication = `-- name: ListArticlesByPublication :many
SELECT id, title, slug, published, "isPremium", visibility, "readingTime", status, "createdAt", "updatedAt"
FROM "Article"
WHERE "publicationId" = $1
ORDER BY "createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByPublicationParams struct {
	PublicationId string `json:"publicationId"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

type ListArticlesByPublicationRow struct {
	ID          string            `json:"id"`
	Title       string            `json:"title"`
	Slug        string            `json:"slug"`
	Published   bool              `json:"published"`
	IsPremium   bool              `json:"isPremium"`
	Visibility  ContentVisibility `json:"visibility"`
	ReadingTime int32             `json:"readingTime"`
	Status      string            `json:"status"`
	CreatedAt   pgtype.Timestamp  `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp  `json:"updatedAt"`
}

func (q *Queries) ListArticlesByPublication(ctx context.Context, arg ListArticlesByPublicationParams) ([]ListArticlesByPublicationRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByPublication, arg.PublicationId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByPublicationRow{}
	for rows.Next() {
		var i ListArticlesByPublicationRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Published,
			&i.IsPremium,
			&i.Visibility,
			&i.ReadingTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleStatus = `-- name: SetArticleStatus :one
UPDATE "Article"
SET status = $2, published = $3, "updatedAt" = now()
WHERE id = $1
RETURNING id
`

type SetArticleStatusParams struct {
	ID        string `json:"id"`
	Status    string `json:"status"`
	Published bool   `json:"published"`
}

func (q *Queries) SetArticleStatus(ctx context.Context, arg SetArticleStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, setArticleStatus, arg.ID, arg.Status, arg.Published)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateArticleContent = `-- name: UpdateArticleContent :one
UPDATE "Article"
SET title = $2, content = $3, slug = $4, "isPremium" = $5, "categoryId" = $6,
    "seoTitle" = $7, "seoDescription" = $8, "readingTime" = $9, "updatedAt" = now()
WHERE id = $1
RETURNING id
`

type UpdateArticleContentParams struct {
	ID             string      `json:"id"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	Slug           string      `json:"slug"`
	IsPremium      bool        `json:"isPremium"`
	CategoryId     pgtype.Text `json:"categoryId"`
	SeoTitle       pgtype.Text `json:"seoTitle"`
	SeoDescription pgtype.Text `json:"seoDescription"`
	ReadingTime    int32       `json:"readingTime"`
}

func (q *Queries) UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) (string, error) {
	row := q.db.QueryRow(ctx, updateArticleContent,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Slug,
		arg.IsPremium,
		arg.CategoryId,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.ReadingTime,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
