// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO "WalletTransaction" (id, "userId", "amountCents", type)
VALUES (gen_random_uuid()::text, $1, $2, $3)
RETURNING id
`

type CreateWalletTransactionParams struct {
	UserId      pgtype.UUID `json:"userId"`
	AmountCents int32       `json:"amountCents"`
	Type        string      `json:"type"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (string, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction, arg.UserId, arg.AmountCents, arg.Type)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getMediaOwnerForCredit = `-- name: GetMediaOwnerForCredit :one
SELECT mm."userId"::text AS owner_id, 'creator' AS owner_role
FROM "MediaMember" mm
JOIN "Media" md ON md.id = mm."mediaId"
WHERE md."publicationId" = $1 AND mm.role = 'owner' AND mm.status = 'active'
LIMIT 1
`

type GetMediaOwnerForCreditRow struct {
	OwnerID   string `json:"owner_id"`
	OwnerRole string `json:"owner_role"`
}

func (q *Queries) GetMediaOwnerForCredit(ctx context.Context, publicationid string) (GetMediaOwnerForCreditRow, error) {
	row := q.db.QueryRow(ctx, getMediaOwnerForCredit, publicationid)
	var i GetMediaOwnerForCreditRow
	err := row.Scan(&i.OwnerID, &i.OwnerRole)
	return i, err
}

const getPersonalOwnerForCredit = `-- name: GetPersonalOwnerForCredit :one
SELECT id::text AS owner_id, role AS owner_role
FROM "User"
WHERE "publicationId" = $1
`

type GetPersonalOwnerForCreditRow struct {
	OwnerID   string `json:"owner_id"`
	OwnerRole string `json:"owner_role"`
}

func (q *Queries) GetPersonalOwnerForCredit(ctx context.Context, publicationid pgtype.Text) (GetPersonalOwnerForCreditRow, error) {
	row := q.db.QueryRow(ctx, getPersonalOwnerForCredit, publicationid)
	var i GetPersonalOwnerForCreditRow
	err := row.Scan(&i.OwnerID, &i.OwnerRole)
	return i, err
}

const getPersonalPublicationByUserID = `-- name: GetPersonalPublicationByUserID :one
SELECT "publicationId" AS id FROM "User" WHERE id = $1
`

func (q *Queries) GetPersonalPublicationByUserID(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getPersonalPublicationByUserID, id)
	var id_2 pgtype.Text
	err := row.Scan(&id_2)
	return id_2, err
}

const getPublicationByID = `-- name: GetPublicationByID :one
SELECT id FROM "Publication" WHERE id = $1
`

func (q *Queries) GetPublicationByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getPublicationByID, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const incrementWalletBalance = `-- name: IncrementWalletBalance :exec
UPDATE "User"
SET "walletBalanceCents" = "walletBalanceCents" + $2
WHERE id = $1
`

type IncrementWalletBalanceParams struct {
	ID                 string `json:"id"`
	WalletBalanceCents int32  `json:"walletBalanceCents"`
}

func (q *Queries) IncrementWalletBalance(ctx context.Context, arg IncrementWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, incrementWalletBalance, arg.ID, arg.WalletBalanceCents)
	return err
}

const setSubscriberPremiumStatus = `-- name: SetSubscriberPremiumStatus :exec
UPDATE "Subscriber"
SET "isActive" = $3, "isPremium" = $3, status = $4
WHERE "publicationId" = $1 AND email = $2
`

type SetSubscriberPremiumStatusParams struct {
	PublicationId string             `json:"publicationId"`
	Email         string             `json:"email"`
	IsActive      bool               `json:"isActive"`
	Status        SubscriptionStatus `json:"status"`
}

func (q *Queries) SetSubscriberPremiumStatus(ctx context.Context, arg SetSubscriberPremiumStatusParams) error {
	_, err := q.db.Exec(ctx, setSubscriberPremiumStatus,
		arg.PublicationId,
		arg.Email,
		arg.IsActive,
		arg.Status,
	)
	return err
}

const upsertSubscriberPayment = `-- name: UpsertSubscriberPayment :one
INSERT INTO "Subscriber" (id, email, "publicationId", status, "isActive", "isPremium", "ltvCents", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, 'ACTIVE', true, true, $3, now())
ON CONFLICT ("email", "publicationId") DO UPDATE SET
  "isActive" = true, "isPremium" = true,
  "ltvCents" = "Subscriber"."ltvCents" + EXCLUDED."ltvCents",
  status = 'ACTIVE',
  "updatedAt" = now()
RETURNING id
`

type UpsertSubscriberPaymentParams struct {
	Email         string `json:"email"`
	PublicationId string `json:"publicationId"`
	LtvCents      int32  `json:"ltvCents"`
}

func (q *Queries) UpsertSubscriberPayment(ctx context.Context, arg UpsertSubscriberPaymentParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertSubscriberPayment, arg.Email, arg.PublicationId, arg.LtvCents)
	var id string
	err := row.Scan(&id)
	return id, err
}
