// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: creator.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*)::int AS count
FROM "Follows"
WHERE "publicationId" = $1
`

func (q *Queries) CountFollowers(ctx context.Context, publicationid string) (int32, error) {
	row := q.db.QueryRow(ctx, countFollowers, publicationid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*)::int AS count
FROM "Follows"
WHERE "readerId" = $1
`

func (q *Queries) CountFollowing(ctx context.Context, readerid pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countFollowing, readerid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM "Bookmark"
WHERE "readerId" = $1 AND "articleId" = $2
`

type DeleteBookmarkParams struct {
	ReaderId  pgtype.UUID `json:"readerId"`
	ArticleId string      `json:"articleId"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.Exec(ctx, deleteBookmark, arg.ReaderId, arg.ArticleId)
	return err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM "Follows"
WHERE "readerId" = $1 AND "publicationId" = $2
`

type DeleteFollowParams struct {
	ReaderId      pgtype.UUID `json:"readerId"`
	PublicationId string      `json:"publicationId"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.ReaderId, arg.PublicationId)
	return err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one

SELECT ak.id            AS api_key_id,
       ak."keyHash"     AS key_hash,
       ak.scopes        AS scopes,
       u.id::text       AS user_id,
       u.email,
       u.username,
       u.name,
       u."logoUrl"      AS logo_url,
       u."isCertified"  AS is_certified,
       u.role,
       u."apiAccessStatus" AS api_access_status,
       COALESCE(p.id::text, '')::text AS publication_id,
       p."umamiWebsiteId" AS umami_website_id
FROM "ApiKey" ak
JOIN "User" u ON u.id = ak."userId"
LEFT JOIN "Publication" p ON p.id = u."publicationId" AND p.type = 'PERSONAL'
WHERE ak."keyHash" = $1
LIMIT 1
`

type GetApiKeyByHashRow struct {
	ApiKeyID        string      `json:"api_key_id"`
	KeyHash         string      `json:"key_hash"`
	Scopes          []string    `json:"scopes"`
	UserID          string      `json:"user_id"`
	Email           string      `json:"email"`
	Username        pgtype.Text `json:"username"`
	Name            pgtype.Text `json:"name"`
	LogoUrl         pgtype.Text `json:"logo_url"`
	IsCertified     bool        `json:"is_certified"`
	Role            string      `json:"role"`
	ApiAccessStatus string      `json:"api_access_status"`
	PublicationID   string      `json:"publication_id"`
	UmamiWebsiteID  pgtype.Text `json:"umami_website_id"`
}

// API Créateur (migration depuis Hono apps/api) : clés API, catégories, users, follows, bookmarks.
func (q *Queries) GetApiKeyByHash(ctx context.Context, keyhash string) (GetApiKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyhash)
	var i GetApiKeyByHashRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.KeyHash,
		&i.Scopes,
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.LogoUrl,
		&i.IsCertified,
		&i.Role,
		&i.ApiAccessStatus,
		&i.PublicationID,
		&i.UmamiWebsiteID,
	)
	return i, err
}

const getExistingBookmark = `-- name: GetExistingBookmark :one
SELECT 1 AS present
FROM "Bookmark"
WHERE "readerId" = $1 AND "articleId" = $2
`

type GetExistingBookmarkParams struct {
	ReaderId  pgtype.UUID `json:"readerId"`
	ArticleId string      `json:"articleId"`
}

func (q *Queries) GetExistingBookmark(ctx context.Context, arg GetExistingBookmarkParams) (int32, error) {
	row := q.db.QueryRow(ctx, getExistingBookmark, arg.ReaderId, arg.ArticleId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getExistingFollow = `-- name: GetExistingFollow :one
SELECT 1 AS present
FROM "Follows"
WHERE "readerId" = $1 AND "publicationId" = $2
`

type GetExistingFollowParams struct {
	ReaderId      pgtype.UUID `json:"readerId"`
	PublicationId string      `json:"publicationId"`
}

func (q *Queries) GetExistingFollow(ctx context.Context, arg GetExistingFollowParams) (int32, error) {
	row := q.db.QueryRow(ctx, getExistingFollow, arg.ReaderId, arg.PublicationId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getPublicationBySlugOrSubdomain = `-- name: GetPublicationBySlugOrSubdomain :one
SELECT p.id,
       p.type,
       p.name,
       p.slug,
       p.subdomain,
       p."customDomain",
       p."heroText",
       p."logoUrl",
       p."headerImageUrl",
       p."isCertified",
       p."createdAt",
       (SELECT COUNT(*)::int FROM "Follows" f WHERE f."publicationId" = p.id) AS followers_count,
       (SELECT COUNT(*)::int FROM "Article" a WHERE a."publicationId" = p.id AND a."published" = true) AS articles_count
FROM "Publication" p
WHERE p.slug = $1 OR p.subdomain = $1
LIMIT 1
`

type GetPublicationBySlugOrSubdomainRow struct {
	ID             string           `json:"id"`
	Type           PublicationType  `json:"type"`
	Name           string           `json:"name"`
	Slug           string           `json:"slug"`
	Subdomain      pgtype.Text      `json:"subdomain"`
	CustomDomain   pgtype.Text      `json:"customDomain"`
	HeroText       pgtype.Text      `json:"heroText"`
	LogoUrl        pgtype.Text      `json:"logoUrl"`
	HeaderImageUrl pgtype.Text      `json:"headerImageUrl"`
	IsCertified    bool             `json:"isCertified"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	FollowersCount int32            `json:"followers_count"`
	ArticlesCount  int32            `json:"articles_count"`
}

func (q *Queries) GetPublicationBySlugOrSubdomain(ctx context.Context, slug string) (GetPublicationBySlugOrSubdomainRow, error) {
	row := q.db.QueryRow(ctx, getPublicationBySlugOrSubdomain, slug)
	var i GetPublicationBySlugOrSubdomainRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Slug,
		&i.Subdomain,
		&i.CustomDomain,
		&i.HeroText,
		&i.LogoUrl,
		&i.HeaderImageUrl,
		&i.IsCertified,
		&i.CreatedAt,
		&i.FollowersCount,
		&i.ArticlesCount,
	)
	return i, err
}

const getUserByIDFull = `-- name: GetUserByIDFull :one
SELECT u.id::text        AS user_id,
       u.email,
       u.username,
       u.name,
       u.role,
       u."isCertified",
       u."isShadowbanned",
       u."isSuspended",
       u."suspendReason",
       u."forceStandardTheme",
       u."onboardingText",
       u."logoUrl",
       u."publicationId",
       u."advancedSettingsMode",
       u."hasCompletedOnboarding",
       u."apiAccessStatus",
       u."apiApplicationReason",
       u."walletBalanceCents",
       u."createdAt",
       u."updatedAt"
FROM "User" u
WHERE u.id = $1
`

type GetUserByIDFullRow struct {
	UserID                 string           `json:"user_id"`
	Email                  string           `json:"email"`
	Username               pgtype.Text      `json:"username"`
	Name                   pgtype.Text      `json:"name"`
	Role                   string           `json:"role"`
	IsCertified            bool             `json:"isCertified"`
	IsShadowbanned         bool             `json:"isShadowbanned"`
	IsSuspended            bool             `json:"isSuspended"`
	SuspendReason          pgtype.Text      `json:"suspendReason"`
	ForceStandardTheme     bool             `json:"forceStandardTheme"`
	OnboardingText         pgtype.Text      `json:"onboardingText"`
	LogoUrl                pgtype.Text      `json:"logoUrl"`
	PublicationId          pgtype.Text      `json:"publicationId"`
	AdvancedSettingsMode   bool             `json:"advancedSettingsMode"`
	HasCompletedOnboarding bool             `json:"hasCompletedOnboarding"`
	ApiAccessStatus        string           `json:"apiAccessStatus"`
	ApiApplicationReason   pgtype.Text      `json:"apiApplicationReason"`
	WalletBalanceCents     int32            `json:"walletBalanceCents"`
	CreatedAt              pgtype.Timestamp `json:"createdAt"`
	UpdatedAt              pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) GetUserByIDFull(ctx context.Context, id string) (GetUserByIDFullRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDFull, id)
	var i GetUserByIDFullRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Role,
		&i.IsCertified,
		&i.IsShadowbanned,
		&i.IsSuspended,
		&i.SuspendReason,
		&i.ForceStandardTheme,
		&i.OnboardingText,
		&i.LogoUrl,
		&i.PublicationId,
		&i.AdvancedSettingsMode,
		&i.HasCompletedOnboarding,
		&i.ApiAccessStatus,
		&i.ApiApplicationReason,
		&i.WalletBalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookmark = `-- name: InsertBookmark :exec
INSERT INTO "Bookmark" (id, "readerId", "articleId")
VALUES (gen_random_uuid()::text, $1, $2)
`

type InsertBookmarkParams struct {
	ReaderId  pgtype.UUID `json:"readerId"`
	ArticleId string      `json:"articleId"`
}

func (q *Queries) InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error {
	_, err := q.db.Exec(ctx, insertBookmark, arg.ReaderId, arg.ArticleId)
	return err
}

const insertFollow = `-- name: InsertFollow :exec
INSERT INTO "Follows" (id, "readerId", "publicationId")
VALUES (gen_random_uuid()::text, $1, $2)
`

type InsertFollowParams struct {
	ReaderId      pgtype.UUID `json:"readerId"`
	PublicationId string      `json:"publicationId"`
}

func (q *Queries) InsertFollow(ctx context.Context, arg InsertFollowParams) error {
	_, err := q.db.Exec(ctx, insertFollow, arg.ReaderId, arg.PublicationId)
	return err
}

const listBookmarksByReader = `-- name: ListBookmarksByReader :many
SELECT b.id                 AS bookmark_id,
       b."createdAt"        AS bookmarked_at,
       a.id                 AS article_id,
       a.title              AS article_title,
       a.slug               AS article_slug,
       a."readingTime"      AS article_reading_time,
       a."isPremium"        AS article_is_premium,
       a."createdAt"        AS article_created_at,
       p.id                 AS publication_id,
       p.name               AS publication_name,
       p.slug               AS publication_slug,
       p.subdomain          AS publication_subdomain,
       u.id::text           AS author_id,
       u.name               AS author_name,
       u.username           AS author_username,
       u."logoUrl"          AS author_logo
FROM "Bookmark" b
JOIN "Article" a ON a.id = b."articleId" AND a.published = true
JOIN "Publication" p ON p.id = a."publicationId"
JOIN "User" u ON u.id = a."authorId"
WHERE b."readerId" = $1
ORDER BY b."createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListBookmarksByReaderParams struct {
	ReaderId pgtype.UUID `json:"readerId"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListBookmarksByReaderRow struct {
	BookmarkID           string           `json:"bookmark_id"`
	BookmarkedAt         pgtype.Timestamp `json:"bookmarked_at"`
	ArticleID            string           `json:"article_id"`
	ArticleTitle         string           `json:"article_title"`
	ArticleSlug          string           `json:"article_slug"`
	ArticleReadingTime   int32            `json:"article_reading_time"`
	ArticleIsPremium     bool             `json:"article_is_premium"`
	ArticleCreatedAt     pgtype.Timestamp `json:"article_created_at"`
	PublicationID        string           `json:"publication_id"`
	PublicationName      string           `json:"publication_name"`
	PublicationSlug      string           `json:"publication_slug"`
	PublicationSubdomain pgtype.Text      `json:"publication_subdomain"`
	AuthorID             string           `json:"author_id"`
	AuthorName           pgtype.Text      `json:"author_name"`
	AuthorUsername       pgtype.Text      `json:"author_username"`
	AuthorLogo           pgtype.Text      `json:"author_logo"`
}

// Articles sauvegardés (bookmarks) d'un lecteur, avec titre/slug/publication
// et la date de sauvegarde — pour la bibliothèque mobile.
func (q *Queries) ListBookmarksByReader(ctx context.Context, arg ListBookmarksByReaderParams) ([]ListBookmarksByReaderRow, error) {
	rows, err := q.db.Query(ctx, listBookmarksByReader, arg.ReaderId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksByReaderRow{}
	for rows.Next() {
		var i ListBookmarksByReaderRow
		if err := rows.Scan(
			&i.BookmarkID,
			&i.BookmarkedAt,
			&i.ArticleID,
			&i.ArticleTitle,
			&i.ArticleSlug,
			&i.ArticleReadingTime,
			&i.ArticleIsPremium,
			&i.ArticleCreatedAt,
			&i.PublicationID,
			&i.PublicationName,
			&i.PublicationSlug,
			&i.PublicationSubdomain,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByPublication = `-- name: ListCategoriesByPublication :many
SELECT c.id,
       c.name,
       c.slug,
       c.description,
       (SELECT COUNT(*)::int
        FROM "Article" a
        WHERE a."categoryId" = c.id AND a."published" = true) AS articles_count
FROM "Category" c
WHERE c."publicationId" = $1
ORDER BY c.name ASC
`

type ListCategoriesByPublicationRow struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Slug          string      `json:"slug"`
	Description   pgtype.Text `json:"description"`
	ArticlesCount int32       `json:"articles_count"`
}

func (q *Queries) ListCategoriesByPublication(ctx context.Context, publicationid string) ([]ListCategoriesByPublicationRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesByPublication, publicationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesByPublicationRow{}
	for rows.Next() {
		var i ListCategoriesByPublicationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ArticlesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE "ApiKey"
SET "lastUsedAt" = now()
WHERE id = $1
`

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsed, id)
	return err
}
