// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Compte des articles d'une publication (mêmes filtres que ListCreatorArticles).
	CountCreatorArticles(ctx context.Context, arg CountCreatorArticlesParams) (int64, error)
	CountFollowers(ctx context.Context, publicationid string) (int32, error)
	CountFollowing(ctx context.Context, readerid pgtype.UUID) (int32, error)
	CountOptionVotes(ctx context.Context, optionid string) (int32, error)
	CountOptionVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountOptionVotesByIDsRow, error)
	CountPollVotes(ctx context.Context, pollid string) (int32, error)
	CountPollVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountPollVotesByIDsRow, error)
	CountPureReposts(ctx context.Context, arg CountPureRepostsParams) (int32, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (string, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (string, error)
	CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (string, error)
	CreateThought(ctx context.Context, arg CreateThoughtParams) (CreateThoughtRow, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (string, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (string, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (string, error)
	DecrementLikeCount(ctx context.Context, id string) error
	DecrementReplyCount(ctx context.Context, id string) error
	DecrementRepostCount(ctx context.Context, id string) error
	DeleteArticle(ctx context.Context, id string) error
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeleteLikeNotification(ctx context.Context, arg DeleteLikeNotificationParams) error
	DeletePureReposts(ctx context.Context, arg DeletePureRepostsParams) error
	DeleteRepostNotification(ctx context.Context, arg DeleteRepostNotificationParams) error
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error
	ExistsUnreadLikeNotification(ctx context.Context, arg ExistsUnreadLikeNotificationParams) (int32, error)
	ExistsUnreadMentionNotification(ctx context.Context, arg ExistsUnreadMentionNotificationParams) (int32, error)
	ExistsUnreadReplyNotification(ctx context.Context, arg ExistsUnreadReplyNotificationParams) (int32, error)
	ExistsUnreadRepostNotification(ctx context.Context, arg ExistsUnreadRepostNotificationParams) (int32, error)
	FindFollowingFeed(ctx context.Context, arg FindFollowingFeedParams) ([]FindFollowingFeedRow, error)
	FindTrending(ctx context.Context, arg FindTrendingParams) ([]FindTrendingRow, error)
	GetActiveSubscribersByPublication(ctx context.Context, arg GetActiveSubscribersByPublicationParams) ([]GetActiveSubscribersByPublicationRow, error)
	GetActiveSubscriptionForReply(ctx context.Context, arg GetActiveSubscriptionForReplyParams) (int32, error)
	GetActiveWebhooksByPublication(ctx context.Context, arg GetActiveWebhooksByPublicationParams) ([]GetActiveWebhooksByPublicationRow, error)
	// API Créateur (migration depuis Hono apps/api) : clés API, catégories, users, follows, bookmarks.
	GetApiKeyByHash(ctx context.Context, keyhash string) (GetApiKeyByHashRow, error)
	GetArticleByID(ctx context.Context, id string) (GetArticleByIDRow, error)
	GetArticleBySlug(ctx context.Context, arg GetArticleBySlugParams) (GetArticleBySlugRow, error)
	GetArticleForSearch(ctx context.Context, id string) (GetArticleForSearchRow, error)
	GetAttachmentsByIDs(ctx context.Context, dollar_1 []string) ([]GetAttachmentsByIDsRow, error)
	GetAudienceSummary(ctx context.Context, publicationid string) (GetAudienceSummaryRow, error)
	GetCanonicalThoughtID(ctx context.Context, id string) (string, error)
	// Lecture d'un article PUBLIÉ d'une publication au format contrat créateurs
	// (clé API → publication du créateur), catégorie embarquée.
	GetCreatorArticleBySlug(ctx context.Context, arg GetCreatorArticleBySlugParams) (GetCreatorArticleBySlugRow, error)
	GetExistingBookmark(ctx context.Context, arg GetExistingBookmarkParams) (int32, error)
	GetExistingFollow(ctx context.Context, arg GetExistingFollowParams) (int32, error)
	GetExistingLike(ctx context.Context, arg GetExistingLikeParams) (int32, error)
	GetFollowForReply(ctx context.Context, arg GetFollowForReplyParams) (int32, error)
	GetFollowedPersonalPublicationOwnerIDs(ctx context.Context, readerid pgtype.UUID) ([]string, error)
	GetFreeSubscriberCount(ctx context.Context, publicationid string) (int32, error)
	GetLikePrefs(ctx context.Context, userid pgtype.UUID) (GetLikePrefsRow, error)
	GetMediaOwnerForCredit(ctx context.Context, publicationid string) (GetMediaOwnerForCreditRow, error)
	GetMediaRoleForUser(ctx context.Context, arg GetMediaRoleForUserParams) (string, error)
	GetNotificationPreferences(ctx context.Context, userid pgtype.UUID) (GetNotificationPreferencesRow, error)
	// Centre de notifications : liste groupée, non-lus, lecture, préférences.
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error)
	GetPersonalOwnerForCredit(ctx context.Context, publicationid pgtype.Text) (GetPersonalOwnerForCreditRow, error)
	GetPersonalPublicationByUserID(ctx context.Context, id string) (pgtype.Text, error)
	GetPersonalPublicationID(ctx context.Context, id string) (pgtype.Text, error)
	// Polls, votes, pièces jointes
	GetPollByThoughtID(ctx context.Context, thoughtid string) (GetPollByThoughtIDRow, error)
	GetPollOptions(ctx context.Context, pollid string) ([]PollOption, error)
	GetPollOptionsByIDs(ctx context.Context, dollar_1 []string) ([]PollOption, error)
	GetPollsByIDs(ctx context.Context, dollar_1 []string) ([]GetPollsByIDsRow, error)
	GetPostAuthor(ctx context.Context, id string) (string, error)
	GetPostThread(ctx context.Context, arg GetPostThreadParams) ([]GetPostThreadRow, error)
	GetPostsByIDs(ctx context.Context, arg GetPostsByIDsParams) ([]GetPostsByIDsRow, error)
	GetPremiumActiveSubscribers(ctx context.Context, publicationid string) ([]GetPremiumActiveSubscribersRow, error)
	GetPublicationByID(ctx context.Context, id string) (string, error)
	GetPublicationBySlugOrSubdomain(ctx context.Context, slug string) (GetPublicationBySlugOrSubdomainRow, error)
	GetRecentArticlesForAnalytics(ctx context.Context, arg GetRecentArticlesForAnalyticsParams) ([]GetRecentArticlesForAnalyticsRow, error)
	GetRecentThoughtsForAnalytics(ctx context.Context, arg GetRecentThoughtsForAnalyticsParams) ([]GetRecentThoughtsForAnalyticsRow, error)
	GetRepliesForThought(ctx context.Context, arg GetRepliesForThoughtParams) ([]GetRepliesForThoughtRow, error)
	GetReplyIDsForThought(ctx context.Context, parentid pgtype.Text) ([]string, error)
	// Notifications REPLY / MENTION
	GetReplyPrefs(ctx context.Context, userid pgtype.UUID) (GetReplyPrefsRow, error)
	GetSubscriberEntitlement(ctx context.Context, arg GetSubscriberEntitlementParams) (GetSubscriberEntitlementRow, error)
	GetThoughtByID(ctx context.Context, id string) (GetThoughtByIDRow, error)
	// Threadgates & réponses
	GetThoughtReplyGate(ctx context.Context, id string) (GetThoughtReplyGateRow, error)
	GetUnreadCount(ctx context.Context, recipientid pgtype.UUID) (int32, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByIDFull(ctx context.Context, id string) (GetUserByIDFullRow, error)
	GetUserPersonalPublication(ctx context.Context, id string) (pgtype.Text, error)
	GetUserPollVote(ctx context.Context, arg GetUserPollVoteParams) (string, error)
	GetUserUsername(ctx context.Context, id string) (pgtype.Text, error)
	GetUserVotesByIDs(ctx context.Context, arg GetUserVotesByIDsParams) ([]GetUserVotesByIDsRow, error)
	GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]GetUsersByUsernamesRow, error)
	GetWebhookByID(ctx context.Context, id string) (Webhook, error)
	IncrementLikeCount(ctx context.Context, id string) error
	IncrementReplyCount(ctx context.Context, id string) error
	IncrementRepostCount(ctx context.Context, id string) error
	IncrementWalletBalance(ctx context.Context, arg IncrementWalletBalanceParams) error
	InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error
	InsertFollow(ctx context.Context, arg InsertFollowParams) error
	InsertLike(ctx context.Context, arg InsertLikeParams) (string, error)
	InsertLikeNotification(ctx context.Context, arg InsertLikeNotificationParams) error
	InsertMentionNotification(ctx context.Context, arg InsertMentionNotificationParams) error
	InsertPureRepost(ctx context.Context, arg InsertPureRepostParams) (string, error)
	InsertReplyNotification(ctx context.Context, arg InsertReplyNotificationParams) error
	InsertRepostNotification(ctx context.Context, arg InsertRepostNotificationParams) error
	ListCategoriesByPublication(ctx context.Context, publicationid string) ([]ListCategoriesByPublicationRow, error)
	// Liste des articles d'une publication au format contrat créateurs (Hono) :
	// filtres `published` (défaut true) et `category` (slug), catégorie embarquée.
	ListCreatorArticles(ctx context.Context, arg ListCreatorArticlesParams) ([]ListCreatorArticlesRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	ListWebhooksByPublication(ctx context.Context, publicationid string) ([]ListWebhooksByPublicationRow, error)
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error
	SetArticleStatus(ctx context.Context, arg SetArticleStatusParams) (string, error)
	SetSubscriberPremiumStatus(ctx context.Context, arg SetSubscriberPremiumStatusParams) error
	UpdateApiKeyLastUsed(ctx context.Context, id string) error
	UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) (string, error)
	UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) error
	UpsertSubscriberPayment(ctx context.Context, arg UpsertSubscriberPaymentParams) (string, error)
}

var _ Querier = (*Queries)(nil)
