// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const existsUnreadMentionNotification = `-- name: ExistsUnreadMentionNotification :one
SELECT 1 AS present
FROM "Notification"
WHERE "recipientId" = $1 AND "senderId" = $2 AND type = 'MENTION' AND "thoughtId" = $3 AND "isRead" = false
`

type ExistsUnreadMentionNotificationParams struct {
	RecipientId pgtype.UUID `json:"recipientId"`
	SenderId    pgtype.UUID `json:"senderId"`
	ThoughtId   pgtype.Text `json:"thoughtId"`
}

func (q *Queries) ExistsUnreadMentionNotification(ctx context.Context, arg ExistsUnreadMentionNotificationParams) (int32, error) {
	row := q.db.QueryRow(ctx, existsUnreadMentionNotification, arg.RecipientId, arg.SenderId, arg.ThoughtId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const existsUnreadReplyNotification = `-- name: ExistsUnreadReplyNotification :one
SELECT 1 AS present
FROM "Notification"
WHERE "recipientId" = $1 AND "senderId" = $2 AND type = 'REPLY' AND "thoughtId" = $3 AND "isRead" = false
`

type ExistsUnreadReplyNotificationParams struct {
	RecipientId pgtype.UUID `json:"recipientId"`
	SenderId    pgtype.UUID `json:"senderId"`
	ThoughtId   pgtype.Text `json:"thoughtId"`
}

func (q *Queries) ExistsUnreadReplyNotification(ctx context.Context, arg ExistsUnreadReplyNotificationParams) (int32, error) {
	row := q.db.QueryRow(ctx, existsUnreadReplyNotification, arg.RecipientId, arg.SenderId, arg.ThoughtId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getActiveSubscriptionForReply = `-- name: GetActiveSubscriptionForReply :one
SELECT 1 AS present
FROM "Subscriber"
WHERE "publicationId" = $1 AND "userId" = $2 AND "isActive" = true
`

type GetActiveSubscriptionForReplyParams struct {
	PublicationId string      `json:"publicationId"`
	UserId        pgtype.UUID `json:"userId"`
}

func (q *Queries) GetActiveSubscriptionForReply(ctx context.Context, arg GetActiveSubscriptionForReplyParams) (int32, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionForReply, arg.PublicationId, arg.UserId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getFollowForReply = `-- name: GetFollowForReply :one
SELECT 1 AS present
FROM "Follows"
WHERE "readerId" = $1 AND "publicationId" = $2
`

type GetFollowForReplyParams struct {
	ReaderId      pgtype.UUID `json:"readerId"`
	PublicationId string      `json:"publicationId"`
}

func (q *Queries) GetFollowForReply(ctx context.Context, arg GetFollowForReplyParams) (int32, error) {
	row := q.db.QueryRow(ctx, getFollowForReply, arg.ReaderId, arg.PublicationId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getPersonalPublicationID = `-- name: GetPersonalPublicationID :one
SELECT "publicationId" AS id
FROM "User"
WHERE id = $1
`

func (q *Queries) GetPersonalPublicationID(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getPersonalPublicationID, id)
	var id_2 pgtype.Text
	err := row.Scan(&id_2)
	return id_2, err
}

const getReplyPrefs = `-- name: GetReplyPrefs :one

SELECT "emailReplies", "pushReplies", "emailMentions", "pushMentions"
FROM "NotificationPreference"
WHERE "userId" = $1
`

type GetReplyPrefsRow struct {
	EmailReplies  bool `json:"emailReplies"`
	PushReplies   bool `json:"pushReplies"`
	EmailMentions bool `json:"emailMentions"`
	PushMentions  bool `json:"pushMentions"`
}

// Notifications REPLY / MENTION
func (q *Queries) GetReplyPrefs(ctx context.Context, userid pgtype.UUID) (GetReplyPrefsRow, error) {
	row := q.db.QueryRow(ctx, getReplyPrefs, userid)
	var i GetReplyPrefsRow
	err := row.Scan(
		&i.EmailReplies,
		&i.PushReplies,
		&i.EmailMentions,
		&i.PushMentions,
	)
	return i, err
}

const getThoughtReplyGate = `-- name: GetThoughtReplyGate :one

SELECT "authorId"::text AS author_id, "replyRestriction", content
FROM "Post"
WHERE id = $1
`

type GetThoughtReplyGateRow struct {
	AuthorID         string `json:"author_id"`
	ReplyRestriction string `json:"replyRestriction"`
	Content          string `json:"content"`
}

// Threadgates & réponses
func (q *Queries) GetThoughtReplyGate(ctx context.Context, id string) (GetThoughtReplyGateRow, error) {
	row := q.db.QueryRow(ctx, getThoughtReplyGate, id)
	var i GetThoughtReplyGateRow
	err := row.Scan(&i.AuthorID, &i.ReplyRestriction, &i.Content)
	return i, err
}

const getUserUsername = `-- name: GetUserUsername :one
SELECT username
FROM "User"
WHERE id = $1
`

func (q *Queries) GetUserUsername(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserUsername, id)
	var username pgtype.Text
	err := row.Scan(&username)
	return username, err
}

const getUsersByUsernames = `-- name: GetUsersByUsernames :many
SELECT id::text AS user_id, username
FROM "User"
WHERE username = ANY($1::text[])
`

type GetUsersByUsernamesRow struct {
	UserID   string      `json:"user_id"`
	Username pgtype.Text `json:"username"`
}

func (q *Queries) GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]GetUsersByUsernamesRow, error) {
	rows, err := q.db.Query(ctx, getUsersByUsernames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByUsernamesRow{}
	for rows.Next() {
		var i GetUsersByUsernamesRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMentionNotification = `-- name: InsertMentionNotification :exec
INSERT INTO "Notification" (id, "recipientId", "senderId", type, "thoughtId")
VALUES (gen_random_uuid()::text, $1, $2, 'MENTION', $3)
`

type InsertMentionNotificationParams struct {
	RecipientId pgtype.UUID `json:"recipientId"`
	SenderId    pgtype.UUID `json:"senderId"`
	ThoughtId   pgtype.Text `json:"thoughtId"`
}

func (q *Queries) InsertMentionNotification(ctx context.Context, arg InsertMentionNotificationParams) error {
	_, err := q.db.Exec(ctx, insertMentionNotification, arg.RecipientId, arg.SenderId, arg.ThoughtId)
	return err
}

const insertReplyNotification = `-- name: InsertReplyNotification :exec
INSERT INTO "Notification" (id, "recipientId", "senderId", type, "thoughtId")
VALUES (gen_random_uuid()::text, $1, $2, 'REPLY', $3)
`

type InsertReplyNotificationParams struct {
	RecipientId pgtype.UUID `json:"recipientId"`
	SenderId    pgtype.UUID `json:"senderId"`
	ThoughtId   pgtype.Text `json:"thoughtId"`
}

func (q *Queries) InsertReplyNotification(ctx context.Context, arg InsertReplyNotificationParams) error {
	_, err := q.db.Exec(ctx, insertReplyNotification, arg.RecipientId, arg.SenderId, arg.ThoughtId)
	return err
}
