// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminDashboardCounts = `-- name: AdminDashboardCounts :one
SELECT
    (SELECT count(*) FROM "User") AS users,
    (SELECT count(*) FROM "User" WHERE role = 'creator') AS creators,
    (SELECT count(*) FROM "Article") AS articles,
    (SELECT count(*) FROM "Subscriber" WHERE "isPremium" = true AND "isActive" = true) AS premium_subscribers
`

type AdminDashboardCountsRow struct {
	Users              int64 `json:"users"`
	Creators           int64 `json:"creators"`
	Articles           int64 `json:"articles"`
	PremiumSubscribers int64 `json:"premium_subscribers"`
}

func (q *Queries) AdminDashboardCounts(ctx context.Context) (AdminDashboardCountsRow, error) {
	row := q.db.QueryRow(ctx, adminDashboardCounts)
	var i AdminDashboardCountsRow
	err := row.Scan(
		&i.Users,
		&i.Creators,
		&i.Articles,
		&i.PremiumSubscribers,
	)
	return i, err
}

const clearArticleEditorPicks = `-- name: ClearArticleEditorPicks :exec
UPDATE "Article" SET "isEditorPick" = false, "updatedAt" = now() WHERE "isEditorPick" = true
`

func (q *Queries) ClearArticleEditorPicks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearArticleEditorPicks)
	return err
}

const countAllNotificationDeliveries = `-- name: CountAllNotificationDeliveries :one
SELECT count(*) FROM "NotificationDelivery"
`

func (q *Queries) CountAllNotificationDeliveries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllNotificationDeliveries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotificationDeliveriesByStatus = `-- name: CountNotificationDeliveriesByStatus :many

SELECT status, count(*) AS total
FROM "NotificationDelivery"
GROUP BY status
`

type CountNotificationDeliveriesByStatusRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

// ── Notifications & livraisons ───────────────────────────────────────────────
func (q *Queries) CountNotificationDeliveriesByStatus(ctx context.Context) ([]CountNotificationDeliveriesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countNotificationDeliveriesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNotificationDeliveriesByStatusRow{}
	for rows.Next() {
		var i CountNotificationDeliveriesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePromo = `-- name: DeletePromo :exec
DELETE FROM "PartnerPromo" WHERE id = $1
`

func (q *Queries) DeletePromo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePromo, id)
	return err
}

const deleteSystemConfig = `-- name: DeleteSystemConfig :exec
DELETE FROM "SystemConfig" WHERE key = $1
`

func (q *Queries) DeleteSystemConfig(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSystemConfig, key)
	return err
}

const deleteTrend = `-- name: DeleteTrend :exec
DELETE FROM "Trend" WHERE id = $1
`

func (q *Queries) DeleteTrend(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTrend, id)
	return err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT u.id, u.name, u.email, u.username, u.role, u."isCertified", u."isShadowbanned",
       u."isSuspended", u."suspendReason", u."logoUrl", u."publicationId", u."createdAt",
       p."subdomain", p."name" AS publication_name,
       (SELECT count(*) FROM "Article" a WHERE a."publicationId" = p.id) AS articles_count,
       (SELECT count(*) FROM "Subscriber" s WHERE s."publicationId" = p.id) AS subscribers_count,
       (SELECT count(*) FROM "WalletTransaction" w WHERE w."userId" = u.id) AS wallet_transactions_count
FROM "User" u
LEFT JOIN "Publication" p ON p.id = u."publicationId"
WHERE u.id = $1
`

type GetAdminUserRow struct {
	ID                      string           `json:"id"`
	Name                    pgtype.Text      `json:"name"`
	Email                   string           `json:"email"`
	Username                pgtype.Text      `json:"username"`
	Role                    string           `json:"role"`
	IsCertified             bool             `json:"isCertified"`
	IsShadowbanned          bool             `json:"isShadowbanned"`
	IsSuspended             bool             `json:"isSuspended"`
	SuspendReason           pgtype.Text      `json:"suspendReason"`
	LogoUrl                 pgtype.Text      `json:"logoUrl"`
	PublicationId           pgtype.Text      `json:"publicationId"`
	CreatedAt               pgtype.Timestamp `json:"createdAt"`
	Subdomain               pgtype.Text      `json:"subdomain"`
	PublicationName         pgtype.Text      `json:"publication_name"`
	ArticlesCount           int64            `json:"articles_count"`
	SubscribersCount        int64            `json:"subscribers_count"`
	WalletTransactionsCount int64            `json:"wallet_transactions_count"`
}

func (q *Queries) GetAdminUser(ctx context.Context, id string) (GetAdminUserRow, error) {
	row := q.db.QueryRow(ctx, getAdminUser, id)
	var i GetAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.IsCertified,
		&i.IsShadowbanned,
		&i.IsSuspended,
		&i.SuspendReason,
		&i.LogoUrl,
		&i.PublicationId,
		&i.CreatedAt,
		&i.Subdomain,
		&i.PublicationName,
		&i.ArticlesCount,
		&i.SubscribersCount,
		&i.WalletTransactionsCount,
	)
	return i, err
}

const getAdminUserRevenue = `-- name: GetAdminUserRevenue :one
SELECT COALESCE(sum(w."amountCents"), 0)::bigint AS total_cents
FROM "WalletTransaction" w
WHERE w."userId" = $1 AND w."type" = 'SUBSCRIPTION_PAYMENT'
`

func (q *Queries) GetAdminUserRevenue(ctx context.Context, userid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getAdminUserRevenue, userid)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const getAdminUserRole = `-- name: GetAdminUserRole :one

SELECT role FROM "User" WHERE id = $1
`

// Admin — console superadmin (modération & management).
// Rôle : réservé au superadmin (vérifié côté service/handler).
func (q *Queries) GetAdminUserRole(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getAdminUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getSystemConfigsByKeys = `-- name: GetSystemConfigsByKeys :many
SELECT key, value, description, "updatedAt" FROM "SystemConfig" WHERE key = ANY($1::text[])
`

func (q *Queries) GetSystemConfigsByKeys(ctx context.Context, dollar_1 []string) ([]SystemConfig, error) {
	rows, err := q.db.Query(ctx, getSystemConfigsByKeys, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemConfig{}
	for rows.Next() {
		var i SystemConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminApiApplicants = `-- name: ListAdminApiApplicants :many

SELECT u.id, u.name, u.email, u."apiAccessStatus", u."apiApplicationReason", u."createdAt", u."updatedAt",
       p."subdomain" AS publication_subdomain
FROM "User" u
LEFT JOIN "Publication" p ON p.id = u."publicationId"
WHERE u.role IN ('creator', 'superadmin') AND u."apiAccessStatus" <> 'none'
ORDER BY u."updatedAt" DESC
`

type ListAdminApiApplicantsRow struct {
	ID                   string           `json:"id"`
	Name                 pgtype.Text      `json:"name"`
	Email                string           `json:"email"`
	ApiAccessStatus      string           `json:"apiAccessStatus"`
	ApiApplicationReason pgtype.Text      `json:"apiApplicationReason"`
	CreatedAt            pgtype.Timestamp `json:"createdAt"`
	UpdatedAt            pgtype.Timestamp `json:"updatedAt"`
	PublicationSubdomain pgtype.Text      `json:"publication_subdomain"`
}

// ── Demandes d'accès API ─────────────────────────────────────────────────────
func (q *Queries) ListAdminApiApplicants(ctx context.Context) ([]ListAdminApiApplicantsRow, error) {
	rows, err := q.db.Query(ctx, listAdminApiApplicants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminApiApplicantsRow{}
	for rows.Next() {
		var i ListAdminApiApplicantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ApiAccessStatus,
			&i.ApiApplicationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicationSubdomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminArticles = `-- name: ListAdminArticles :many

SELECT a.id, a.title, a.slug, a.published, a."isEditorPick", a."createdAt",
       u.name AS author_name, u.email AS author_email
FROM "Article" a
JOIN "User" u ON u.id = a."authorId"
ORDER BY a."createdAt" DESC
`

type ListAdminArticlesRow struct {
	ID           string           `json:"id"`
	Title        string           `json:"title"`
	Slug         string           `json:"slug"`
	Published    bool             `json:"published"`
	IsEditorPick bool             `json:"isEditorPick"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	AuthorName   pgtype.Text      `json:"author_name"`
	AuthorEmail  string           `json:"author_email"`
}

// ── Widgets & Tendances ──────────────────────────────────────────────────────
func (q *Queries) ListAdminArticles(ctx context.Context) ([]ListAdminArticlesRow, error) {
	rows, err := q.db.Query(ctx, listAdminArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminArticlesRow{}
	for rows.Next() {
		var i ListAdminArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Published,
			&i.IsEditorPick,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminOAuthClients = `-- name: ListAdminOAuthClients :many

SELECT c.id, c."clientId", c.name, c.description, c."logoUrl", c."homepageUrl",
       c."redirectUris", c.scopes, c."clientType", c.status, c."createdAt",
       u.name AS owner_name, u.email AS owner_email, u.username AS owner_username
FROM "OAuthClient" c
JOIN "User" u ON u.id = c."ownerUserId"
ORDER BY c."createdAt" DESC
`

type ListAdminOAuthClientsRow struct {
	ID            string            `json:"id"`
	ClientId      string            `json:"clientId"`
	Name          string            `json:"name"`
	Description   pgtype.Text       `json:"description"`
	LogoUrl       pgtype.Text       `json:"logoUrl"`
	HomepageUrl   pgtype.Text       `json:"homepageUrl"`
	RedirectUris  []string          `json:"redirectUris"`
	Scopes        []string          `json:"scopes"`
	ClientType    OAuthClientType   `json:"clientType"`
	Status        OAuthClientStatus `json:"status"`
	CreatedAt     pgtype.Timestamp  `json:"createdAt"`
	OwnerName     pgtype.Text       `json:"owner_name"`
	OwnerEmail    string            `json:"owner_email"`
	OwnerUsername pgtype.Text       `json:"owner_username"`
}

// ── OAuth ────────────────────────────────────────────────────────────────────
func (q *Queries) ListAdminOAuthClients(ctx context.Context) ([]ListAdminOAuthClientsRow, error) {
	rows, err := q.db.Query(ctx, listAdminOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminOAuthClientsRow{}
	for rows.Next() {
		var i ListAdminOAuthClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientId,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.HomepageUrl,
			&i.RedirectUris,
			&i.Scopes,
			&i.ClientType,
			&i.Status,
			&i.CreatedAt,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPromos = `-- name: ListAdminPromos :many
SELECT id, title, description, "ctaText", "ctaUrl", "imageUrl", "isActive", "createdAt", "updatedAt"
FROM "PartnerPromo"
ORDER BY "createdAt" DESC
`

func (q *Queries) ListAdminPromos(ctx context.Context) ([]PartnerPromo, error) {
	rows, err := q.db.Query(ctx, listAdminPromos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartnerPromo{}
	for rows.Next() {
		var i PartnerPromo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CtaText,
			&i.CtaUrl,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminTrends = `-- name: ListAdminTrends :many
SELECT id, hashtag, count, "createdAt", "updatedAt"
FROM "Trend"
ORDER BY count DESC
`

func (q *Queries) ListAdminTrends(ctx context.Context) ([]Trend, error) {
	rows, err := q.db.Query(ctx, listAdminTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trend{}
	for rows.Next() {
		var i Trend
		if err := rows.Scan(
			&i.ID,
			&i.Hashtag,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT u.id, u.name, u.email, u.username, u.role, u."isCertified", u."isShadowbanned",
       u."isSuspended", u."suspendReason", u."createdAt", u."updatedAt",
       p."subdomain" AS publication_subdomain
FROM "User" u
LEFT JOIN "Publication" p ON p.id = u."publicationId"
ORDER BY u."createdAt" DESC
`

type ListAdminUsersRow struct {
	ID                   string           `json:"id"`
	Name                 pgtype.Text      `json:"name"`
	Email                string           `json:"email"`
	Username             pgtype.Text      `json:"username"`
	Role                 string           `json:"role"`
	IsCertified          bool             `json:"isCertified"`
	IsShadowbanned       bool             `json:"isShadowbanned"`
	IsSuspended          bool             `json:"isSuspended"`
	SuspendReason        pgtype.Text      `json:"suspendReason"`
	CreatedAt            pgtype.Timestamp `json:"createdAt"`
	UpdatedAt            pgtype.Timestamp `json:"updatedAt"`
	PublicationSubdomain pgtype.Text      `json:"publication_subdomain"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.IsCertified,
			&i.IsShadowbanned,
			&i.IsSuspended,
			&i.SuspendReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicationSubdomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT d.id, d.recipient, d.status, d.channel, d.attempts, d.provider, d."lastError", d."createdAt",
       n.type::text AS notification_type, a.title AS article_title
FROM "NotificationDelivery" d
JOIN "Notification" n ON n.id = d."notificationId"
LEFT JOIN "Article" a ON a.id = n."articleId"
ORDER BY d."createdAt" DESC
LIMIT 50
`

type ListNotificationDeliveriesRow struct {
	ID               string           `json:"id"`
	Recipient        string           `json:"recipient"`
	Status           string           `json:"status"`
	Channel          string           `json:"channel"`
	Attempts         int32            `json:"attempts"`
	Provider         pgtype.Text      `json:"provider"`
	LastError        pgtype.Text      `json:"lastError"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	NotificationType string           `json:"notification_type"`
	ArticleTitle     pgtype.Text      `json:"article_title"`
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context) ([]ListNotificationDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationDeliveriesRow{}
	for rows.Next() {
		var i ListNotificationDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Recipient,
			&i.Status,
			&i.Channel,
			&i.Attempts,
			&i.Provider,
			&i.LastError,
			&i.CreatedAt,
			&i.NotificationType,
			&i.ArticleTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemConfigs = `-- name: ListSystemConfigs :many

SELECT key, value, description, "updatedAt" FROM "SystemConfig" ORDER BY key ASC
`

// ── Feature Flags / Config / Frontend / Translations ────────────────────────
func (q *Queries) ListSystemConfigs(ctx context.Context) ([]SystemConfig, error) {
	rows, err := q.db.Query(ctx, listSystemConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemConfig{}
	for rows.Next() {
		var i SystemConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryNotificationDelivery = `-- name: RetryNotificationDelivery :exec
UPDATE "NotificationDelivery"
SET status = 'QUEUED', "availableAt" = now(), "lastError" = NULL, "updatedAt" = now()
WHERE id = $1 AND status IN ('FAILED', 'DISABLED')
`

func (q *Queries) RetryNotificationDelivery(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, retryNotificationDelivery, id)
	return err
}

const setArticleEditorPick = `-- name: SetArticleEditorPick :one
UPDATE "Article" SET "isEditorPick" = $2, "updatedAt" = now() WHERE id = $1 RETURNING id, "isEditorPick"
`

type SetArticleEditorPickParams struct {
	ID           string `json:"id"`
	IsEditorPick bool   `json:"isEditorPick"`
}

type SetArticleEditorPickRow struct {
	ID           string `json:"id"`
	IsEditorPick bool   `json:"isEditorPick"`
}

func (q *Queries) SetArticleEditorPick(ctx context.Context, arg SetArticleEditorPickParams) (SetArticleEditorPickRow, error) {
	row := q.db.QueryRow(ctx, setArticleEditorPick, arg.ID, arg.IsEditorPick)
	var i SetArticleEditorPickRow
	err := row.Scan(&i.ID, &i.IsEditorPick)
	return i, err
}

const updateAdminOAuthClientStatus = `-- name: UpdateAdminOAuthClientStatus :one
UPDATE "OAuthClient" SET status = $2, "updatedAt" = now() WHERE id = $1
RETURNING id, status
`

type UpdateAdminOAuthClientStatusParams struct {
	ID     string            `json:"id"`
	Status OAuthClientStatus `json:"status"`
}

type UpdateAdminOAuthClientStatusRow struct {
	ID     string            `json:"id"`
	Status OAuthClientStatus `json:"status"`
}

func (q *Queries) UpdateAdminOAuthClientStatus(ctx context.Context, arg UpdateAdminOAuthClientStatusParams) (UpdateAdminOAuthClientStatusRow, error) {
	row := q.db.QueryRow(ctx, updateAdminOAuthClientStatus, arg.ID, arg.Status)
	var i UpdateAdminOAuthClientStatusRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const updateAdminUserApiAccess = `-- name: UpdateAdminUserApiAccess :one
UPDATE "User" SET "apiAccessStatus" = $2, "updatedAt" = now() WHERE id = $1
RETURNING id, "apiAccessStatus"
`

type UpdateAdminUserApiAccessParams struct {
	ID              string `json:"id"`
	ApiAccessStatus string `json:"apiAccessStatus"`
}

type UpdateAdminUserApiAccessRow struct {
	ID              string `json:"id"`
	ApiAccessStatus string `json:"apiAccessStatus"`
}

func (q *Queries) UpdateAdminUserApiAccess(ctx context.Context, arg UpdateAdminUserApiAccessParams) (UpdateAdminUserApiAccessRow, error) {
	row := q.db.QueryRow(ctx, updateAdminUserApiAccess, arg.ID, arg.ApiAccessStatus)
	var i UpdateAdminUserApiAccessRow
	err := row.Scan(&i.ID, &i.ApiAccessStatus)
	return i, err
}

const updateAdminUserModeration = `-- name: UpdateAdminUserModeration :one
UPDATE "User"
SET "isCertified" = $2, "isShadowbanned" = $3, "isSuspended" = $4,
    "suspendReason" = $5, "updatedAt" = now()
WHERE id = $1
RETURNING id, role, "isCertified", "isShadowbanned", "isSuspended", "suspendReason"
`

type UpdateAdminUserModerationParams struct {
	ID             string      `json:"id"`
	IsCertified    bool        `json:"isCertified"`
	IsShadowbanned bool        `json:"isShadowbanned"`
	IsSuspended    bool        `json:"isSuspended"`
	SuspendReason  pgtype.Text `json:"suspendReason"`
}

type UpdateAdminUserModerationRow struct {
	ID             string      `json:"id"`
	Role           string      `json:"role"`
	IsCertified    bool        `json:"isCertified"`
	IsShadowbanned bool        `json:"isShadowbanned"`
	IsSuspended    bool        `json:"isSuspended"`
	SuspendReason  pgtype.Text `json:"suspendReason"`
}

func (q *Queries) UpdateAdminUserModeration(ctx context.Context, arg UpdateAdminUserModerationParams) (UpdateAdminUserModerationRow, error) {
	row := q.db.QueryRow(ctx, updateAdminUserModeration,
		arg.ID,
		arg.IsCertified,
		arg.IsShadowbanned,
		arg.IsSuspended,
		arg.SuspendReason,
	)
	var i UpdateAdminUserModerationRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.IsCertified,
		&i.IsShadowbanned,
		&i.IsSuspended,
		&i.SuspendReason,
	)
	return i, err
}

const updatePromoActive = `-- name: UpdatePromoActive :one
UPDATE "PartnerPromo" SET "isActive" = $2, "updatedAt" = now() WHERE id = $1
RETURNING id, "isActive"
`

type UpdatePromoActiveParams struct {
	ID       string `json:"id"`
	IsActive bool   `json:"isActive"`
}

type UpdatePromoActiveRow struct {
	ID       string `json:"id"`
	IsActive bool   `json:"isActive"`
}

func (q *Queries) UpdatePromoActive(ctx context.Context, arg UpdatePromoActiveParams) (UpdatePromoActiveRow, error) {
	row := q.db.QueryRow(ctx, updatePromoActive, arg.ID, arg.IsActive)
	var i UpdatePromoActiveRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const updatePublicationCertified = `-- name: UpdatePublicationCertified :one
UPDATE "Publication"
SET "isCertified" = $2, "updatedAt" = now()
WHERE id = $1
RETURNING id, "isCertified"
`

type UpdatePublicationCertifiedParams struct {
	ID          string `json:"id"`
	IsCertified bool   `json:"isCertified"`
}

type UpdatePublicationCertifiedRow struct {
	ID          string `json:"id"`
	IsCertified bool   `json:"isCertified"`
}

func (q *Queries) UpdatePublicationCertified(ctx context.Context, arg UpdatePublicationCertifiedParams) (UpdatePublicationCertifiedRow, error) {
	row := q.db.QueryRow(ctx, updatePublicationCertified, arg.ID, arg.IsCertified)
	var i UpdatePublicationCertifiedRow
	err := row.Scan(&i.ID, &i.IsCertified)
	return i, err
}

const updateTrendCount = `-- name: UpdateTrendCount :one
UPDATE "Trend" SET count = $2, "updatedAt" = now() WHERE id = $1 RETURNING id, hashtag, count
`

type UpdateTrendCountParams struct {
	ID    string `json:"id"`
	Count int32  `json:"count"`
}

type UpdateTrendCountRow struct {
	ID      string `json:"id"`
	Hashtag string `json:"hashtag"`
	Count   int32  `json:"count"`
}

func (q *Queries) UpdateTrendCount(ctx context.Context, arg UpdateTrendCountParams) (UpdateTrendCountRow, error) {
	row := q.db.QueryRow(ctx, updateTrendCount, arg.ID, arg.Count)
	var i UpdateTrendCountRow
	err := row.Scan(&i.ID, &i.Hashtag, &i.Count)
	return i, err
}

const upsertPromo = `-- name: UpsertPromo :one
INSERT INTO "PartnerPromo" (id, title, description, "ctaText", "ctaUrl", "isActive", "createdAt", "updatedAt")
VALUES (COALESCE(NULLIF($1, ''), gen_random_uuid()::text), $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description,
    "ctaText" = EXCLUDED."ctaText", "ctaUrl" = EXCLUDED."ctaUrl",
    "isActive" = EXCLUDED."isActive", "updatedAt" = now()
RETURNING id, title, description, "ctaText", "ctaUrl", "imageUrl", "isActive"
`

type UpsertPromoParams struct {
	Column1     interface{} `json:"column_1"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	CtaText     pgtype.Text `json:"ctaText"`
	CtaUrl      pgtype.Text `json:"ctaUrl"`
	IsActive    bool        `json:"isActive"`
}

type UpsertPromoRow struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	CtaText     pgtype.Text `json:"ctaText"`
	CtaUrl      pgtype.Text `json:"ctaUrl"`
	ImageUrl    pgtype.Text `json:"imageUrl"`
	IsActive    bool        `json:"isActive"`
}

func (q *Queries) UpsertPromo(ctx context.Context, arg UpsertPromoParams) (UpsertPromoRow, error) {
	row := q.db.QueryRow(ctx, upsertPromo,
		arg.Column1,
		arg.Title,
		arg.Description,
		arg.CtaText,
		arg.CtaUrl,
		arg.IsActive,
	)
	var i UpsertPromoRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CtaText,
		&i.CtaUrl,
		&i.ImageUrl,
		&i.IsActive,
	)
	return i, err
}

const upsertSystemConfig = `-- name: UpsertSystemConfig :one
INSERT INTO "SystemConfig" (key, value, description, "updatedAt")
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, "SystemConfig".description), "updatedAt" = now()
RETURNING key, value, description, "updatedAt"
`

type UpsertSystemConfigParams struct {
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, upsertSystemConfig, arg.Key, arg.Value, arg.Description)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrend = `-- name: UpsertTrend :one
INSERT INTO "Trend" (id, hashtag, count, "createdAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, now(), now())
ON CONFLICT (hashtag) DO UPDATE SET count = EXCLUDED.count, "updatedAt" = now()
RETURNING id, hashtag, count
`

type UpsertTrendParams struct {
	Hashtag string `json:"hashtag"`
	Count   int32  `json:"count"`
}

type UpsertTrendRow struct {
	ID      string `json:"id"`
	Hashtag string `json:"hashtag"`
	Count   int32  `json:"count"`
}

func (q *Queries) UpsertTrend(ctx context.Context, arg UpsertTrendParams) (UpsertTrendRow, error) {
	row := q.db.QueryRow(ctx, upsertTrend, arg.Hashtag, arg.Count)
	var i UpsertTrendRow
	err := row.Scan(&i.ID, &i.Hashtag, &i.Count)
	return i, err
}
