// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAudienceSummary = `-- name: GetAudienceSummary :one
SELECT
  COUNT(*)::int AS total,
  COUNT(*) FILTER (WHERE "isActive" = true)::int AS active,
  COUNT(*) FILTER (WHERE "isPremium" = true)::int AS premium
FROM "Subscriber"
WHERE "publicationId" = $1
`

type GetAudienceSummaryRow struct {
	Total   int32 `json:"total"`
	Active  int32 `json:"active"`
	Premium int32 `json:"premium"`
}

func (q *Queries) GetAudienceSummary(ctx context.Context, publicationid string) (GetAudienceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAudienceSummary, publicationid)
	var i GetAudienceSummaryRow
	err := row.Scan(&i.Total, &i.Active, &i.Premium)
	return i, err
}

const getFreeSubscriberCount = `-- name: GetFreeSubscriberCount :one
SELECT COUNT(*)::int AS count
FROM "Subscriber"
WHERE "publicationId" = $1 AND "isPremium" = false
`

func (q *Queries) GetFreeSubscriberCount(ctx context.Context, publicationid string) (int32, error) {
	row := q.db.QueryRow(ctx, getFreeSubscriberCount, publicationid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getPremiumActiveSubscribers = `-- name: GetPremiumActiveSubscribers :many
SELECT s."ltvCents", t."monthlyPriceCents"
FROM "Subscriber" s
LEFT JOIN "Tier" t ON t.id = s."tierId"
WHERE s."publicationId" = $1 AND s.status = 'ACTIVE' AND s."isPremium" = true
`

type GetPremiumActiveSubscribersRow struct {
	LtvCents          int32       `json:"ltvCents"`
	MonthlyPriceCents pgtype.Int4 `json:"monthlyPriceCents"`
}

func (q *Queries) GetPremiumActiveSubscribers(ctx context.Context, publicationid string) ([]GetPremiumActiveSubscribersRow, error) {
	rows, err := q.db.Query(ctx, getPremiumActiveSubscribers, publicationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPremiumActiveSubscribersRow{}
	for rows.Next() {
		var i GetPremiumActiveSubscribersRow
		if err := rows.Scan(&i.LtvCents, &i.MonthlyPriceCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentArticlesForAnalytics = `-- name: GetRecentArticlesForAnalytics :many
SELECT id, title, "createdAt"
FROM "Article"
WHERE "publicationId" = $1 AND published = true
ORDER BY "createdAt" DESC
LIMIT $2
`

type GetRecentArticlesForAnalyticsParams struct {
	PublicationId string `json:"publicationId"`
	Limit         int32  `json:"limit"`
}

type GetRecentArticlesForAnalyticsRow struct {
	ID        string           `json:"id"`
	Title     string           `json:"title"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) GetRecentArticlesForAnalytics(ctx context.Context, arg GetRecentArticlesForAnalyticsParams) ([]GetRecentArticlesForAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, getRecentArticlesForAnalytics, arg.PublicationId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentArticlesForAnalyticsRow{}
	for rows.Next() {
		var i GetRecentArticlesForAnalyticsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentThoughtsForAnalytics = `-- name: GetRecentThoughtsForAnalytics :many
SELECT id, content, "createdAt", "likeCount", "repostCount"
FROM "Post"
WHERE "authorId" = $1 AND "isDraft" = false AND "deletedAt" IS NULL
ORDER BY "createdAt" DESC
LIMIT $2
`

type GetRecentThoughtsForAnalyticsParams struct {
	AuthorId string `json:"authorId"`
	Limit    int32  `json:"limit"`
}

type GetRecentThoughtsForAnalyticsRow struct {
	ID          string           `json:"id"`
	Content     string           `json:"content"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	LikeCount   int32            `json:"likeCount"`
	RepostCount int32            `json:"repostCount"`
}

func (q *Queries) GetRecentThoughtsForAnalytics(ctx context.Context, arg GetRecentThoughtsForAnalyticsParams) ([]GetRecentThoughtsForAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, getRecentThoughtsForAnalytics, arg.AuthorId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentThoughtsForAnalyticsRow{}
	for rows.Next() {
		var i GetRecentThoughtsForAnalyticsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.LikeCount,
			&i.RepostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT id, email, "isActive", "isPremium", "ltvCents", "createdAt"
FROM "Subscriber"
WHERE "publicationId" = $1
ORDER BY "createdAt" DESC
`

type ListSubscribersRow struct {
	ID        string           `json:"id"`
	Email     string           `json:"email"`
	IsActive  bool             `json:"isActive"`
	IsPremium bool             `json:"isPremium"`
	LtvCents  int32            `json:"ltvCents"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) ListSubscribers(ctx context.Context, publicationid string) ([]ListSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listSubscribers, publicationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribersRow{}
	for rows.Next() {
		var i ListSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsActive,
			&i.IsPremium,
			&i.LtvCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
