// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics_reading_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReadingSessionsByArticleId = `-- name: CountReadingSessionsByArticleId :one
SELECT COUNT(*)::int AS count
FROM "ReadingSession"
WHERE "articleId" = $1
  AND ($2::timestamptz IS NULL OR "createdAt" >= $2)
`

type CountReadingSessionsByArticleIdParams struct {
	ArticleId string             `json:"articleId"`
	Column2   pgtype.Timestamptz `json:"column_2"`
}

func (q *Queries) CountReadingSessionsByArticleId(ctx context.Context, arg CountReadingSessionsByArticleIdParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReadingSessionsByArticleId, arg.ArticleId, arg.Column2)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countReadingSessionsByArticleIds = `-- name: CountReadingSessionsByArticleIds :many
SELECT COUNT(*)::int AS count
FROM "ReadingSession"
WHERE "articleId" = ANY($1::text[])
  AND ($2::timestamptz IS NULL OR "createdAt" >= $2)
`

type CountReadingSessionsByArticleIdsParams struct {
	Column1 []string           `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

// Variante batch pour provenance globale (tous les articleIds du créateur).
func (q *Queries) CountReadingSessionsByArticleIds(ctx context.Context, arg CountReadingSessionsByArticleIdsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, countReadingSessionsByArticleIds, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var count int32
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingSessionDailySeries = `-- name: GetReadingSessionDailySeries :many
SELECT to_char(date_trunc('day', "createdAt"), 'YYYY-MM-DD') AS day, COUNT(*)::int AS cnt
FROM "ReadingSession"
WHERE "articleId" = ANY($1::text[])
  AND ($2::timestamptz IS NULL OR "createdAt" >= $2)
GROUP BY date_trunc('day', "createdAt")
ORDER BY day
`

type GetReadingSessionDailySeriesParams struct {
	Column1 []string           `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

type GetReadingSessionDailySeriesRow struct {
	Day string `json:"day"`
	Cnt int32  `json:"cnt"`
}

func (q *Queries) GetReadingSessionDailySeries(ctx context.Context, arg GetReadingSessionDailySeriesParams) ([]GetReadingSessionDailySeriesRow, error) {
	rows, err := q.db.Query(ctx, getReadingSessionDailySeries, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReadingSessionDailySeriesRow{}
	for rows.Next() {
		var i GetReadingSessionDailySeriesRow
		if err := rows.Scan(&i.Day, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupByHostname = `-- name: GroupByHostname :many
SELECT hostname AS key, COUNT(*)::int AS count
FROM "ReadingSession"
WHERE "articleId" = ANY($1::text[])
  AND hostname IS NOT NULL
  AND ($2::timestamptz IS NULL OR "createdAt" >= $2)
GROUP BY hostname
ORDER BY count DESC
`

type GroupByHostnameParams struct {
	Column1 []string           `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

type GroupByHostnameRow struct {
	Key   pgtype.Text `json:"key"`
	Count int32       `json:"count"`
}

func (q *Queries) GroupByHostname(ctx context.Context, arg GroupByHostnameParams) ([]GroupByHostnameRow, error) {
	rows, err := q.db.Query(ctx, groupByHostname, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupByHostnameRow{}
	for rows.Next() {
		var i GroupByHostnameRow
		if err := rows.Scan(&i.Key, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupByReferrerUsername = `-- name: GroupByReferrerUsername :many
SELECT "referrerUsername" AS key, COUNT(*)::int AS count
FROM "ReadingSession"
WHERE "articleId" = ANY($1::text[])
  AND "referrerUsername" IS NOT NULL
  AND ($2::timestamptz IS NULL OR "createdAt" >= $2)
GROUP BY "referrerUsername"
ORDER BY count DESC
`

type GroupByReferrerUsernameParams struct {
	Column1 []string           `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

type GroupByReferrerUsernameRow struct {
	Key   pgtype.Text `json:"key"`
	Count int32       `json:"count"`
}

func (q *Queries) GroupByReferrerUsername(ctx context.Context, arg GroupByReferrerUsernameParams) ([]GroupByReferrerUsernameRow, error) {
	rows, err := q.db.Query(ctx, groupByReferrerUsername, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupByReferrerUsernameRow{}
	for rows.Next() {
		var i GroupByReferrerUsernameRow
		if err := rows.Scan(&i.Key, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupReadingSessionsByArticleId = `-- name: GroupReadingSessionsByArticleId :many
SELECT "articleId" AS article_id, COUNT(*)::int AS count
FROM "ReadingSession"
WHERE "articleId" = ANY($1::text[])
  AND ($2::timestamptz IS NULL OR "createdAt" >= $2)
GROUP BY "articleId"
ORDER BY count DESC
`

type GroupReadingSessionsByArticleIdParams struct {
	Column1 []string           `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

type GroupReadingSessionsByArticleIdRow struct {
	ArticleID string `json:"article_id"`
	Count     int32  `json:"count"`
}

func (q *Queries) GroupReadingSessionsByArticleId(ctx context.Context, arg GroupReadingSessionsByArticleIdParams) ([]GroupReadingSessionsByArticleIdRow, error) {
	rows, err := q.db.Query(ctx, groupReadingSessionsByArticleId, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupReadingSessionsByArticleIdRow{}
	for rows.Next() {
		var i GroupReadingSessionsByArticleIdRow
		if err := rows.Scan(&i.ArticleID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupReadingSessionsBySource = `-- name: GroupReadingSessionsBySource :many

SELECT source AS key, COUNT(*)::int AS count
FROM "ReadingSession"
WHERE "articleId" = ANY($1::text[])
  AND ($2::timestamptz IS NULL OR "createdAt" >= $2)
GROUP BY source
ORDER BY count DESC
`

type GroupReadingSessionsBySourceParams struct {
	Column1 []string           `json:"column_1"`
	Column2 pgtype.Timestamptz `json:"column_2"`
}

type GroupReadingSessionsBySourceRow struct {
	Key   string `json:"key"`
	Count int32  `json:"count"`
}

// Analytics ReadingSession — migration Prisma → Go (sqlc + raw SQL fallback).
// Remplace :
//
//	prisma.readingSession.groupBy { by: ['source'|'hostname'|'referrerUsername'|'articleId'] }
//	prisma.$queryRawUnsafe `SELECT to_char(date_trunc('day', "createdAt")...)`
//	prisma.readingSession.count
//	prisma.user.groupBy (demographie) — voir analytics_demographics.sql si besoin
//	prisma.article.findMany + attributions — voir ListAttributedArticleIDs ci-dessous
func (q *Queries) GroupReadingSessionsBySource(ctx context.Context, arg GroupReadingSessionsBySourceParams) ([]GroupReadingSessionsBySourceRow, error) {
	rows, err := q.db.Query(ctx, groupReadingSessionsBySource, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupReadingSessionsBySourceRow{}
	for rows.Next() {
		var i GroupReadingSessionsBySourceRow
		if err := rows.Scan(&i.Key, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupUsersByAgeRange = `-- name: GroupUsersByAgeRange :many
SELECT "ageRange"::text AS value, COUNT(*)::int AS count
FROM "User"
WHERE "ageRange" IS NOT NULL
  AND ($1::uuid[] IS NULL OR id = ANY($1::uuid[]))
GROUP BY "ageRange"
ORDER BY count DESC
`

type GroupUsersByAgeRangeRow struct {
	Value string `json:"value"`
	Count int32  `json:"count"`
}

func (q *Queries) GroupUsersByAgeRange(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByAgeRangeRow, error) {
	rows, err := q.db.Query(ctx, groupUsersByAgeRange, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupUsersByAgeRangeRow{}
	for rows.Next() {
		var i GroupUsersByAgeRangeRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupUsersByCountry = `-- name: GroupUsersByCountry :many
SELECT "countryCode" AS value, COUNT(*)::int AS count
FROM "User"
WHERE "countryCode" IS NOT NULL
  AND ($1::uuid[] IS NULL OR id = ANY($1::uuid[]))
GROUP BY "countryCode"
ORDER BY count DESC
`

type GroupUsersByCountryRow struct {
	Value pgtype.Text `json:"value"`
	Count int32       `json:"count"`
}

func (q *Queries) GroupUsersByCountry(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByCountryRow, error) {
	rows, err := q.db.Query(ctx, groupUsersByCountry, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupUsersByCountryRow{}
	for rows.Next() {
		var i GroupUsersByCountryRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupUsersByGender = `-- name: GroupUsersByGender :many
SELECT gender::text AS value, COUNT(*)::int AS count
FROM "User"
WHERE gender IS NOT NULL
  AND ($1::uuid[] IS NULL OR id = ANY($1::uuid[]))
GROUP BY gender
ORDER BY count DESC
`

type GroupUsersByGenderRow struct {
	Value string `json:"value"`
	Count int32  `json:"count"`
}

func (q *Queries) GroupUsersByGender(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByGenderRow, error) {
	rows, err := q.db.Query(ctx, groupUsersByGender, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupUsersByGenderRow{}
	for rows.Next() {
		var i GroupUsersByGenderRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupUsersByLanguage = `-- name: GroupUsersByLanguage :many
SELECT "languageCode" AS value, COUNT(*)::int AS count
FROM "User"
WHERE "languageCode" IS NOT NULL
  AND ($1::uuid[] IS NULL OR id = ANY($1::uuid[]))
GROUP BY "languageCode"
ORDER BY count DESC
`

type GroupUsersByLanguageRow struct {
	Value pgtype.Text `json:"value"`
	Count int32       `json:"count"`
}

func (q *Queries) GroupUsersByLanguage(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByLanguageRow, error) {
	rows, err := q.db.Query(ctx, groupUsersByLanguage, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupUsersByLanguageRow{}
	for rows.Next() {
		var i GroupUsersByLanguageRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributedArticleIDs = `-- name: ListAttributedArticleIDs :many
SELECT a.id
FROM "Article" a
WHERE a.published = true
  AND (
    a."publicationId" = $1
    OR EXISTS (
      SELECT 1 FROM "ArticleAttribution" aa
      WHERE aa."articleId" = a.id
        AND aa."userId" = $2
        AND aa."consentStatus" = 'ACCEPTED'
        AND aa."isVisible" = true
    )
  )
`

type ListAttributedArticleIDsParams struct {
	PublicationId string      `json:"publicationId"`
	UserId        pgtype.UUID `json:"userId"`
}

// Articles attribués à un créateur : publication directe OU co-signés via ArticleAttribution ACCEPTED + visible.
// Miroir de prisma.article.findMany { OR: [{publicationId}, {attributions: {some: {userId, consentStatus, isVisible}}}] } où published = true.
func (q *Queries) ListAttributedArticleIDs(ctx context.Context, arg ListAttributedArticleIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttributedArticleIDs, arg.PublicationId, arg.UserId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
