// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaborations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleForCollaboration = `-- name: GetArticleForCollaboration :one

SELECT id, "authorId"::text AS author_id, "publicationId"
FROM "Article"
WHERE id = $1
`

type GetArticleForCollaborationRow struct {
	ID            string `json:"id"`
	AuthorID      string `json:"author_id"`
	PublicationId string `json:"publicationId"`
}

// Collaborations / attributions (migration de studio advanced/actions.ts).
func (q *Queries) GetArticleForCollaboration(ctx context.Context, id string) (GetArticleForCollaborationRow, error) {
	row := q.db.QueryRow(ctx, getArticleForCollaboration, id)
	var i GetArticleForCollaborationRow
	err := row.Scan(&i.ID, &i.AuthorID, &i.PublicationId)
	return i, err
}

const getCollaborationRequestByID = `-- name: GetCollaborationRequestByID :one
SELECT id, "articleId", "inviterId"::text, "inviteeId"::text, status,
       "requestedRole", "requestedOrder", "showOnPublicProfile", "createdAt"
FROM "CollaborationRequest"
WHERE id = $1
`

type GetCollaborationRequestByIDRow struct {
	ID                  string           `json:"id"`
	ArticleId           string           `json:"articleId"`
	InviterId           string           `json:"inviterId"`
	InviteeId           string           `json:"inviteeId"`
	Status              string           `json:"status"`
	RequestedRole       string           `json:"requestedRole"`
	RequestedOrder      int32            `json:"requestedOrder"`
	ShowOnPublicProfile bool             `json:"showOnPublicProfile"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) GetCollaborationRequestByID(ctx context.Context, id string) (GetCollaborationRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getCollaborationRequestByID, id)
	var i GetCollaborationRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.ArticleId,
		&i.InviterId,
		&i.InviteeId,
		&i.Status,
		&i.RequestedRole,
		&i.RequestedOrder,
		&i.ShowOnPublicProfile,
		&i.CreatedAt,
	)
	return i, err
}

const getUserWithCollabPrefsByEmail = `-- name: GetUserWithCollabPrefsByEmail :one
SELECT u.id::text AS id, u.email, u.name, u.username,
       u."isSuspended", u."isShadowbanned",
       COALESCE(s."allowCollaborationInvites", true) AS allow_collab
FROM "User" u
LEFT JOIN "UserSettings" s ON s."userId" = u.id
WHERE u.email = $1
`

type GetUserWithCollabPrefsByEmailRow struct {
	ID             string      `json:"id"`
	Email          string      `json:"email"`
	Name           pgtype.Text `json:"name"`
	Username       pgtype.Text `json:"username"`
	IsSuspended    bool        `json:"isSuspended"`
	IsShadowbanned bool        `json:"isShadowbanned"`
	AllowCollab    bool        `json:"allow_collab"`
}

func (q *Queries) GetUserWithCollabPrefsByEmail(ctx context.Context, email string) (GetUserWithCollabPrefsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserWithCollabPrefsByEmail, email)
	var i GetUserWithCollabPrefsByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.IsSuspended,
		&i.IsShadowbanned,
		&i.AllowCollab,
	)
	return i, err
}

const getUserWithCollabPrefsByID = `-- name: GetUserWithCollabPrefsByID :one
SELECT u.id::text AS id, u.email, u.name, u.username,
       u."isSuspended", u."isShadowbanned",
       COALESCE(s."allowCollaborationInvites", true) AS allow_collab
FROM "User" u
LEFT JOIN "UserSettings" s ON s."userId" = u.id
WHERE u.id = $1
`

type GetUserWithCollabPrefsByIDRow struct {
	ID             string      `json:"id"`
	Email          string      `json:"email"`
	Name           pgtype.Text `json:"name"`
	Username       pgtype.Text `json:"username"`
	IsSuspended    bool        `json:"isSuspended"`
	IsShadowbanned bool        `json:"isShadowbanned"`
	AllowCollab    bool        `json:"allow_collab"`
}

func (q *Queries) GetUserWithCollabPrefsByID(ctx context.Context, id string) (GetUserWithCollabPrefsByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithCollabPrefsByID, id)
	var i GetUserWithCollabPrefsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Username,
		&i.IsSuspended,
		&i.IsShadowbanned,
		&i.AllowCollab,
	)
	return i, err
}

const insertArticleContributorNotification = `-- name: InsertArticleContributorNotification :exec
INSERT INTO "Notification" (id, "recipientId", "senderId", type, "articleId")
SELECT gen_random_uuid()::text, $1::uuid, $2::uuid, $3::"NotificationType", $4::text
WHERE $1::uuid <> $2::uuid
  AND NOT EXISTS (
    SELECT 1 FROM "Notification" n
    WHERE n."recipientId" = $1::uuid AND n."senderId" = $2::uuid
      AND n.type = $3::"NotificationType" AND n."articleId" = $4::text
      AND n."isRead" = false
  )
`

type InsertArticleContributorNotificationParams struct {
	Column1 pgtype.UUID      `json:"column_1"`
	Column2 pgtype.UUID      `json:"column_2"`
	Column3 NotificationType `json:"column_3"`
	Column4 string           `json:"column_4"`
}

// Notification in-app (jamais perdue) : dédup par (recipient, sender, type,
// articleId, non-lue) + pas d'auto-notification. Casts explicites : évite
// l'ambiguïté uuid/text en protocole étendu (operator does not exist).
func (q *Queries) InsertArticleContributorNotification(ctx context.Context, arg InsertArticleContributorNotificationParams) error {
	_, err := q.db.Exec(ctx, insertArticleContributorNotification,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const isActiveMediaMember = `-- name: IsActiveMediaMember :one
SELECT EXISTS (
  SELECT 1 FROM "MediaMember" mm
  JOIN "Media" m ON m.id = mm."mediaId"
  WHERE m."publicationId" = $1 AND mm."userId" = $2 AND mm.status = 'active'
) AS "exists"
`

type IsActiveMediaMemberParams struct {
	PublicationId string      `json:"publicationId"`
	UserId        pgtype.UUID `json:"userId"`
}

func (q *Queries) IsActiveMediaMember(ctx context.Context, arg IsActiveMediaMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveMediaMember, arg.PublicationId, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listReceivedCollaborationRequests = `-- name: ListReceivedCollaborationRequests :many
SELECT cr.id, cr."articleId", cr.status, cr."requestedRole", cr."requestedOrder",
       cr."showOnPublicProfile", cr."createdAt",
       a.title AS article_title, a.slug AS article_slug,
       u.id::text AS user_id, u.name AS user_name, u.email AS user_email, u.username AS user_username
FROM "CollaborationRequest" cr
JOIN "Article" a ON a.id = cr."articleId"
JOIN "User" u ON u.id = cr."inviterId"
WHERE cr."inviteeId" = $1
ORDER BY cr."createdAt" DESC
`

type ListReceivedCollaborationRequestsRow struct {
	ID                  string           `json:"id"`
	ArticleId           string           `json:"articleId"`
	Status              string           `json:"status"`
	RequestedRole       string           `json:"requestedRole"`
	RequestedOrder      int32            `json:"requestedOrder"`
	ShowOnPublicProfile bool             `json:"showOnPublicProfile"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	ArticleTitle        string           `json:"article_title"`
	ArticleSlug         string           `json:"article_slug"`
	UserID              string           `json:"user_id"`
	UserName            pgtype.Text      `json:"user_name"`
	UserEmail           string           `json:"user_email"`
	UserUsername        pgtype.Text      `json:"user_username"`
}

func (q *Queries) ListReceivedCollaborationRequests(ctx context.Context, inviteeid pgtype.UUID) ([]ListReceivedCollaborationRequestsRow, error) {
	rows, err := q.db.Query(ctx, listReceivedCollaborationRequests, inviteeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceivedCollaborationRequestsRow{}
	for rows.Next() {
		var i ListReceivedCollaborationRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleId,
			&i.Status,
			&i.RequestedRole,
			&i.RequestedOrder,
			&i.ShowOnPublicProfile,
			&i.CreatedAt,
			&i.ArticleTitle,
			&i.ArticleSlug,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.UserUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentCollaborationRequests = `-- name: ListSentCollaborationRequests :many
SELECT cr.id, cr."articleId", cr.status, cr."requestedRole", cr."requestedOrder",
       cr."showOnPublicProfile", cr."createdAt",
       a.title AS article_title, a.slug AS article_slug,
       u.id::text AS user_id, u.name AS user_name, u.email AS user_email, u.username AS user_username
FROM "CollaborationRequest" cr
JOIN "Article" a ON a.id = cr."articleId"
JOIN "User" u ON u.id = cr."inviteeId"
WHERE cr."inviterId" = $1
ORDER BY cr."createdAt" DESC
`

type ListSentCollaborationRequestsRow struct {
	ID                  string           `json:"id"`
	ArticleId           string           `json:"articleId"`
	Status              string           `json:"status"`
	RequestedRole       string           `json:"requestedRole"`
	RequestedOrder      int32            `json:"requestedOrder"`
	ShowOnPublicProfile bool             `json:"showOnPublicProfile"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
	ArticleTitle        string           `json:"article_title"`
	ArticleSlug         string           `json:"article_slug"`
	UserID              string           `json:"user_id"`
	UserName            pgtype.Text      `json:"user_name"`
	UserEmail           string           `json:"user_email"`
	UserUsername        pgtype.Text      `json:"user_username"`
}

func (q *Queries) ListSentCollaborationRequests(ctx context.Context, inviterid pgtype.UUID) ([]ListSentCollaborationRequestsRow, error) {
	rows, err := q.db.Query(ctx, listSentCollaborationRequests, inviterid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSentCollaborationRequestsRow{}
	for rows.Next() {
		var i ListSentCollaborationRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleId,
			&i.Status,
			&i.RequestedRole,
			&i.RequestedOrder,
			&i.ShowOnPublicProfile,
			&i.CreatedAt,
			&i.ArticleTitle,
			&i.ArticleSlug,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.UserUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCollaborationRequestsForArticle = `-- name: RevokeCollaborationRequestsForArticle :exec
UPDATE "CollaborationRequest"
SET status = 'REVOKED', "showOnPublicProfile" = false, "updatedAt" = now()
WHERE "articleId" = $1 AND "inviteeId" = $2
`

type RevokeCollaborationRequestsForArticleParams struct {
	ArticleId string      `json:"articleId"`
	InviteeId pgtype.UUID `json:"inviteeId"`
}

func (q *Queries) RevokeCollaborationRequestsForArticle(ctx context.Context, arg RevokeCollaborationRequestsForArticleParams) error {
	_, err := q.db.Exec(ctx, revokeCollaborationRequestsForArticle, arg.ArticleId, arg.InviteeId)
	return err
}

const updateArticleAttributionConsent = `-- name: UpdateArticleAttributionConsent :exec
UPDATE "ArticleAttribution"
SET "consentStatus" = $3, "isVisible" = false, "consentUpdatedAt" = now(), "updatedAt" = now()
WHERE "articleId" = $1 AND "userId" = $2
`

type UpdateArticleAttributionConsentParams struct {
	ArticleId     string      `json:"articleId"`
	UserId        pgtype.UUID `json:"userId"`
	ConsentStatus string      `json:"consentStatus"`
}

func (q *Queries) UpdateArticleAttributionConsent(ctx context.Context, arg UpdateArticleAttributionConsentParams) error {
	_, err := q.db.Exec(ctx, updateArticleAttributionConsent, arg.ArticleId, arg.UserId, arg.ConsentStatus)
	return err
}

const updateCollaborationRequestResponse = `-- name: UpdateCollaborationRequestResponse :exec
UPDATE "CollaborationRequest"
SET status = $2, "showOnPublicProfile" = $3, "acceptedAt" = $4, "updatedAt" = now()
WHERE id = $1
`

type UpdateCollaborationRequestResponseParams struct {
	ID                  string           `json:"id"`
	Status              string           `json:"status"`
	ShowOnPublicProfile bool             `json:"showOnPublicProfile"`
	AcceptedAt          pgtype.Timestamp `json:"acceptedAt"`
}

func (q *Queries) UpdateCollaborationRequestResponse(ctx context.Context, arg UpdateCollaborationRequestResponseParams) error {
	_, err := q.db.Exec(ctx, updateCollaborationRequestResponse,
		arg.ID,
		arg.Status,
		arg.ShowOnPublicProfile,
		arg.AcceptedAt,
	)
	return err
}

const upsertArticleAttribution = `-- name: UpsertArticleAttribution :exec
INSERT INTO "ArticleAttribution" (id, "articleId", "userId", role, "order", "isVisible",
                                  "consentStatus", "consentUpdatedAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, 'ACCEPTED', now(), now())
ON CONFLICT ("articleId", "userId") DO UPDATE SET
  role = $3, "order" = $4, "isVisible" = $5, "consentStatus" = 'ACCEPTED',
  "consentUpdatedAt" = now(), "updatedAt" = now()
`

type UpsertArticleAttributionParams struct {
	ArticleId string      `json:"articleId"`
	UserId    pgtype.UUID `json:"userId"`
	Role      string      `json:"role"`
	Order     int32       `json:"order"`
	IsVisible bool        `json:"isVisible"`
}

func (q *Queries) UpsertArticleAttribution(ctx context.Context, arg UpsertArticleAttributionParams) error {
	_, err := q.db.Exec(ctx, upsertArticleAttribution,
		arg.ArticleId,
		arg.UserId,
		arg.Role,
		arg.Order,
		arg.IsVisible,
	)
	return err
}

const upsertCollaborationRequest = `-- name: UpsertCollaborationRequest :one
INSERT INTO "CollaborationRequest" (id, "articleId", "inviterId", "inviteeId", status,
                                    "requestedRole", "requestedOrder", "showOnPublicProfile",
                                    "acceptedAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, 'PENDING', $4, $5, false, NULL, now())
ON CONFLICT ("articleId", "inviteeId") DO UPDATE SET
  "inviterId" = $2, status = 'PENDING', "requestedRole" = $4, "requestedOrder" = $5,
  "showOnPublicProfile" = false, "acceptedAt" = NULL, "updatedAt" = now()
RETURNING id, "articleId", "inviterId"::text, "inviteeId"::text, status,
          "requestedRole", "requestedOrder", "showOnPublicProfile", "createdAt"
`

type UpsertCollaborationRequestParams struct {
	ArticleId      string      `json:"articleId"`
	InviterId      pgtype.UUID `json:"inviterId"`
	InviteeId      pgtype.UUID `json:"inviteeId"`
	RequestedRole  string      `json:"requestedRole"`
	RequestedOrder int32       `json:"requestedOrder"`
}

type UpsertCollaborationRequestRow struct {
	ID                  string           `json:"id"`
	ArticleId           string           `json:"articleId"`
	InviterId           string           `json:"inviterId"`
	InviteeId           string           `json:"inviteeId"`
	Status              string           `json:"status"`
	RequestedRole       string           `json:"requestedRole"`
	RequestedOrder      int32            `json:"requestedOrder"`
	ShowOnPublicProfile bool             `json:"showOnPublicProfile"`
	CreatedAt           pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) UpsertCollaborationRequest(ctx context.Context, arg UpsertCollaborationRequestParams) (UpsertCollaborationRequestRow, error) {
	row := q.db.QueryRow(ctx, upsertCollaborationRequest,
		arg.ArticleId,
		arg.InviterId,
		arg.InviteeId,
		arg.RequestedRole,
		arg.RequestedOrder,
	)
	var i UpsertCollaborationRequestRow
	err := row.Scan(
		&i.ID,
		&i.ArticleId,
		&i.InviterId,
		&i.InviteeId,
		&i.Status,
		&i.RequestedRole,
		&i.RequestedOrder,
		&i.ShowOnPublicProfile,
		&i.CreatedAt,
	)
	return i, err
}
