// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteArticleComment = `-- name: DeleteArticleComment :exec
DELETE FROM "ArticleComment"
WHERE id = $1
`

func (q *Queries) DeleteArticleComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArticleComment, id)
	return err
}

const getArticleCommentAuthor = `-- name: GetArticleCommentAuthor :one
SELECT "authorId"::text AS author_id
FROM "ArticleComment"
WHERE id = $1
`

func (q *Queries) GetArticleCommentAuthor(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getArticleCommentAuthor, id)
	var author_id string
	err := row.Scan(&author_id)
	return author_id, err
}

const getArticleCommentsConfig = `-- name: GetArticleCommentsConfig :one
SELECT a."allowComments" AS article_allow_comments,
       a."authorId"::text AS author_id,
       a."publicationId" AS publication_id,
       p."allowComments" AS publication_allow_comments
FROM "Article" a
JOIN "Publication" p ON p.id = a."publicationId"
WHERE a.id = $1
`

type GetArticleCommentsConfigRow struct {
	ArticleAllowComments     bool   `json:"article_allow_comments"`
	AuthorID                 string `json:"author_id"`
	PublicationID            string `json:"publication_id"`
	PublicationAllowComments bool   `json:"publication_allow_comments"`
}

func (q *Queries) GetArticleCommentsConfig(ctx context.Context, id string) (GetArticleCommentsConfigRow, error) {
	row := q.db.QueryRow(ctx, getArticleCommentsConfig, id)
	var i GetArticleCommentsConfigRow
	err := row.Scan(
		&i.ArticleAllowComments,
		&i.AuthorID,
		&i.PublicationID,
		&i.PublicationAllowComments,
	)
	return i, err
}

const getCommentParentAuthor = `-- name: GetCommentParentAuthor :one
SELECT "authorId"::text AS author_id
FROM "ArticleComment"
WHERE id = $1
`

func (q *Queries) GetCommentParentAuthor(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getCommentParentAuthor, id)
	var author_id string
	err := row.Scan(&author_id)
	return author_id, err
}

const getCommentWithAuthor = `-- name: GetCommentWithAuthor :one
SELECT c.id, c."content", c."createdAt", c."updatedAt", c."articleId",
       c."authorId"::text AS author_id, c."parentId",
       u.name AS author_name,
       u.username AS author_username,
       u."logoUrl" AS author_logo_url,
       u."isCertified" AS author_is_certified
FROM "ArticleComment" c
JOIN "User" u ON u.id = c."authorId"
WHERE c.id = $1
`

type GetCommentWithAuthorRow struct {
	ID                string           `json:"id"`
	Content           string           `json:"content"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
	ArticleId         string           `json:"articleId"`
	AuthorID          string           `json:"author_id"`
	ParentId          pgtype.Text      `json:"parentId"`
	AuthorName        pgtype.Text      `json:"author_name"`
	AuthorUsername    pgtype.Text      `json:"author_username"`
	AuthorLogoUrl     pgtype.Text      `json:"author_logo_url"`
	AuthorIsCertified bool             `json:"author_is_certified"`
}

func (q *Queries) GetCommentWithAuthor(ctx context.Context, id string) (GetCommentWithAuthorRow, error) {
	row := q.db.QueryRow(ctx, getCommentWithAuthor, id)
	var i GetCommentWithAuthorRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArticleId,
		&i.AuthorID,
		&i.ParentId,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorLogoUrl,
		&i.AuthorIsCertified,
	)
	return i, err
}

const insertArticleComment = `-- name: InsertArticleComment :one
INSERT INTO "ArticleComment" (id, "content", "articleId", "authorId", "parentId", "createdAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, now(), now())
RETURNING id, "content", "createdAt", "updatedAt", "articleId", "authorId"::text AS author_id, "parentId"
`

type InsertArticleCommentParams struct {
	Content   string      `json:"content"`
	ArticleId string      `json:"articleId"`
	AuthorId  pgtype.UUID `json:"authorId"`
	ParentId  pgtype.Text `json:"parentId"`
}

type InsertArticleCommentRow struct {
	ID        string           `json:"id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	ArticleId string           `json:"articleId"`
	AuthorID  string           `json:"author_id"`
	ParentId  pgtype.Text      `json:"parentId"`
}

func (q *Queries) InsertArticleComment(ctx context.Context, arg InsertArticleCommentParams) (InsertArticleCommentRow, error) {
	row := q.db.QueryRow(ctx, insertArticleComment,
		arg.Content,
		arg.ArticleId,
		arg.AuthorId,
		arg.ParentId,
	)
	var i InsertArticleCommentRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArticleId,
		&i.AuthorID,
		&i.ParentId,
	)
	return i, err
}

const listArticleComments = `-- name: ListArticleComments :many
SELECT c.id, c."content", c."createdAt", c."updatedAt", c."articleId",
       c."authorId"::text AS author_id, c."parentId",
       u.name AS author_name,
       u.username AS author_username,
       u."logoUrl" AS author_logo_url,
       u."isCertified" AS author_is_certified
FROM "ArticleComment" c
JOIN "User" u ON u.id = c."authorId"
WHERE c."articleId" = $1
ORDER BY c."createdAt" ASC
`

type ListArticleCommentsRow struct {
	ID                string           `json:"id"`
	Content           string           `json:"content"`
	CreatedAt         pgtype.Timestamp `json:"createdAt"`
	UpdatedAt         pgtype.Timestamp `json:"updatedAt"`
	ArticleId         string           `json:"articleId"`
	AuthorID          string           `json:"author_id"`
	ParentId          pgtype.Text      `json:"parentId"`
	AuthorName        pgtype.Text      `json:"author_name"`
	AuthorUsername    pgtype.Text      `json:"author_username"`
	AuthorLogoUrl     pgtype.Text      `json:"author_logo_url"`
	AuthorIsCertified bool             `json:"author_is_certified"`
}

func (q *Queries) ListArticleComments(ctx context.Context, articleid string) ([]ListArticleCommentsRow, error) {
	rows, err := q.db.Query(ctx, listArticleComments, articleid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticleCommentsRow{}
	for rows.Next() {
		var i ListArticleCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleId,
			&i.AuthorID,
			&i.ParentId,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogoUrl,
			&i.AuthorIsCertified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
