// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devtools.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevtoolsArticles = `-- name: CountDevtoolsArticles :one
SELECT count(*) FROM "Article"
`

func (q *Queries) CountDevtoolsArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevtoolsArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevtoolsLikes = `-- name: CountDevtoolsLikes :one
SELECT count(*) FROM "Like"
`

func (q *Queries) CountDevtoolsLikes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevtoolsLikes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevtoolsSubscribers = `-- name: CountDevtoolsSubscribers :one
SELECT count(*) FROM "Subscriber"
`

func (q *Queries) CountDevtoolsSubscribers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevtoolsSubscribers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevtoolsThoughts = `-- name: CountDevtoolsThoughts :one
SELECT count(*) FROM "Post"
`

func (q *Queries) CountDevtoolsThoughts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevtoolsThoughts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDevtoolsUsers = `-- name: CountDevtoolsUsers :one
SELECT count(*) FROM "User"
`

func (q *Queries) CountDevtoolsUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDevtoolsUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserRole = `-- name: GetUserRole :one

SELECT role FROM "User" WHERE id = $1
`

// DevTools — inspecteur de données (panneau dev-only des apps).
// Rôle : lecture seule, réservé au superadmin (vérifié côté handler).
func (q *Queries) GetUserRole(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listDevtoolsUsers = `-- name: ListDevtoolsUsers :many
SELECT u.id, u.name, u.email, u.username, u.role, u."createdAt",
       p."subdomain", p."customDomain", p."accentColor", p."layoutStyle"
FROM "User" u
LEFT JOIN "Publication" p ON p.id = u."publicationId"
ORDER BY u."createdAt" DESC
`

type ListDevtoolsUsersRow struct {
	ID           string           `json:"id"`
	Name         pgtype.Text      `json:"name"`
	Email        string           `json:"email"`
	Username     pgtype.Text      `json:"username"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	Subdomain    pgtype.Text      `json:"subdomain"`
	CustomDomain pgtype.Text      `json:"customDomain"`
	AccentColor  pgtype.Text      `json:"accentColor"`
	LayoutStyle  pgtype.Text      `json:"layoutStyle"`
}

func (q *Queries) ListDevtoolsUsers(ctx context.Context) ([]ListDevtoolsUsersRow, error) {
	rows, err := q.db.Query(ctx, listDevtoolsUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDevtoolsUsersRow{}
	for rows.Next() {
		var i ListDevtoolsUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
			&i.Subdomain,
			&i.CustomDomain,
			&i.AccentColor,
			&i.LayoutStyle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
