// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const findFollowingFeed = `-- name: FindFollowingFeed :many
SELECT p.id,
       p.content,
       p."authorId",
       p."createdAt",
       p.tags,
       p."imageUrl",
       p."likeCount",
       p."repostCount",
       p."replyCount",
       p."parentId",
       p."rootId",
       p."repostId",
       p."replyRestriction",
       p."isPinned",
       p."isHiddenByAuthor",
       u.id::text     AS author_id,
       u.name         AS author_name,
       u.username     AS author_username,
       u."logoUrl"    AS author_logo,
       u."isCertified" AS author_certified,
       (CASE WHEN l."userId" IS NOT NULL THEN true ELSE false END) AS viewer_liked,
       (CASE WHEN r.id IS NOT NULL THEN true ELSE false END)      AS viewer_reposted
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
LEFT JOIN "Like" l ON l."postId" = p.id AND l."userId" = $1
LEFT JOIN "Post" r ON r."repostId" = p.id AND r."authorId" = $1 AND r."deletedAt" IS NULL AND (r.content = '' OR r.content = ' ')
WHERE p."authorId" = ANY($2::uuid[])
  AND u."isShadowbanned" = false
  AND u."isSuspended" = false
  AND p."isDraft" = false
  AND p."deletedAt" IS NULL
  AND (p."scheduledAt" IS NULL OR p."scheduledAt" <= now())
  AND p.visibility IN ('public', 'followers')
ORDER BY p."createdAt" DESC, p.id DESC
LIMIT $4 OFFSET $3
`

type FindFollowingFeedParams struct {
	ViewerID  pgtype.UUID   `json:"viewer_id"`
	AuthorIds []pgtype.UUID `json:"author_ids"`
	SkipCount int32         `json:"skip_count"`
	TakeCount int32         `json:"take_count"`
}

type FindFollowingFeedRow struct {
	ID               string           `json:"id"`
	Content          string           `json:"content"`
	AuthorId         string           `json:"authorId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Tags             []string         `json:"tags"`
	ImageUrl         pgtype.Text      `json:"imageUrl"`
	LikeCount        int32            `json:"likeCount"`
	RepostCount      int32            `json:"repostCount"`
	ReplyCount       int32            `json:"replyCount"`
	ParentId         pgtype.Text      `json:"parentId"`
	RootId           pgtype.Text      `json:"rootId"`
	RepostId         pgtype.Text      `json:"repostId"`
	ReplyRestriction string           `json:"replyRestriction"`
	IsPinned         bool             `json:"isPinned"`
	IsHiddenByAuthor bool             `json:"isHiddenByAuthor"`
	AuthorID         string           `json:"author_id"`
	AuthorName       pgtype.Text      `json:"author_name"`
	AuthorUsername   pgtype.Text      `json:"author_username"`
	AuthorLogo       pgtype.Text      `json:"author_logo"`
	AuthorCertified  bool             `json:"author_certified"`
	ViewerLiked      bool             `json:"viewer_liked"`
	ViewerReposted   bool             `json:"viewer_reposted"`
}

func (q *Queries) FindFollowingFeed(ctx context.Context, arg FindFollowingFeedParams) ([]FindFollowingFeedRow, error) {
	rows, err := q.db.Query(ctx, findFollowingFeed,
		arg.ViewerID,
		arg.AuthorIds,
		arg.SkipCount,
		arg.TakeCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindFollowingFeedRow{}
	for rows.Next() {
		var i FindFollowingFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorId,
			&i.CreatedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.LikeCount,
			&i.RepostCount,
			&i.ReplyCount,
			&i.ParentId,
			&i.RootId,
			&i.RepostId,
			&i.ReplyRestriction,
			&i.IsPinned,
			&i.IsHiddenByAuthor,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogo,
			&i.AuthorCertified,
			&i.ViewerLiked,
			&i.ViewerReposted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPostsByAuthor = `-- name: FindPostsByAuthor :many
SELECT p.id,
       p.content,
       p."authorId",
       p."createdAt",
       p.tags,
       p."imageUrl",
       p."likeCount",
       p."repostCount",
       p."replyCount",
       p."parentId",
       p."rootId",
       p."repostId",
       p."replyRestriction",
       p."isPinned",
       p."isHiddenByAuthor",
       u.id::text     AS author_id,
       u.name         AS author_name,
       u.username     AS author_username,
       u."logoUrl"    AS author_logo,
       u."isCertified" AS author_certified,
       (CASE WHEN l."userId" IS NOT NULL THEN true ELSE false END) AS viewer_liked,
       (CASE WHEN r.id IS NOT NULL THEN true ELSE false END)      AS viewer_reposted
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
LEFT JOIN "Like" l ON l."postId" = p.id AND l."userId" = $1
LEFT JOIN "Post" r ON r."repostId" = p.id AND r."authorId" = $1 AND r."deletedAt" IS NULL AND (r.content = '' OR r.content = ' ')
WHERE p."authorId" = $2::uuid
  AND u."isShadowbanned" = false
  AND u."isSuspended" = false
  AND p."isDraft" = false
  AND p."deletedAt" IS NULL
  AND (p."scheduledAt" IS NULL OR p."scheduledAt" <= now())
  AND p.visibility = 'public'
ORDER BY p."createdAt" DESC, p.id DESC
LIMIT $4 OFFSET $3
`

type FindPostsByAuthorParams struct {
	ViewerID  pgtype.UUID `json:"viewer_id"`
	AuthorID  pgtype.UUID `json:"author_id"`
	SkipCount int32       `json:"skip_count"`
	TakeCount int32       `json:"take_count"`
}

type FindPostsByAuthorRow struct {
	ID               string           `json:"id"`
	Content          string           `json:"content"`
	AuthorId         string           `json:"authorId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Tags             []string         `json:"tags"`
	ImageUrl         pgtype.Text      `json:"imageUrl"`
	LikeCount        int32            `json:"likeCount"`
	RepostCount      int32            `json:"repostCount"`
	ReplyCount       int32            `json:"replyCount"`
	ParentId         pgtype.Text      `json:"parentId"`
	RootId           pgtype.Text      `json:"rootId"`
	RepostId         pgtype.Text      `json:"repostId"`
	ReplyRestriction string           `json:"replyRestriction"`
	IsPinned         bool             `json:"isPinned"`
	IsHiddenByAuthor bool             `json:"isHiddenByAuthor"`
	AuthorID         string           `json:"author_id"`
	AuthorName       pgtype.Text      `json:"author_name"`
	AuthorUsername   pgtype.Text      `json:"author_username"`
	AuthorLogo       pgtype.Text      `json:"author_logo"`
	AuthorCertified  bool             `json:"author_certified"`
	ViewerLiked      bool             `json:"viewer_liked"`
	ViewerReposted   bool             `json:"viewer_reposted"`
}

func (q *Queries) FindPostsByAuthor(ctx context.Context, arg FindPostsByAuthorParams) ([]FindPostsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, findPostsByAuthor,
		arg.ViewerID,
		arg.AuthorID,
		arg.SkipCount,
		arg.TakeCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPostsByAuthorRow{}
	for rows.Next() {
		var i FindPostsByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorId,
			&i.CreatedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.LikeCount,
			&i.RepostCount,
			&i.ReplyCount,
			&i.ParentId,
			&i.RootId,
			&i.RepostId,
			&i.ReplyRestriction,
			&i.IsPinned,
			&i.IsHiddenByAuthor,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogo,
			&i.AuthorCertified,
			&i.ViewerLiked,
			&i.ViewerReposted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTrending = `-- name: FindTrending :many
SELECT p.id,
       p.content,
       p."authorId",
       p."createdAt",
       p.tags,
       p."imageUrl",
       p."likeCount",
       p."repostCount",
       p."replyCount",
       p."parentId",
       p."rootId",
       p."repostId",
       p."replyRestriction",
       p."isPinned",
       p."isHiddenByAuthor",
       u.id::text       AS author_id,
       u.name           AS author_name,
       u.username       AS author_username,
       u."logoUrl"      AS author_logo,
       u."isCertified"  AS author_certified,
       (CASE WHEN l."userId" IS NOT NULL THEN true ELSE false END) AS viewer_liked,
       (CASE WHEN r.id IS NOT NULL THEN true ELSE false END)      AS viewer_reposted
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
LEFT JOIN "Like" l ON l."postId" = p.id AND l."userId" = $1
LEFT JOIN "Post" r ON r."repostId" = p.id AND r."authorId" = $1 AND r."deletedAt" IS NULL AND (r.content = '' OR r.content = ' ')
WHERE p."isDraft" = false
  AND p."deletedAt" IS NULL
  AND p.visibility = 'public'
  AND p."createdAt" >= now() - interval '7 days'
  AND u."isShadowbanned" = false
  AND u."isSuspended" = false
ORDER BY (p."likeCount" + p."repostCount" + p."replyCount") DESC, p."createdAt" DESC
LIMIT $3 OFFSET $2
`

type FindTrendingParams struct {
	ViewerID  pgtype.UUID `json:"viewer_id"`
	SkipCount int32       `json:"skip_count"`
	TakeCount int32       `json:"take_count"`
}

type FindTrendingRow struct {
	ID               string           `json:"id"`
	Content          string           `json:"content"`
	AuthorId         string           `json:"authorId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Tags             []string         `json:"tags"`
	ImageUrl         pgtype.Text      `json:"imageUrl"`
	LikeCount        int32            `json:"likeCount"`
	RepostCount      int32            `json:"repostCount"`
	ReplyCount       int32            `json:"replyCount"`
	ParentId         pgtype.Text      `json:"parentId"`
	RootId           pgtype.Text      `json:"rootId"`
	RepostId         pgtype.Text      `json:"repostId"`
	ReplyRestriction string           `json:"replyRestriction"`
	IsPinned         bool             `json:"isPinned"`
	IsHiddenByAuthor bool             `json:"isHiddenByAuthor"`
	AuthorID         string           `json:"author_id"`
	AuthorName       pgtype.Text      `json:"author_name"`
	AuthorUsername   pgtype.Text      `json:"author_username"`
	AuthorLogo       pgtype.Text      `json:"author_logo"`
	AuthorCertified  bool             `json:"author_certified"`
	ViewerLiked      bool             `json:"viewer_liked"`
	ViewerReposted   bool             `json:"viewer_reposted"`
}

func (q *Queries) FindTrending(ctx context.Context, arg FindTrendingParams) ([]FindTrendingRow, error) {
	rows, err := q.db.Query(ctx, findTrending, arg.ViewerID, arg.SkipCount, arg.TakeCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTrendingRow{}
	for rows.Next() {
		var i FindTrendingRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorId,
			&i.CreatedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.LikeCount,
			&i.RepostCount,
			&i.ReplyCount,
			&i.ParentId,
			&i.RootId,
			&i.RepostId,
			&i.ReplyRestriction,
			&i.IsPinned,
			&i.IsHiddenByAuthor,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogo,
			&i.AuthorCertified,
			&i.ViewerLiked,
			&i.ViewerReposted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowedPersonalPublicationOwnerIDs = `-- name: GetFollowedPersonalPublicationOwnerIDs :many
SELECT u.id::text AS user_id
FROM "Follows" f
JOIN "User" u ON u."publicationId" = f."publicationId"
WHERE f."readerId" = $1
  AND u."publicationId" IS NOT NULL
`

func (q *Queries) GetFollowedPersonalPublicationOwnerIDs(ctx context.Context, readerid pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getFollowedPersonalPublicationOwnerIDs, readerid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingStateByAuthorIDs = `-- name: GetFollowingStateByAuthorIDs :many
SELECT u.id::text AS author_id,
       (f.id IS NOT NULL)::boolean AS is_following
FROM "User" u
LEFT JOIN "Follows" f ON f."readerId" = $1
  AND f."publicationId" = u."publicationId"
WHERE u.id = ANY($2::uuid[])
  AND u."publicationId" IS NOT NULL
`

type GetFollowingStateByAuthorIDsParams struct {
	ViewerID pgtype.UUID   `json:"viewer_id"`
	Ids      []pgtype.UUID `json:"ids"`
}

type GetFollowingStateByAuthorIDsRow struct {
	AuthorID    string `json:"author_id"`
	IsFollowing bool   `json:"is_following"`
}

func (q *Queries) GetFollowingStateByAuthorIDs(ctx context.Context, arg GetFollowingStateByAuthorIDsParams) ([]GetFollowingStateByAuthorIDsRow, error) {
	rows, err := q.db.Query(ctx, getFollowingStateByAuthorIDs, arg.ViewerID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFollowingStateByAuthorIDsRow{}
	for rows.Next() {
		var i GetFollowingStateByAuthorIDsRow
		if err := rows.Scan(&i.AuthorID, &i.IsFollowing); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostThread = `-- name: GetPostThread :many
SELECT p.id,
       p.content,
       p."authorId",
       p."createdAt",
       p.tags,
       p."imageUrl",
       p."likeCount",
       p."repostCount",
       p."replyCount",
       p."parentId",
       p."rootId",
       p."repostId",
       p."replyRestriction",
       p."isPinned",
       p."isHiddenByAuthor",
       u.id::text      AS author_id,
       u.name          AS author_name,
       u.username      AS author_username,
       u."logoUrl"     AS author_logo,
       u."isCertified" AS author_certified,
       (CASE WHEN l."userId" IS NOT NULL THEN true ELSE false END) AS viewer_liked
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
LEFT JOIN "Like" l ON l."postId" = p.id AND l."userId" = $2
WHERE p.id = $1 OR p."rootId" = $1
ORDER BY p."createdAt" ASC
`

type GetPostThreadParams struct {
	ID       string      `json:"id"`
	ViewerID pgtype.UUID `json:"viewer_id"`
}

type GetPostThreadRow struct {
	ID               string           `json:"id"`
	Content          string           `json:"content"`
	AuthorId         string           `json:"authorId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Tags             []string         `json:"tags"`
	ImageUrl         pgtype.Text      `json:"imageUrl"`
	LikeCount        int32            `json:"likeCount"`
	RepostCount      int32            `json:"repostCount"`
	ReplyCount       int32            `json:"replyCount"`
	ParentId         pgtype.Text      `json:"parentId"`
	RootId           pgtype.Text      `json:"rootId"`
	RepostId         pgtype.Text      `json:"repostId"`
	ReplyRestriction string           `json:"replyRestriction"`
	IsPinned         bool             `json:"isPinned"`
	IsHiddenByAuthor bool             `json:"isHiddenByAuthor"`
	AuthorID         string           `json:"author_id"`
	AuthorName       pgtype.Text      `json:"author_name"`
	AuthorUsername   pgtype.Text      `json:"author_username"`
	AuthorLogo       pgtype.Text      `json:"author_logo"`
	AuthorCertified  bool             `json:"author_certified"`
	ViewerLiked      bool             `json:"viewer_liked"`
}

func (q *Queries) GetPostThread(ctx context.Context, arg GetPostThreadParams) ([]GetPostThreadRow, error) {
	rows, err := q.db.Query(ctx, getPostThread, arg.ID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostThreadRow{}
	for rows.Next() {
		var i GetPostThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorId,
			&i.CreatedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.LikeCount,
			&i.RepostCount,
			&i.ReplyCount,
			&i.ParentId,
			&i.RootId,
			&i.RepostId,
			&i.ReplyRestriction,
			&i.IsPinned,
			&i.IsHiddenByAuthor,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogo,
			&i.AuthorCertified,
			&i.ViewerLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsByIDs = `-- name: GetPostsByIDs :many
SELECT p.id,
       p.content,
       p."authorId",
       p."createdAt",
       p.tags,
       p."imageUrl",
       p."likeCount",
       p."repostCount",
       p."replyCount",
       p."parentId",
       p."rootId",
       p."repostId",
       p."replyRestriction",
       p."isPinned",
       p."isHiddenByAuthor",
       u.id::text      AS author_id,
       u.name          AS author_name,
       u.username      AS author_username,
       u."logoUrl"     AS author_logo,
       u."isCertified" AS author_certified,
       (CASE WHEN l."userId" IS NOT NULL THEN true ELSE false END) AS viewer_liked,
       (CASE WHEN r.id IS NOT NULL THEN true ELSE false END)      AS viewer_reposted
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
LEFT JOIN "Like" l ON l."postId" = p.id AND l."userId" = $1
LEFT JOIN "Post" r ON r."repostId" = p.id AND r."authorId" = $1 AND r."deletedAt" IS NULL AND (r.content = '' OR r.content = ' ')
WHERE p.id = ANY($2::text[])
  AND p."deletedAt" IS NULL
`

type GetPostsByIDsParams struct {
	ViewerID pgtype.UUID `json:"viewer_id"`
	Ids      []string    `json:"ids"`
}

type GetPostsByIDsRow struct {
	ID               string           `json:"id"`
	Content          string           `json:"content"`
	AuthorId         string           `json:"authorId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Tags             []string         `json:"tags"`
	ImageUrl         pgtype.Text      `json:"imageUrl"`
	LikeCount        int32            `json:"likeCount"`
	RepostCount      int32            `json:"repostCount"`
	ReplyCount       int32            `json:"replyCount"`
	ParentId         pgtype.Text      `json:"parentId"`
	RootId           pgtype.Text      `json:"rootId"`
	RepostId         pgtype.Text      `json:"repostId"`
	ReplyRestriction string           `json:"replyRestriction"`
	IsPinned         bool             `json:"isPinned"`
	IsHiddenByAuthor bool             `json:"isHiddenByAuthor"`
	AuthorID         string           `json:"author_id"`
	AuthorName       pgtype.Text      `json:"author_name"`
	AuthorUsername   pgtype.Text      `json:"author_username"`
	AuthorLogo       pgtype.Text      `json:"author_logo"`
	AuthorCertified  bool             `json:"author_certified"`
	ViewerLiked      bool             `json:"viewer_liked"`
	ViewerReposted   bool             `json:"viewer_reposted"`
}

func (q *Queries) GetPostsByIDs(ctx context.Context, arg GetPostsByIDsParams) ([]GetPostsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getPostsByIDs, arg.ViewerID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsByIDsRow{}
	for rows.Next() {
		var i GetPostsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorId,
			&i.CreatedAt,
			&i.Tags,
			&i.ImageUrl,
			&i.LikeCount,
			&i.RepostCount,
			&i.ReplyCount,
			&i.ParentId,
			&i.RootId,
			&i.RepostId,
			&i.ReplyRestriction,
			&i.IsPinned,
			&i.IsHiddenByAuthor,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogo,
			&i.AuthorCertified,
			&i.ViewerLiked,
			&i.ViewerReposted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepliesForThought = `-- name: GetRepliesForThought :many
SELECT id,
       content,
       "authorId",
       "createdAt",
       "likeCount",
       "repostCount",
       "replyCount",
       "parentId",
       "rootId",
       "repostId"
FROM "Post"
WHERE "parentId" = $1
  AND "deletedAt" IS NULL
  AND "isDraft" = false
ORDER BY "createdAt" ASC
LIMIT $2 OFFSET $3
`

type GetRepliesForThoughtParams struct {
	ParentId pgtype.Text `json:"parentId"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GetRepliesForThoughtRow struct {
	ID          string           `json:"id"`
	Content     string           `json:"content"`
	AuthorId    string           `json:"authorId"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	LikeCount   int32            `json:"likeCount"`
	RepostCount int32            `json:"repostCount"`
	ReplyCount  int32            `json:"replyCount"`
	ParentId    pgtype.Text      `json:"parentId"`
	RootId      pgtype.Text      `json:"rootId"`
	RepostId    pgtype.Text      `json:"repostId"`
}

func (q *Queries) GetRepliesForThought(ctx context.Context, arg GetRepliesForThoughtParams) ([]GetRepliesForThoughtRow, error) {
	rows, err := q.db.Query(ctx, getRepliesForThought, arg.ParentId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRepliesForThoughtRow{}
	for rows.Next() {
		var i GetRepliesForThoughtRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorId,
			&i.CreatedAt,
			&i.LikeCount,
			&i.RepostCount,
			&i.ReplyCount,
			&i.ParentId,
			&i.RootId,
			&i.RepostId,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplyIDsForThought = `-- name: GetReplyIDsForThought :many
SELECT id
FROM "Post"
WHERE "parentId" = $1
  AND "deletedAt" IS NULL
  AND "isDraft" = false
ORDER BY "createdAt" ASC
`

func (q *Queries) GetReplyIDsForThought(ctx context.Context, parentid pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, getReplyIDsForThought, parentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEmbeddingText = `-- name: GetUserEmbeddingText :one
SELECT COALESCE("embedding"::text, '')::text AS embedding_text FROM "User" WHERE id = $1
`

func (q *Queries) GetUserEmbeddingText(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmbeddingText, id)
	var embedding_text string
	err := row.Scan(&embedding_text)
	return embedding_text, err
}

const getMutedWords = `-- name: GetMutedWords :many
SELECT word FROM "MutedWord" WHERE "userId" = $1
`

func (q *Queries) GetMutedWords(ctx context.Context, userid pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getMutedWords, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		items = append(items, word)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUserReadingSessions = `-- name: CountUserReadingSessions :one
SELECT COUNT(*)::int AS count FROM "ReadingSession" WHERE "userId" = $1
`

func (q *Queries) CountUserReadingSessions(ctx context.Context, userid pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUserReadingSessions, userid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const findPersonalizedPosts = `-- name: FindPersonalizedPosts :many
SELECT p.id,
       p.content,
       p."authorId",
       p."createdAt",
       p."likeCount",
       p."repostCount",
       p."replyCount",
       p."quotedArticleId",
       (1 - (p."embedding" <=> $1::vector))::float8 AS sim_score,
       EXP(-EXTRACT(EPOCH FROM (NOW() - p."createdAt"))/86400)::float8 AS freshness_score
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
WHERE p."parentId" IS NULL
  AND p."repostId" IS NULL
  AND p."deletedAt" IS NULL
  AND p."isDraft" = false
  AND p."isHiddenByAuthor" = false
  AND p."embedding" IS NOT NULL
  AND u."isShadowbanned" = false
  AND u."isSuspended" = false
ORDER BY p."embedding" <=> $1::vector
LIMIT $2 OFFSET $3
`

type FindPersonalizedPostsParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	Limit     int32           `json:"limit"`
	Offset    int32           `json:"offset"`
}

type FindPersonalizedPostsRow struct {
	ID               string           `json:"id"`
	Content          string           `json:"content"`
	AuthorId         string           `json:"authorId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	LikeCount        int32            `json:"likeCount"`
	RepostCount      int32            `json:"repostCount"`
	ReplyCount       int32            `json:"replyCount"`
	QuotedArticleId  pgtype.Text      `json:"quotedArticleId"`
	SimScore         float64          `json:"sim_score"`
	FreshnessScore   float64          `json:"freshness_score"`
}

func (q *Queries) FindPersonalizedPosts(ctx context.Context, arg FindPersonalizedPostsParams) ([]FindPersonalizedPostsRow, error) {
	rows, err := q.db.Query(ctx, findPersonalizedPosts, arg.Embedding, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPersonalizedPostsRow{}
	for rows.Next() {
		var i FindPersonalizedPostsRow
		if err := rows.Scan(&i.ID, &i.Content, &i.AuthorId, &i.CreatedAt, &i.LikeCount, &i.RepostCount, &i.ReplyCount, &i.QuotedArticleId, &i.SimScore, &i.FreshnessScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
