// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legal_lifecycle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimLegalReviewReminders = `-- name: ClaimLegalReviewReminders :many
WITH candidates AS (
  SELECT id FROM legal_review_reminder
  WHERE status = 'QUEUED' AND available_at <= now()
  ORDER BY created_at ASC
  FOR UPDATE SKIP LOCKED
  LIMIT $1
)
UPDATE legal_review_reminder r
SET status = 'PROCESSING', attempts = r.attempts + 1, updated_at = now()
FROM candidates c
WHERE r.id = c.id
RETURNING r.id, r.review_id, r.user_id, r.email, r.stage, r.attempts
`

type ClaimLegalReviewRemindersRow struct {
	ID       string      `json:"id"`
	ReviewID string      `json:"review_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Email    string      `json:"email"`
	Stage    string      `json:"stage"`
	Attempts int32       `json:"attempts"`
}

func (q *Queries) ClaimLegalReviewReminders(ctx context.Context, batchSize int32) ([]ClaimLegalReviewRemindersRow, error) {
	rows, err := q.db.Query(ctx, claimLegalReviewReminders, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimLegalReviewRemindersRow{}
	for rows.Next() {
		var i ClaimLegalReviewRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Email,
			&i.Stage,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeLegalReviewsForVersion = `-- name: CompleteLegalReviewsForVersion :exec
UPDATE legal_review
SET status = 'PUBLISHED', completed_at = now(), updated_at = now()
WHERE draft_version_id = $1 AND status = 'DRAFTED'
`

// Publier le brouillon d'une revue clôt la revue : la boucle est bouclée sans
// qu'un humain ait à cocher quoi que ce soit en plus.
func (q *Queries) CompleteLegalReviewsForVersion(ctx context.Context, versionID pgtype.Text) error {
	_, err := q.db.Exec(ctx, completeLegalReviewsForVersion, versionID)
	return err
}

const countDueScheduledLegalVersions = `-- name: CountDueScheduledLegalVersions :one
SELECT count(*) FROM legal_document_version
WHERE status = 'DRAFT' AND scheduled_at IS NOT NULL AND scheduled_at <= now()
`

func (q *Queries) CountDueScheduledLegalVersions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDueScheduledLegalVersions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dismissLegalReview = `-- name: DismissLegalReview :one
UPDATE legal_review
SET status = 'DISMISSED', completed_at = now(), notes = COALESCE($1, notes), updated_at = now()
WHERE id = $2 AND status IN ('OPEN', 'DRAFTED')
RETURNING id, document_id, rule_key, due_at, status, draft_version_id, notes, opened_at, completed_at, created_at, updated_at
`

type DismissLegalReviewParams struct {
	Notes pgtype.Text `json:"notes"`
	ID    string      `json:"id"`
}

func (q *Queries) DismissLegalReview(ctx context.Context, arg DismissLegalReviewParams) (LegalReview, error) {
	row := q.db.QueryRow(ctx, dismissLegalReview, arg.Notes, arg.ID)
	var i LegalReview
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RuleKey,
		&i.DueAt,
		&i.Status,
		&i.DraftVersionID,
		&i.Notes,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestLegalConsentExport = `-- name: GetLatestLegalConsentExport :one
SELECT id, seq, scope, subject, reason, filters, requested_by, requested_by_email, documents_count, acceptances_count, cookie_records_count, content_sha256, previous_chain, chain_sha256, signature, key_id, algorithm, generated_at FROM legal_consent_export ORDER BY seq DESC LIMIT 1
`

func (q *Queries) GetLatestLegalConsentExport(ctx context.Context) (LegalConsentExport, error) {
	row := q.db.QueryRow(ctx, getLatestLegalConsentExport)
	var i LegalConsentExport
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Scope,
		&i.Subject,
		&i.Reason,
		&i.Filters,
		&i.RequestedBy,
		&i.RequestedByEmail,
		&i.DocumentsCount,
		&i.AcceptancesCount,
		&i.CookieRecordsCount,
		&i.ContentSha256,
		&i.PreviousChain,
		&i.ChainSha256,
		&i.Signature,
		&i.KeyID,
		&i.Algorithm,
		&i.GeneratedAt,
	)
	return i, err
}

const getLegalActorEmail = `-- name: GetLegalActorEmail :one

SELECT COALESCE(email, '')::text FROM "User" WHERE id = $1::uuid
`

// ─── Rappels aux superadmins ─────────────────────────────────────────
// L'email de l'auteur d'un export : le registre doit dire QUI a produit la
// pièce, pas seulement quel compte technique.
func (q *Queries) GetLegalActorEmail(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLegalActorEmail, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getLegalDocumentBySlugAdmin = `-- name: GetLegalDocumentBySlugAdmin :one
SELECT id, slug, category, audience, requires_acceptance, is_active, sort_order, created_at, updated_at FROM legal_document WHERE slug = $1
`

func (q *Queries) GetLegalDocumentBySlugAdmin(ctx context.Context, slug string) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, getLegalDocumentBySlugAdmin, slug)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Audience,
		&i.RequiresAcceptance,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegalReviewReminderContext = `-- name: GetLegalReviewReminderContext :one
SELECT rr.id, rr.stage, rr.email, rr.attempts,
       r.id AS review_id, r.due_at, r.status AS review_status, r.notes,
       d.slug AS document_slug, d.category, d.audience,
       -- Titre lisible pour l'email : le libellé publié, à défaut le slug.
       COALESCE((SELECT v2.title FROM legal_document_version v2
                  WHERE v2.document_id = d.id AND v2.status = 'PUBLISHED'
                  ORDER BY (v2.locale = 'fr') DESC, v2.published_at DESC NULLS LAST
                  LIMIT 1), d.slug)::text AS document_title,
       COALESCE(v.version, '')::text AS draft_version,
       v.scheduled_at AS draft_scheduled_at,
       COALESCE(u.name, u.username, '')::text AS recipient_name
FROM legal_review_reminder rr
JOIN legal_review r ON r.id = rr.review_id
JOIN legal_document d ON d.id = r.document_id
LEFT JOIN legal_document_version v ON v.id = r.draft_version_id
LEFT JOIN "User" u ON u.id = rr.user_id
WHERE rr.id = $1
`

type GetLegalReviewReminderContextRow struct {
	ID               string           `json:"id"`
	Stage            string           `json:"stage"`
	Email            string           `json:"email"`
	Attempts         int32            `json:"attempts"`
	ReviewID         string           `json:"review_id"`
	DueAt            pgtype.Timestamp `json:"due_at"`
	ReviewStatus     string           `json:"review_status"`
	Notes            pgtype.Text      `json:"notes"`
	DocumentSlug     string           `json:"document_slug"`
	Category         string           `json:"category"`
	Audience         string           `json:"audience"`
	DocumentTitle    string           `json:"document_title"`
	DraftVersion     string           `json:"draft_version"`
	DraftScheduledAt pgtype.Timestamp `json:"draft_scheduled_at"`
	RecipientName    string           `json:"recipient_name"`
}

func (q *Queries) GetLegalReviewReminderContext(ctx context.Context, id string) (GetLegalReviewReminderContextRow, error) {
	row := q.db.QueryRow(ctx, getLegalReviewReminderContext, id)
	var i GetLegalReviewReminderContextRow
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.Email,
		&i.Attempts,
		&i.ReviewID,
		&i.DueAt,
		&i.ReviewStatus,
		&i.Notes,
		&i.DocumentSlug,
		&i.Category,
		&i.Audience,
		&i.DocumentTitle,
		&i.DraftVersion,
		&i.DraftScheduledAt,
		&i.RecipientName,
	)
	return i, err
}

const getReferencePublishedVersion = `-- name: GetReferencePublishedVersion :one
SELECT v.id, v.document_id, v.locale, v.version, v.title, v.summary, v.body, v.status, v.changelog, v.effective_at, v.published_at, v.archived_at, v.scheduled_at, v.created_by, v.created_at, v.updated_at FROM legal_document_version v
WHERE v.document_id = $1 AND v.status = 'PUBLISHED'
ORDER BY (v.locale = 'fr') DESC, v.published_at DESC NULLS LAST
LIMIT 1
`

// Version publiée de référence d'un document (FR en priorité : c'est le texte
// qui fait foi). Sert de base au brouillon de revue.
func (q *Queries) GetReferencePublishedVersion(ctx context.Context, documentID string) (LegalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, getReferencePublishedVersion, documentID)
	var i LegalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Status,
		&i.Changelog,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.ScheduledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLegalConsentExport = `-- name: InsertLegalConsentExport :one
INSERT INTO legal_consent_export (
    scope, subject, reason, filters, requested_by, requested_by_email,
    documents_count, acceptances_count, cookie_records_count,
    content_sha256, previous_chain, chain_sha256, signature, key_id, algorithm
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::uuid,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING id, seq, scope, subject, reason, filters, requested_by, requested_by_email, documents_count, acceptances_count, cookie_records_count, content_sha256, previous_chain, chain_sha256, signature, key_id, algorithm, generated_at
`

type InsertLegalConsentExportParams struct {
	Scope              string      `json:"scope"`
	Subject            pgtype.Text `json:"subject"`
	Reason             pgtype.Text `json:"reason"`
	Filters            []byte      `json:"filters"`
	RequestedBy        pgtype.UUID `json:"requested_by"`
	RequestedByEmail   pgtype.Text `json:"requested_by_email"`
	DocumentsCount     int32       `json:"documents_count"`
	AcceptancesCount   int32       `json:"acceptances_count"`
	CookieRecordsCount int32       `json:"cookie_records_count"`
	ContentSha256      string      `json:"content_sha256"`
	PreviousChain      pgtype.Text `json:"previous_chain"`
	ChainSha256        string      `json:"chain_sha256"`
	Signature          string      `json:"signature"`
	KeyID              string      `json:"key_id"`
	Algorithm          string      `json:"algorithm"`
}

func (q *Queries) InsertLegalConsentExport(ctx context.Context, arg InsertLegalConsentExportParams) (LegalConsentExport, error) {
	row := q.db.QueryRow(ctx, insertLegalConsentExport,
		arg.Scope,
		arg.Subject,
		arg.Reason,
		arg.Filters,
		arg.RequestedBy,
		arg.RequestedByEmail,
		arg.DocumentsCount,
		arg.AcceptancesCount,
		arg.CookieRecordsCount,
		arg.ContentSha256,
		arg.PreviousChain,
		arg.ChainSha256,
		arg.Signature,
		arg.KeyID,
		arg.Algorithm,
	)
	var i LegalConsentExport
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Scope,
		&i.Subject,
		&i.Reason,
		&i.Filters,
		&i.RequestedBy,
		&i.RequestedByEmail,
		&i.DocumentsCount,
		&i.AcceptancesCount,
		&i.CookieRecordsCount,
		&i.ContentSha256,
		&i.PreviousChain,
		&i.ChainSha256,
		&i.Signature,
		&i.KeyID,
		&i.Algorithm,
		&i.GeneratedAt,
	)
	return i, err
}

const insertLegalReviewReminder = `-- name: InsertLegalReviewReminder :execrows
INSERT INTO legal_review_reminder (review_id, user_id, email, stage)
VALUES ($1, $2::uuid, $3, $4)
ON CONFLICT (review_id, user_id, stage) DO NOTHING
`

type InsertLegalReviewReminderParams struct {
	ReviewID string      `json:"review_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Email    string      `json:"email"`
	Stage    string      `json:"stage"`
}

// Le nombre de lignes réellement insérées compte : un rappel déjà émis n'est
// pas un rappel émis, et le rapport du cycle doit le dire honnêtement.
func (q *Queries) InsertLegalReviewReminder(ctx context.Context, arg InsertLegalReviewReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLegalReviewReminder,
		arg.ReviewID,
		arg.UserID,
		arg.Email,
		arg.Stage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCookieConsentForExport = `-- name: ListCookieConsentForExport :many
SELECT c.id, c.seq, c.consent_id, c.user_id, c.session_id, c.locale, c.policy_version,
       c.categories, c.source, c.country, c.ip, c.user_agent, c.created_at
FROM cookie_consent_record c
WHERE ($1::text IS NULL OR c.consent_id = $1::text)
  AND ($2::timestamp IS NULL OR c.created_at >= $2::timestamp)
  AND ($3::timestamp IS NULL OR c.created_at <= $3::timestamp)
ORDER BY c.seq ASC
LIMIT $4
`

type ListCookieConsentForExportParams struct {
	ConsentID  pgtype.Text      `json:"consent_id"`
	FromAt     pgtype.Timestamp `json:"from_at"`
	ToAt       pgtype.Timestamp `json:"to_at"`
	LimitCount int32            `json:"limit_count"`
}

// Journal des choix de traceurs. Le consent_id est un identifiant aléatoire de
// navigateur, pas une personne : il permet de reconstituer une suite de choix.
func (q *Queries) ListCookieConsentForExport(ctx context.Context, arg ListCookieConsentForExportParams) ([]CookieConsentRecord, error) {
	rows, err := q.db.Query(ctx, listCookieConsentForExport,
		arg.ConsentID,
		arg.FromAt,
		arg.ToAt,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CookieConsentRecord{}
	for rows.Next() {
		var i CookieConsentRecord
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ConsentID,
			&i.UserID,
			&i.SessionID,
			&i.Locale,
			&i.PolicyVersion,
			&i.Categories,
			&i.Source,
			&i.Country,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalAcceptancesForExport = `-- name: ListLegalAcceptancesForExport :many
SELECT a.id, a.user_id, a.document_id, d.slug AS document_slug, a.version_id, a.version,
       a.locale, a.accepted_at, a.source, a.method, a.ip, a.user_agent,
       COALESCE(u.email, '')::text AS user_email
FROM legal_acceptance a
JOIN legal_document d ON d.id = a.document_id
LEFT JOIN "User" u ON u.id = a.user_id
WHERE ($1::text IS NULL OR d.slug = $1::text)
  AND ($2::uuid IS NULL OR a.user_id = $2::uuid)
  AND ($3::timestamp IS NULL OR a.accepted_at >= $3::timestamp)
  AND ($4::timestamp IS NULL OR a.accepted_at <= $4::timestamp)
ORDER BY a.accepted_at ASC
LIMIT $5
`

type ListLegalAcceptancesForExportParams struct {
	Slug       pgtype.Text      `json:"slug"`
	UserID     pgtype.UUID      `json:"user_id"`
	FromAt     pgtype.Timestamp `json:"from_at"`
	ToAt       pgtype.Timestamp `json:"to_at"`
	LimitCount int32            `json:"limit_count"`
}

type ListLegalAcceptancesForExportRow struct {
	ID           string           `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	DocumentID   string           `json:"document_id"`
	DocumentSlug string           `json:"document_slug"`
	VersionID    string           `json:"version_id"`
	Version      string           `json:"version"`
	Locale       string           `json:"locale"`
	AcceptedAt   pgtype.Timestamp `json:"accepted_at"`
	Source       string           `json:"source"`
	Method       string           `json:"method"`
	Ip           pgtype.Text      `json:"ip"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	UserEmail    string           `json:"user_email"`
}

// Preuves de consentement. L'IP et l'agent utilisateur sont inclus : c'est
// précisément ce qu'une autorité de contrôle demande pour établir qu'une
// acceptation vient d'un vrai parcours, et l'export est nominatif par nature.
func (q *Queries) ListLegalAcceptancesForExport(ctx context.Context, arg ListLegalAcceptancesForExportParams) ([]ListLegalAcceptancesForExportRow, error) {
	rows, err := q.db.Query(ctx, listLegalAcceptancesForExport,
		arg.Slug,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalAcceptancesForExportRow{}
	for rows.Next() {
		var i ListLegalAcceptancesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentID,
			&i.DocumentSlug,
			&i.VersionID,
			&i.Version,
			&i.Locale,
			&i.AcceptedAt,
			&i.Source,
			&i.Method,
			&i.Ip,
			&i.UserAgent,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalConsentExports = `-- name: ListLegalConsentExports :many
SELECT id, seq, scope, subject, reason, filters, requested_by, requested_by_email, documents_count, acceptances_count, cookie_records_count, content_sha256, previous_chain, chain_sha256, signature, key_id, algorithm, generated_at FROM legal_consent_export ORDER BY seq DESC LIMIT $1
`

func (q *Queries) ListLegalConsentExports(ctx context.Context, limitCount int32) ([]LegalConsentExport, error) {
	rows, err := q.db.Query(ctx, listLegalConsentExports, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalConsentExport{}
	for rows.Next() {
		var i LegalConsentExport
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Scope,
			&i.Subject,
			&i.Reason,
			&i.Filters,
			&i.RequestedBy,
			&i.RequestedByEmail,
			&i.DocumentsCount,
			&i.AcceptancesCount,
			&i.CookieRecordsCount,
			&i.ContentSha256,
			&i.PreviousChain,
			&i.ChainSha256,
			&i.Signature,
			&i.KeyID,
			&i.Algorithm,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalConsentExportsForVerify = `-- name: ListLegalConsentExportsForVerify :many
SELECT id, seq, scope, subject, reason, filters, requested_by, requested_by_email, documents_count, acceptances_count, cookie_records_count, content_sha256, previous_chain, chain_sha256, signature, key_id, algorithm, generated_at FROM legal_consent_export ORDER BY seq ASC
`

// Chaîne complète, du plus ancien au plus récent : c'est l'ordre dans lequel
// les signatures doivent être recomputées pour vérifier qu'aucun maillon n'a
// été retiré ni réécrit.
func (q *Queries) ListLegalConsentExportsForVerify(ctx context.Context) ([]LegalConsentExport, error) {
	rows, err := q.db.Query(ctx, listLegalConsentExportsForVerify)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalConsentExport{}
	for rows.Next() {
		var i LegalConsentExport
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Scope,
			&i.Subject,
			&i.Reason,
			&i.Filters,
			&i.RequestedBy,
			&i.RequestedByEmail,
			&i.DocumentsCount,
			&i.AcceptancesCount,
			&i.CookieRecordsCount,
			&i.ContentSha256,
			&i.PreviousChain,
			&i.ChainSha256,
			&i.Signature,
			&i.KeyID,
			&i.Algorithm,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalReviewsAdmin = `-- name: ListLegalReviewsAdmin :many
SELECT r.id, r.document_id, d.slug AS document_slug, d.audience, r.rule_key, r.due_at,
       r.status, r.notes, r.opened_at, r.completed_at,
       COALESCE(v.version, '')::text AS draft_version,
       v.scheduled_at AS draft_scheduled_at,
       (SELECT count(*) FROM legal_review_reminder rr WHERE rr.review_id = r.id) AS reminders,
       (SELECT count(*) FROM legal_review_reminder rr WHERE rr.review_id = r.id AND rr.status = 'SENT') AS reminders_sent
FROM legal_review r
JOIN legal_document d ON d.id = r.document_id
LEFT JOIN legal_document_version v ON v.id = r.draft_version_id
ORDER BY r.due_at ASC
LIMIT $1
`

type ListLegalReviewsAdminRow struct {
	ID               string           `json:"id"`
	DocumentID       string           `json:"document_id"`
	DocumentSlug     string           `json:"document_slug"`
	Audience         string           `json:"audience"`
	RuleKey          string           `json:"rule_key"`
	DueAt            pgtype.Timestamp `json:"due_at"`
	Status           string           `json:"status"`
	Notes            pgtype.Text      `json:"notes"`
	OpenedAt         pgtype.Timestamp `json:"opened_at"`
	CompletedAt      pgtype.Timestamp `json:"completed_at"`
	DraftVersion     string           `json:"draft_version"`
	DraftScheduledAt pgtype.Timestamp `json:"draft_scheduled_at"`
	Reminders        int64            `json:"reminders"`
	RemindersSent    int64            `json:"reminders_sent"`
}

func (q *Queries) ListLegalReviewsAdmin(ctx context.Context, limitCount int32) ([]ListLegalReviewsAdminRow, error) {
	rows, err := q.db.Query(ctx, listLegalReviewsAdmin, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalReviewsAdminRow{}
	for rows.Next() {
		var i ListLegalReviewsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.DocumentSlug,
			&i.Audience,
			&i.RuleKey,
			&i.DueAt,
			&i.Status,
			&i.Notes,
			&i.OpenedAt,
			&i.CompletedAt,
			&i.DraftVersion,
			&i.DraftScheduledAt,
			&i.Reminders,
			&i.RemindersSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalSuperadmins = `-- name: ListLegalSuperadmins :many
SELECT id, COALESCE(email, '')::text AS email, COALESCE(name, username, '')::text AS name
FROM "User"
WHERE role = 'superadmin' AND "isSuspended" = false AND email IS NOT NULL AND email <> ''
ORDER BY email ASC
`

type ListLegalSuperadminsRow struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) ListLegalSuperadmins(ctx context.Context) ([]ListLegalSuperadminsRow, error) {
	rows, err := q.db.Query(ctx, listLegalSuperadmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalSuperadminsRow{}
	for rows.Next() {
		var i ListLegalSuperadminsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalVersionsForExport = `-- name: ListLegalVersionsForExport :many


SELECT v.id, v.document_id, d.slug AS document_slug, d.category AS document_category,
       d.audience, d.requires_acceptance,
       v.locale, v.version, v.title, v.summary, v.body, v.status, v.changelog,
       v.effective_at, v.published_at, v.archived_at, v.scheduled_at, v.created_at,
       encode(sha256(convert_to(COALESCE(v.body, ''), 'UTF8')), 'hex')::text AS body_sha256,
       length(COALESCE(v.body, '')) AS body_length
FROM legal_document_version v
JOIN legal_document d ON d.id = v.document_id
WHERE ($1::text IS NULL OR d.slug = $1::text)
ORDER BY d.slug ASC, v.locale ASC, v.created_at ASC
`

type ListLegalVersionsForExportRow struct {
	ID                 string           `json:"id"`
	DocumentID         string           `json:"document_id"`
	DocumentSlug       string           `json:"document_slug"`
	DocumentCategory   string           `json:"document_category"`
	Audience           string           `json:"audience"`
	RequiresAcceptance bool             `json:"requires_acceptance"`
	Locale             string           `json:"locale"`
	Version            string           `json:"version"`
	Title              string           `json:"title"`
	Summary            string           `json:"summary"`
	Body               string           `json:"body"`
	Status             string           `json:"status"`
	Changelog          pgtype.Text      `json:"changelog"`
	EffectiveAt        pgtype.Timestamp `json:"effective_at"`
	PublishedAt        pgtype.Timestamp `json:"published_at"`
	ArchivedAt         pgtype.Timestamp `json:"archived_at"`
	ScheduledAt        pgtype.Timestamp `json:"scheduled_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	BodySha256         string           `json:"body_sha256"`
	BodyLength         float64          `json:"body_length"`
}

// ═══════════════════════════════════════════════════════════════════
// ⚖️ Legal — cycle de vie (revues, publication planifiée, rappels)
//
//	et registre des exports signés du consentement
//
// ═══════════════════════════════════════════════════════════════════
// ─── Exports signés du registre du consentement ──────────────────────
// Le texte accepté fait partie de la preuve : on exporte la version complète
// (corps inclus) et son empreinte SHA-256, pour qu'un vérificateur puisse
// contrôler l'intégrité sans dépendre de notre base.
func (q *Queries) ListLegalVersionsForExport(ctx context.Context, slug pgtype.Text) ([]ListLegalVersionsForExportRow, error) {
	rows, err := q.db.Query(ctx, listLegalVersionsForExport, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalVersionsForExportRow{}
	for rows.Next() {
		var i ListLegalVersionsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.DocumentSlug,
			&i.DocumentCategory,
			&i.Audience,
			&i.RequiresAcceptance,
			&i.Locale,
			&i.Version,
			&i.Title,
			&i.Summary,
			&i.Body,
			&i.Status,
			&i.Changelog,
			&i.EffectiveAt,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.BodySha256,
			&i.BodyLength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLegalReviews = `-- name: ListOpenLegalReviews :many
SELECT r.id, r.document_id, r.rule_key, r.due_at, r.status, r.draft_version_id,
       r.opened_at, r.completed_at,
       d.slug AS document_slug, d.audience, d.category, d.requires_acceptance,
       COALESCE(v.version, '')::text AS draft_version,
       v.scheduled_at AS draft_scheduled_at
FROM legal_review r
JOIN legal_document d ON d.id = r.document_id
LEFT JOIN legal_document_version v ON v.id = r.draft_version_id
WHERE r.status IN ('OPEN', 'DRAFTED')
ORDER BY r.due_at ASC
`

type ListOpenLegalReviewsRow struct {
	ID                 string           `json:"id"`
	DocumentID         string           `json:"document_id"`
	RuleKey            string           `json:"rule_key"`
	DueAt              pgtype.Timestamp `json:"due_at"`
	Status             string           `json:"status"`
	DraftVersionID     pgtype.Text      `json:"draft_version_id"`
	OpenedAt           pgtype.Timestamp `json:"opened_at"`
	CompletedAt        pgtype.Timestamp `json:"completed_at"`
	DocumentSlug       string           `json:"document_slug"`
	Audience           string           `json:"audience"`
	Category           string           `json:"category"`
	RequiresAcceptance bool             `json:"requires_acceptance"`
	DraftVersion       string           `json:"draft_version"`
	DraftScheduledAt   pgtype.Timestamp `json:"draft_scheduled_at"`
}

func (q *Queries) ListOpenLegalReviews(ctx context.Context) ([]ListOpenLegalReviewsRow, error) {
	rows, err := q.db.Query(ctx, listOpenLegalReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenLegalReviewsRow{}
	for rows.Next() {
		var i ListOpenLegalReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.RuleKey,
			&i.DueAt,
			&i.Status,
			&i.DraftVersionID,
			&i.OpenedAt,
			&i.CompletedAt,
			&i.DocumentSlug,
			&i.Audience,
			&i.Category,
			&i.RequiresAcceptance,
			&i.DraftVersion,
			&i.DraftScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueScheduledLegalVersion = `-- name: LockDueScheduledLegalVersion :one
SELECT v.id, v.document_id, v.locale, v.version, v.title, v.changelog, v.scheduled_at
FROM legal_document_version v
WHERE v.status = 'DRAFT' AND v.scheduled_at IS NOT NULL AND v.scheduled_at <= now()
ORDER BY v.scheduled_at ASC
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type LockDueScheduledLegalVersionRow struct {
	ID          string           `json:"id"`
	DocumentID  string           `json:"document_id"`
	Locale      string           `json:"locale"`
	Version     string           `json:"version"`
	Title       string           `json:"title"`
	Changelog   pgtype.Text      `json:"changelog"`
	ScheduledAt pgtype.Timestamp `json:"scheduled_at"`
}

// Réclame UN brouillon arrivé à échéance, verrouillé jusqu'à la fin de la
// transaction : la publication et le déverrouillage sont donc atomiques, et
// deux workers ne peuvent pas publier la même version.
func (q *Queries) LockDueScheduledLegalVersion(ctx context.Context) (LockDueScheduledLegalVersionRow, error) {
	row := q.db.QueryRow(ctx, lockDueScheduledLegalVersion)
	var i LockDueScheduledLegalVersionRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Changelog,
		&i.ScheduledAt,
	)
	return i, err
}

const markLegalReviewReminder = `-- name: MarkLegalReviewReminder :exec
UPDATE legal_review_reminder
SET status = $1,
    provider = $2,
    last_error = $3,
    sent_at = $4,
    available_at = COALESCE($5, available_at),
    updated_at = now()
WHERE id = $6
`

type MarkLegalReviewReminderParams struct {
	Status      string           `json:"status"`
	Provider    pgtype.Text      `json:"provider"`
	LastError   pgtype.Text      `json:"last_error"`
	SentAt      pgtype.Timestamp `json:"sent_at"`
	AvailableAt pgtype.Timestamp `json:"available_at"`
	ID          string           `json:"id"`
}

func (q *Queries) MarkLegalReviewReminder(ctx context.Context, arg MarkLegalReviewReminderParams) error {
	_, err := q.db.Exec(ctx, markLegalReviewReminder,
		arg.Status,
		arg.Provider,
		arg.LastError,
		arg.SentAt,
		arg.AvailableAt,
		arg.ID,
	)
	return err
}

const scheduleLegalDocumentVersion = `-- name: ScheduleLegalDocumentVersion :one

UPDATE legal_document_version
SET scheduled_at = $1,
    updated_at = now()
WHERE id = $2 AND status = 'DRAFT'
RETURNING id, document_id, locale, version, title, summary, body, status, changelog, effective_at, published_at, archived_at, scheduled_at, created_by, created_at, updated_at
`

type ScheduleLegalDocumentVersionParams struct {
	ScheduledAt pgtype.Timestamp `json:"scheduled_at"`
	ID          string           `json:"id"`
}

// ─── Publication planifiée ───────────────────────────────────────────
// Programme (ou déprogramme, si la date est nulle) la publication automatique
// d'un brouillon. Refusé sur une version déjà publiée.
func (q *Queries) ScheduleLegalDocumentVersion(ctx context.Context, arg ScheduleLegalDocumentVersionParams) (LegalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, scheduleLegalDocumentVersion, arg.ScheduledAt, arg.ID)
	var i LegalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Status,
		&i.Changelog,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.ScheduledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLegalConsentExportSignature = `-- name: SetLegalConsentExportSignature :one
UPDATE legal_consent_export
SET content_sha256 = $1,
    previous_chain = $2,
    chain_sha256   = $3,
    signature      = $4,
    key_id         = $5,
    algorithm      = $6
WHERE id = $7
RETURNING id, seq, scope, subject, reason, filters, requested_by, requested_by_email, documents_count, acceptances_count, cookie_records_count, content_sha256, previous_chain, chain_sha256, signature, key_id, algorithm, generated_at
`

type SetLegalConsentExportSignatureParams struct {
	ContentSha256 string      `json:"content_sha256"`
	PreviousChain pgtype.Text `json:"previous_chain"`
	ChainSha256   string      `json:"chain_sha256"`
	Signature     string      `json:"signature"`
	KeyID         string      `json:"key_id"`
	Algorithm     string      `json:"algorithm"`
	ID            string      `json:"id"`
}

// L'identifiant et le numéro de séquence ne sont connus qu'après insertion :
// on écrit donc d'abord la ligne (dans la transaction), puis on y scelle
// l'empreinte du contenu, le maillon précédent et la signature. Tant que la
// transaction n'est pas validée, personne ne voit d'export non signé.
func (q *Queries) SetLegalConsentExportSignature(ctx context.Context, arg SetLegalConsentExportSignatureParams) (LegalConsentExport, error) {
	row := q.db.QueryRow(ctx, setLegalConsentExportSignature,
		arg.ContentSha256,
		arg.PreviousChain,
		arg.ChainSha256,
		arg.Signature,
		arg.KeyID,
		arg.Algorithm,
		arg.ID,
	)
	var i LegalConsentExport
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Scope,
		&i.Subject,
		&i.Reason,
		&i.Filters,
		&i.RequestedBy,
		&i.RequestedByEmail,
		&i.DocumentsCount,
		&i.AcceptancesCount,
		&i.CookieRecordsCount,
		&i.ContentSha256,
		&i.PreviousChain,
		&i.ChainSha256,
		&i.Signature,
		&i.KeyID,
		&i.Algorithm,
		&i.GeneratedAt,
	)
	return i, err
}

const setLegalReviewDraft = `-- name: SetLegalReviewDraft :one
UPDATE legal_review
SET draft_version_id = $1,
    status = 'DRAFTED',
    updated_at = now()
WHERE id = $2 AND draft_version_id IS NULL
RETURNING id, document_id, rule_key, due_at, status, draft_version_id, notes, opened_at, completed_at, created_at, updated_at
`

type SetLegalReviewDraftParams struct {
	DraftVersionID pgtype.Text `json:"draft_version_id"`
	ID             string      `json:"id"`
}

func (q *Queries) SetLegalReviewDraft(ctx context.Context, arg SetLegalReviewDraftParams) (LegalReview, error) {
	row := q.db.QueryRow(ctx, setLegalReviewDraft, arg.DraftVersionID, arg.ID)
	var i LegalReview
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RuleKey,
		&i.DueAt,
		&i.Status,
		&i.DraftVersionID,
		&i.Notes,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLegalReview = `-- name: UpsertLegalReview :one

INSERT INTO legal_review (document_id, rule_key, due_at, status, notes)
VALUES (
    $1,
    $2,
    $3,
    'OPEN',
    $4
)
ON CONFLICT (document_id, rule_key, due_at) DO UPDATE
    SET updated_at = legal_review.updated_at
RETURNING id, document_id, rule_key, due_at, status, draft_version_id, notes, opened_at, completed_at, created_at, updated_at
`

type UpsertLegalReviewParams struct {
	DocumentID string           `json:"document_id"`
	RuleKey    string           `json:"rule_key"`
	DueAt      pgtype.Timestamp `json:"due_at"`
	Notes      pgtype.Text      `json:"notes"`
}

// ─── Revues périodiques ──────────────────────────────────────────────
// Ouvre (ou retrouve) la revue d'une échéance. `DO UPDATE` sans effet permet
// de récupérer la ligne existante : une même échéance n'ouvre qu'une revue,
// quel que soit le nombre de passages du worker.
func (q *Queries) UpsertLegalReview(ctx context.Context, arg UpsertLegalReviewParams) (LegalReview, error) {
	row := q.db.QueryRow(ctx, upsertLegalReview,
		arg.DocumentID,
		arg.RuleKey,
		arg.DueAt,
		arg.Notes,
	)
	var i LegalReview
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RuleKey,
		&i.DueAt,
		&i.Status,
		&i.DraftVersionID,
		&i.Notes,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
