// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveLegalDocumentVersion = `-- name: ArchiveLegalDocumentVersion :one
UPDATE legal_document_version
SET status = 'ARCHIVED', archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'PUBLISHED'
RETURNING id, document_id, locale, version, title, summary, body, status, changelog, effective_at, published_at, archived_at, created_by, created_at, updated_at
`

func (q *Queries) ArchiveLegalDocumentVersion(ctx context.Context, id string) (LegalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, archiveLegalDocumentVersion, id)
	var i LegalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Status,
		&i.Changelog,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archivePublishedLegalVersions = `-- name: ArchivePublishedLegalVersions :exec
UPDATE legal_document_version
SET status = 'ARCHIVED', archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE document_id = $1 AND locale = $2 AND status = 'PUBLISHED'
`

type ArchivePublishedLegalVersionsParams struct {
	DocumentID string `json:"document_id"`
	Locale     string `json:"locale"`
}

func (q *Queries) ArchivePublishedLegalVersions(ctx context.Context, arg ArchivePublishedLegalVersionsParams) error {
	_, err := q.db.Exec(ctx, archivePublishedLegalVersions, arg.DocumentID, arg.Locale)
	return err
}

const countLegalDocuments = `-- name: CountLegalDocuments :one
SELECT count(*) FROM legal_document
`

func (q *Queries) CountLegalDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLegalDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLegalDocument = `-- name: DeleteLegalDocument :exec
DELETE FROM legal_document WHERE id = $1
`

func (q *Queries) DeleteLegalDocument(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLegalDocument, id)
	return err
}

const deleteLegalDocumentVersion = `-- name: DeleteLegalDocumentVersion :exec
DELETE FROM legal_document_version WHERE id = $1 AND status = 'DRAFT'
`

func (q *Queries) DeleteLegalDocumentVersion(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLegalDocumentVersion, id)
	return err
}

const getLegalAcceptance = `-- name: GetLegalAcceptance :one
SELECT id, user_id, document_id, version_id, version, locale, accepted_at, ip, user_agent, source, method FROM legal_acceptance
WHERE user_id = $1::uuid AND version_id = $2
`

type GetLegalAcceptanceParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	VersionID string      `json:"version_id"`
}

func (q *Queries) GetLegalAcceptance(ctx context.Context, arg GetLegalAcceptanceParams) (LegalAcceptance, error) {
	row := q.db.QueryRow(ctx, getLegalAcceptance, arg.UserID, arg.VersionID)
	var i LegalAcceptance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.VersionID,
		&i.Version,
		&i.Locale,
		&i.AcceptedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Source,
		&i.Method,
	)
	return i, err
}

const getLegalDocumentByID = `-- name: GetLegalDocumentByID :one
SELECT id, slug, category, audience, requires_acceptance, is_active, sort_order, created_at, updated_at FROM legal_document WHERE id = $1
`

func (q *Queries) GetLegalDocumentByID(ctx context.Context, id string) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, getLegalDocumentByID, id)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Audience,
		&i.RequiresAcceptance,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegalDocumentBySlug = `-- name: GetLegalDocumentBySlug :one
SELECT id, slug, category, audience, requires_acceptance, is_active, sort_order, created_at, updated_at FROM legal_document WHERE slug = $1
`

func (q *Queries) GetLegalDocumentBySlug(ctx context.Context, slug string) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, getLegalDocumentBySlug, slug)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Audience,
		&i.RequiresAcceptance,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegalDocumentVersion = `-- name: GetLegalDocumentVersion :one
SELECT id, document_id, locale, version, title, summary, body, status, changelog, effective_at, published_at, archived_at, created_by, created_at, updated_at FROM legal_document_version WHERE id = $1
`

func (q *Queries) GetLegalDocumentVersion(ctx context.Context, id string) (LegalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, getLegalDocumentVersion, id)
	var i LegalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Status,
		&i.Changelog,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedLegalDocument = `-- name: GetPublishedLegalDocument :one
SELECT d.id, d.slug, d.category, d.audience, d.requires_acceptance,
       v.id AS version_id, v.version, v.title, v.summary, v.body, v.changelog,
       v.locale, v.effective_at, v.published_at, v.updated_at
FROM legal_document d
JOIN legal_document_version v
  ON v.document_id = d.id AND v.status = 'PUBLISHED' AND v.locale = $1
WHERE d.slug = $2 AND d.is_active = true
`

type GetPublishedLegalDocumentParams struct {
	Locale string `json:"locale"`
	Slug   string `json:"slug"`
}

type GetPublishedLegalDocumentRow struct {
	ID                 string           `json:"id"`
	Slug               string           `json:"slug"`
	Category           string           `json:"category"`
	Audience           string           `json:"audience"`
	RequiresAcceptance bool             `json:"requires_acceptance"`
	VersionID          string           `json:"version_id"`
	Version            string           `json:"version"`
	Title              string           `json:"title"`
	Summary            string           `json:"summary"`
	Body               string           `json:"body"`
	Changelog          pgtype.Text      `json:"changelog"`
	Locale             string           `json:"locale"`
	EffectiveAt        pgtype.Timestamp `json:"effective_at"`
	PublishedAt        pgtype.Timestamp `json:"published_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

// Contenu complet d'un document publié (markdown).
func (q *Queries) GetPublishedLegalDocument(ctx context.Context, arg GetPublishedLegalDocumentParams) (GetPublishedLegalDocumentRow, error) {
	row := q.db.QueryRow(ctx, getPublishedLegalDocument, arg.Locale, arg.Slug)
	var i GetPublishedLegalDocumentRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Audience,
		&i.RequiresAcceptance,
		&i.VersionID,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Changelog,
		&i.Locale,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLegalDocument = `-- name: InsertLegalDocument :one
INSERT INTO legal_document (slug, category, audience, requires_acceptance, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, category, audience, requires_acceptance, is_active, sort_order, created_at, updated_at
`

type InsertLegalDocumentParams struct {
	Slug               string `json:"slug"`
	Category           string `json:"category"`
	Audience           string `json:"audience"`
	RequiresAcceptance bool   `json:"requires_acceptance"`
	IsActive           bool   `json:"is_active"`
	SortOrder          int32  `json:"sort_order"`
}

func (q *Queries) InsertLegalDocument(ctx context.Context, arg InsertLegalDocumentParams) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, insertLegalDocument,
		arg.Slug,
		arg.Category,
		arg.Audience,
		arg.RequiresAcceptance,
		arg.IsActive,
		arg.SortOrder,
	)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Audience,
		&i.RequiresAcceptance,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLegalDocumentVersion = `-- name: InsertLegalDocumentVersion :one
INSERT INTO legal_document_version (document_id, locale, version, title, summary, body, status, changelog, effective_at, created_by)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  'DRAFT',
  $7,
  $8,
  $9
)
RETURNING id, document_id, locale, version, title, summary, body, status, changelog, effective_at, published_at, archived_at, created_by, created_at, updated_at
`

type InsertLegalDocumentVersionParams struct {
	DocumentID  string           `json:"document_id"`
	Locale      string           `json:"locale"`
	Version     string           `json:"version"`
	Title       string           `json:"title"`
	Summary     string           `json:"summary"`
	Body        string           `json:"body"`
	Changelog   pgtype.Text      `json:"changelog"`
	EffectiveAt pgtype.Timestamp `json:"effective_at"`
	CreatedBy   pgtype.UUID      `json:"created_by"`
}

func (q *Queries) InsertLegalDocumentVersion(ctx context.Context, arg InsertLegalDocumentVersionParams) (LegalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, insertLegalDocumentVersion,
		arg.DocumentID,
		arg.Locale,
		arg.Version,
		arg.Title,
		arg.Summary,
		arg.Body,
		arg.Changelog,
		arg.EffectiveAt,
		arg.CreatedBy,
	)
	var i LegalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Status,
		&i.Changelog,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const legalAcceptanceStats = `-- name: LegalAcceptanceStats :many
SELECT d.id, d.slug, d.requires_acceptance,
       (SELECT count(*) FROM legal_acceptance a WHERE a.document_id = d.id) AS acceptances,
       (SELECT count(*) FROM legal_acceptance a WHERE a.document_id = d.id AND a.accepted_at > CURRENT_TIMESTAMP - INTERVAL '30 days') AS acceptances_30d,
       (SELECT count(*) FROM legal_document_version v WHERE v.document_id = d.id) AS versions_count
FROM legal_document d
ORDER BY d.sort_order ASC
`

type LegalAcceptanceStatsRow struct {
	ID                 string `json:"id"`
	Slug               string `json:"slug"`
	RequiresAcceptance bool   `json:"requires_acceptance"`
	Acceptances        int64  `json:"acceptances"`
	Acceptances30d     int64  `json:"acceptances_30d"`
	VersionsCount      int64  `json:"versions_count"`
}

// Preuve d'acceptation agrégée par document : combien d'utilisateurs ont
// accepté la version publiée courante (et combien ne l'ont pas encore fait).
func (q *Queries) LegalAcceptanceStats(ctx context.Context) ([]LegalAcceptanceStatsRow, error) {
	rows, err := q.db.Query(ctx, legalAcceptanceStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalAcceptanceStatsRow{}
	for rows.Next() {
		var i LegalAcceptanceStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.RequiresAcceptance,
			&i.Acceptances,
			&i.Acceptances30d,
			&i.VersionsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalAcceptancesAdmin = `-- name: ListLegalAcceptancesAdmin :many
SELECT a.id, a.user_id, a.document_id, a.version, a.locale, a.accepted_at, a.ip,
       a.user_agent, a.source, a.method, u.email AS user_email, d.slug AS document_slug
FROM legal_acceptance a
LEFT JOIN "User" u ON u.id = a.user_id
JOIN legal_document d ON d.id = a.document_id
WHERE ($1::text = '' OR d.slug = $1::text)
ORDER BY a.accepted_at DESC
LIMIT $2
`

type ListLegalAcceptancesAdminParams struct {
	Slug       string `json:"slug"`
	LimitCount int32  `json:"limit_count"`
}

type ListLegalAcceptancesAdminRow struct {
	ID           string           `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	DocumentID   string           `json:"document_id"`
	Version      string           `json:"version"`
	Locale       string           `json:"locale"`
	AcceptedAt   pgtype.Timestamp `json:"accepted_at"`
	Ip           pgtype.Text      `json:"ip"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	Source       string           `json:"source"`
	Method       string           `json:"method"`
	UserEmail    pgtype.Text      `json:"user_email"`
	DocumentSlug string           `json:"document_slug"`
}

func (q *Queries) ListLegalAcceptancesAdmin(ctx context.Context, arg ListLegalAcceptancesAdminParams) ([]ListLegalAcceptancesAdminRow, error) {
	rows, err := q.db.Query(ctx, listLegalAcceptancesAdmin, arg.Slug, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalAcceptancesAdminRow{}
	for rows.Next() {
		var i ListLegalAcceptancesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DocumentID,
			&i.Version,
			&i.Locale,
			&i.AcceptedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Source,
			&i.Method,
			&i.UserEmail,
			&i.DocumentSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalDocumentVersions = `-- name: ListLegalDocumentVersions :many
SELECT v.id, v.document_id, v.locale, v.version, v.title, v.summary, v.body, v.status,
       v.changelog, v.effective_at, v.published_at, v.archived_at, v.created_by,
       v.created_at, v.updated_at, u.name AS created_by_name
FROM legal_document_version v
LEFT JOIN "User" u ON u.id = v.created_by
WHERE v.document_id = $1
ORDER BY v.locale ASC, v.created_at DESC
`

type ListLegalDocumentVersionsRow struct {
	ID            string           `json:"id"`
	DocumentID    string           `json:"document_id"`
	Locale        string           `json:"locale"`
	Version       string           `json:"version"`
	Title         string           `json:"title"`
	Summary       string           `json:"summary"`
	Body          string           `json:"body"`
	Status        string           `json:"status"`
	Changelog     pgtype.Text      `json:"changelog"`
	EffectiveAt   pgtype.Timestamp `json:"effective_at"`
	PublishedAt   pgtype.Timestamp `json:"published_at"`
	ArchivedAt    pgtype.Timestamp `json:"archived_at"`
	CreatedBy     pgtype.UUID      `json:"created_by"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CreatedByName pgtype.Text      `json:"created_by_name"`
}

func (q *Queries) ListLegalDocumentVersions(ctx context.Context, documentID string) ([]ListLegalDocumentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listLegalDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalDocumentVersionsRow{}
	for rows.Next() {
		var i ListLegalDocumentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Locale,
			&i.Version,
			&i.Title,
			&i.Summary,
			&i.Body,
			&i.Status,
			&i.Changelog,
			&i.EffectiveAt,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalDocumentsAdmin = `-- name: ListLegalDocumentsAdmin :many

SELECT d.id, d.slug, d.category, d.audience, d.requires_acceptance, d.is_active,
       d.sort_order, d.created_at, d.updated_at,
       (SELECT count(*) FROM legal_document_version v WHERE v.document_id = d.id) AS versions_count,
       (SELECT count(*) FROM legal_document_version v WHERE v.document_id = d.id AND v.status = 'DRAFT') AS drafts_count,
       (SELECT count(*) FROM legal_acceptance a WHERE a.document_id = d.id) AS acceptances_count,
       COALESCE(pub.version, '') AS published_version,
       COALESCE(pub.locale, '') AS published_locale,
       COALESCE((SELECT v2.title FROM legal_document_version v2 WHERE v2.document_id = d.id AND v2.status = 'PUBLISHED' LIMIT 1), '')::text AS published_title
FROM legal_document d
LEFT JOIN LATERAL (
    SELECT v.version, v.locale FROM legal_document_version v
    WHERE v.document_id = d.id AND v.status = 'PUBLISHED'
    LIMIT 1
) pub ON true
ORDER BY d.sort_order ASC, d.slug ASC
`

type ListLegalDocumentsAdminRow struct {
	ID                 string           `json:"id"`
	Slug               string           `json:"slug"`
	Category           string           `json:"category"`
	Audience           string           `json:"audience"`
	RequiresAcceptance bool             `json:"requires_acceptance"`
	IsActive           bool             `json:"is_active"`
	SortOrder          int32            `json:"sort_order"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	VersionsCount      int64            `json:"versions_count"`
	DraftsCount        int64            `json:"drafts_count"`
	AcceptancesCount   int64            `json:"acceptances_count"`
	PublishedVersion   string           `json:"published_version"`
	PublishedLocale    string           `json:"published_locale"`
	PublishedTitle     string           `json:"published_title"`
}

// ─── Superadmin ─────────────────────────────────────────────────────
func (q *Queries) ListLegalDocumentsAdmin(ctx context.Context) ([]ListLegalDocumentsAdminRow, error) {
	rows, err := q.db.Query(ctx, listLegalDocumentsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLegalDocumentsAdminRow{}
	for rows.Next() {
		var i ListLegalDocumentsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Category,
			&i.Audience,
			&i.RequiresAcceptance,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VersionsCount,
			&i.DraftsCount,
			&i.AcceptancesCount,
			&i.PublishedVersion,
			&i.PublishedLocale,
			&i.PublishedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLegalAcceptances = `-- name: ListPendingLegalAcceptances :many
SELECT d.id, d.slug, d.category, d.audience, v.id AS version_id, v.version,
       v.title, v.effective_at
FROM legal_document d
JOIN legal_document_version v
  ON v.document_id = d.id AND v.status = 'PUBLISHED' AND v.locale = $1
LEFT JOIN legal_acceptance a
  ON a.version_id = v.id AND a.user_id = $2::uuid
WHERE d.is_active = true AND d.requires_acceptance = true AND a.id IS NULL
ORDER BY d.sort_order ASC
`

type ListPendingLegalAcceptancesParams struct {
	Locale string      `json:"locale"`
	UserID pgtype.UUID `json:"user_id"`
}

type ListPendingLegalAcceptancesRow struct {
	ID          string           `json:"id"`
	Slug        string           `json:"slug"`
	Category    string           `json:"category"`
	Audience    string           `json:"audience"`
	VersionID   string           `json:"version_id"`
	Version     string           `json:"version"`
	Title       string           `json:"title"`
	EffectiveAt pgtype.Timestamp `json:"effective_at"`
}

// Documents qui exigent une acceptation et que l'utilisateur n'a pas encore
// acceptés dans leur version publiée courante (déclencheur de re-consentement
// après une nouvelle version).
func (q *Queries) ListPendingLegalAcceptances(ctx context.Context, arg ListPendingLegalAcceptancesParams) ([]ListPendingLegalAcceptancesRow, error) {
	rows, err := q.db.Query(ctx, listPendingLegalAcceptances, arg.Locale, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingLegalAcceptancesRow{}
	for rows.Next() {
		var i ListPendingLegalAcceptancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Category,
			&i.Audience,
			&i.VersionID,
			&i.Version,
			&i.Title,
			&i.EffectiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedLegalDocuments = `-- name: ListPublishedLegalDocuments :many


SELECT d.id, d.slug, d.category, d.audience, d.requires_acceptance, d.sort_order,
       v.id AS version_id, v.version, v.title, v.summary, v.changelog,
       v.locale, v.effective_at, v.published_at, v.updated_at
FROM legal_document d
JOIN legal_document_version v
  ON v.document_id = d.id AND v.status = 'PUBLISHED' AND v.locale = $1
WHERE d.is_active = true
ORDER BY d.sort_order ASC, d.slug ASC
`

type ListPublishedLegalDocumentsRow struct {
	ID                 string           `json:"id"`
	Slug               string           `json:"slug"`
	Category           string           `json:"category"`
	Audience           string           `json:"audience"`
	RequiresAcceptance bool             `json:"requires_acceptance"`
	SortOrder          int32            `json:"sort_order"`
	VersionID          string           `json:"version_id"`
	Version            string           `json:"version"`
	Title              string           `json:"title"`
	Summary            string           `json:"summary"`
	Changelog          pgtype.Text      `json:"changelog"`
	Locale             string           `json:"locale"`
	EffectiveAt        pgtype.Timestamp `json:"effective_at"`
	PublishedAt        pgtype.Timestamp `json:"published_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

// ═══════════════════════════════════════════════════════════════════
// ⚖️ Legal — documents juridiques versionnés
//
//	Public  : lecture des versions publiées + consentement du lecteur
//	Admin   : CRUD superadmin (brouillons, publication, archivage, preuves)
//
// ═══════════════════════════════════════════════════════════════════
// ─── Public ─────────────────────────────────────────────────────────
// Sommaire public : uniquement les documents actifs ayant une version
// publiée dans la locale demandée.
func (q *Queries) ListPublishedLegalDocuments(ctx context.Context, locale string) ([]ListPublishedLegalDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedLegalDocuments, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedLegalDocumentsRow{}
	for rows.Next() {
		var i ListPublishedLegalDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Category,
			&i.Audience,
			&i.RequiresAcceptance,
			&i.SortOrder,
			&i.VersionID,
			&i.Version,
			&i.Title,
			&i.Summary,
			&i.Changelog,
			&i.Locale,
			&i.EffectiveAt,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedLegalVersions = `-- name: ListPublishedLegalVersions :many
SELECT v.id, v.document_id, v.locale, v.version, v.title, v.summary, v.status,
       v.changelog, v.effective_at, v.published_at, v.archived_at, v.created_at
FROM legal_document_version v
JOIN legal_document d ON d.id = v.document_id
WHERE d.slug = $1 AND v.locale = $2 AND v.status <> 'DRAFT'
ORDER BY v.published_at DESC NULLS LAST, v.created_at DESC
`

type ListPublishedLegalVersionsParams struct {
	Slug   string `json:"slug"`
	Locale string `json:"locale"`
}

type ListPublishedLegalVersionsRow struct {
	ID          string           `json:"id"`
	DocumentID  string           `json:"document_id"`
	Locale      string           `json:"locale"`
	Version     string           `json:"version"`
	Title       string           `json:"title"`
	Summary     string           `json:"summary"`
	Status      string           `json:"status"`
	Changelog   pgtype.Text      `json:"changelog"`
	EffectiveAt pgtype.Timestamp `json:"effective_at"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	ArchivedAt  pgtype.Timestamp `json:"archived_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

// Historique public (transparence) : versions publiées/archivées, jamais les brouillons.
func (q *Queries) ListPublishedLegalVersions(ctx context.Context, arg ListPublishedLegalVersionsParams) ([]ListPublishedLegalVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedLegalVersions, arg.Slug, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedLegalVersionsRow{}
	for rows.Next() {
		var i ListPublishedLegalVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Locale,
			&i.Version,
			&i.Title,
			&i.Summary,
			&i.Status,
			&i.Changelog,
			&i.EffectiveAt,
			&i.PublishedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLegalAcceptances = `-- name: ListUserLegalAcceptances :many
SELECT a.id, a.document_id, a.version_id, a.version, a.locale, a.accepted_at,
       a.source, a.method, d.slug, d.category
FROM legal_acceptance a
JOIN legal_document d ON d.id = a.document_id
WHERE a.user_id = $1::uuid
ORDER BY a.accepted_at DESC
`

type ListUserLegalAcceptancesRow struct {
	ID         string           `json:"id"`
	DocumentID string           `json:"document_id"`
	VersionID  string           `json:"version_id"`
	Version    string           `json:"version"`
	Locale     string           `json:"locale"`
	AcceptedAt pgtype.Timestamp `json:"accepted_at"`
	Source     string           `json:"source"`
	Method     string           `json:"method"`
	Slug       string           `json:"slug"`
	Category   string           `json:"category"`
}

func (q *Queries) ListUserLegalAcceptances(ctx context.Context, userID pgtype.UUID) ([]ListUserLegalAcceptancesRow, error) {
	rows, err := q.db.Query(ctx, listUserLegalAcceptances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserLegalAcceptancesRow{}
	for rows.Next() {
		var i ListUserLegalAcceptancesRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionID,
			&i.Version,
			&i.Locale,
			&i.AcceptedAt,
			&i.Source,
			&i.Method,
			&i.Slug,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishLegalDocumentVersion = `-- name: PublishLegalDocumentVersion :one
UPDATE legal_document_version
SET status = 'PUBLISHED', published_at = CURRENT_TIMESTAMP, archived_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'DRAFT'
RETURNING id, document_id, locale, version, title, summary, body, status, changelog, effective_at, published_at, archived_at, created_by, created_at, updated_at
`

func (q *Queries) PublishLegalDocumentVersion(ctx context.Context, id string) (LegalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, publishLegalDocumentVersion, id)
	var i LegalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Status,
		&i.Changelog,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLegalDocument = `-- name: UpdateLegalDocument :one
UPDATE legal_document
SET slug = $1,
    category = $2,
    audience = $3,
    requires_acceptance = $4,
    is_active = $5,
    sort_order = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, slug, category, audience, requires_acceptance, is_active, sort_order, created_at, updated_at
`

type UpdateLegalDocumentParams struct {
	Slug               string `json:"slug"`
	Category           string `json:"category"`
	Audience           string `json:"audience"`
	RequiresAcceptance bool   `json:"requires_acceptance"`
	IsActive           bool   `json:"is_active"`
	SortOrder          int32  `json:"sort_order"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdateLegalDocument(ctx context.Context, arg UpdateLegalDocumentParams) (LegalDocument, error) {
	row := q.db.QueryRow(ctx, updateLegalDocument,
		arg.Slug,
		arg.Category,
		arg.Audience,
		arg.RequiresAcceptance,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	var i LegalDocument
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.Audience,
		&i.RequiresAcceptance,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLegalDocumentVersion = `-- name: UpdateLegalDocumentVersion :one
UPDATE legal_document_version
SET title = $1,
    summary = $2,
    body = $3,
    changelog = $4,
    effective_at = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6 AND status = 'DRAFT'
RETURNING id, document_id, locale, version, title, summary, body, status, changelog, effective_at, published_at, archived_at, created_by, created_at, updated_at
`

type UpdateLegalDocumentVersionParams struct {
	Title       string           `json:"title"`
	Summary     string           `json:"summary"`
	Body        string           `json:"body"`
	Changelog   pgtype.Text      `json:"changelog"`
	EffectiveAt pgtype.Timestamp `json:"effective_at"`
	ID          string           `json:"id"`
}

// Un brouillon est éditable ; une version publiée est immuable (on publie une
// nouvelle version, l'ancienne reste archivée comme preuve légale).
func (q *Queries) UpdateLegalDocumentVersion(ctx context.Context, arg UpdateLegalDocumentVersionParams) (LegalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, updateLegalDocumentVersion,
		arg.Title,
		arg.Summary,
		arg.Body,
		arg.Changelog,
		arg.EffectiveAt,
		arg.ID,
	)
	var i LegalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Locale,
		&i.Version,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Status,
		&i.Changelog,
		&i.EffectiveAt,
		&i.PublishedAt,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLegalAcceptance = `-- name: UpsertLegalAcceptance :one
INSERT INTO legal_acceptance (user_id, document_id, version_id, version, locale, ip, user_agent, source, method)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (user_id, version_id) DO UPDATE
  SET source = legal_acceptance.source,
      method = legal_acceptance.method
RETURNING id, user_id, document_id, version_id, version, locale, accepted_at, ip, user_agent, source, method
`

type UpsertLegalAcceptanceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	DocumentID string      `json:"document_id"`
	VersionID  string      `json:"version_id"`
	Version    string      `json:"version"`
	Locale     string      `json:"locale"`
	Ip         pgtype.Text `json:"ip"`
	UserAgent  pgtype.Text `json:"user_agent"`
	Source     string      `json:"source"`
	Method     string      `json:"method"`
}

// Idempotent : un re-clic ne crée pas de doublon, il rafraîchit la preuve.
// La preuve est immuable : un re-clic renvoie la première acceptation sans
// la réécrire (sinon une source par défaut écraserait la preuve d'origine).
func (q *Queries) UpsertLegalAcceptance(ctx context.Context, arg UpsertLegalAcceptanceParams) (LegalAcceptance, error) {
	row := q.db.QueryRow(ctx, upsertLegalAcceptance,
		arg.UserID,
		arg.DocumentID,
		arg.VersionID,
		arg.Version,
		arg.Locale,
		arg.Ip,
		arg.UserAgent,
		arg.Source,
		arg.Method,
	)
	var i LegalAcceptance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.VersionID,
		&i.Version,
		&i.Locale,
		&i.AcceptedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Source,
		&i.Method,
	)
	return i, err
}
