// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO "MediaAsset" (id, sha256, url, "storagePath", bucket, "mimeType", width, height,
                          "sizeBytes", blurhash, "isNsfw", "isSensitive", "safetyScores",
                          "ownerId", "targetType", status, "purgeDueAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
        'DRAFT_ORPHAN', now() + interval '3 days', now())
RETURNING id, sha256, url, "storagePath", bucket, "mimeType", width, height, "sizeBytes", blurhash, "isNsfw", "isSensitive", "safetyScores", "moderatedAt", status, "targetType", "ownerId", "attachedToId", "purgeDueAt", "deletedAt", "createdAt", "updatedAt"
`

type CreateMediaAssetParams struct {
	Sha256       string               `json:"sha256"`
	Url          string               `json:"url"`
	StoragePath  string               `json:"storagePath"`
	Bucket       string               `json:"bucket"`
	MimeType     string               `json:"mimeType"`
	Width        pgtype.Int4          `json:"width"`
	Height       pgtype.Int4          `json:"height"`
	SizeBytes    int32                `json:"sizeBytes"`
	Blurhash     pgtype.Text          `json:"blurhash"`
	IsNsfw       bool                 `json:"isNsfw"`
	IsSensitive  bool                 `json:"isSensitive"`
	SafetyScores []byte               `json:"safetyScores"`
	OwnerId      string               `json:"ownerId"`
	TargetType   MediaAssetTargetType `json:"targetType"`
}

// Nouvel asset orphelin (DRAFT_ORPHAN, purgé dans 3 jours si non attaché).
func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.Sha256,
		arg.Url,
		arg.StoragePath,
		arg.Bucket,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Blurhash,
		arg.IsNsfw,
		arg.IsSensitive,
		arg.SafetyScores,
		arg.OwnerId,
		arg.TargetType,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Url,
		&i.StoragePath,
		&i.Bucket,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Blurhash,
		&i.IsNsfw,
		&i.IsSensitive,
		&i.SafetyScores,
		&i.ModeratedAt,
		&i.Status,
		&i.TargetType,
		&i.OwnerId,
		&i.AttachedToId,
		&i.PurgeDueAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaAssetBySha256 = `-- name: GetMediaAssetBySha256 :one
SELECT id, sha256, url, "storagePath", bucket, "mimeType", width, height, "sizeBytes", blurhash, "isNsfw", "isSensitive", "safetyScores", "moderatedAt", status, "targetType", "ownerId", "attachedToId", "purgeDueAt", "deletedAt", "createdAt", "updatedAt" FROM "MediaAsset" WHERE "sha256" = $1 LIMIT 1
`

// Dédoublonnage CAS : cherche un asset existant par hash SHA-256.
func (q *Queries) GetMediaAssetBySha256(ctx context.Context, sha256 string) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAssetBySha256, sha256)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Url,
		&i.StoragePath,
		&i.Bucket,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Blurhash,
		&i.IsNsfw,
		&i.IsSensitive,
		&i.SafetyScores,
		&i.ModeratedAt,
		&i.Status,
		&i.TargetType,
		&i.OwnerId,
		&i.AttachedToId,
		&i.PurgeDueAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reactivateMediaAsset = `-- name: ReactivateMediaAsset :one
UPDATE "MediaAsset"
SET status = 'DRAFT_ORPHAN', "purgeDueAt" = now() + interval '3 days', "deletedAt" = NULL, "updatedAt" = now()
WHERE id = $1
RETURNING id, sha256, url, "storagePath", bucket, "mimeType", width, height, "sizeBytes", blurhash, "isNsfw", "isSensitive", "safetyScores", "moderatedAt", status, "targetType", "ownerId", "attachedToId", "purgeDueAt", "deletedAt", "createdAt", "updatedAt"
`

// Réactive un asset purgé/supprimé (nouvelle fenêtre de 3 jours).
func (q *Queries) ReactivateMediaAsset(ctx context.Context, id string) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, reactivateMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.Url,
		&i.StoragePath,
		&i.Bucket,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Blurhash,
		&i.IsNsfw,
		&i.IsSensitive,
		&i.SafetyScores,
		&i.ModeratedAt,
		&i.Status,
		&i.TargetType,
		&i.OwnerId,
		&i.AttachedToId,
		&i.PurgeDueAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
