// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one

INSERT INTO "Message" (id, "conversationId", "senderId", content)
VALUES (gen_random_uuid()::text, $1, $2, $3)
RETURNING id, "senderId"::text AS sender_id, content, "createdAt"
`

type InsertMessageParams struct {
	ConversationId string      `json:"conversationId"`
	SenderId       pgtype.UUID `json:"senderId"`
	Content        string      `json:"content"`
}

type InsertMessageRow struct {
	ID        string           `json:"id"`
	SenderID  string           `json:"sender_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

// Messagerie directe : messages (tranche 1).
// Table : Message. Pagination arrière par curseur createdAt (exclusif),
// plus récupération incrémentale des nouveaux messages pour le polling.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ConversationId, arg.SenderId, arg.Content)
	var i InsertMessageRow
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT id, "senderId"::text AS sender_id, content, "createdAt"
FROM "Message"
WHERE "conversationId" = $1 AND "createdAt" > $2
ORDER BY "createdAt" ASC, id ASC
LIMIT $3
`

type ListMessagesAfterParams struct {
	ConversationId string           `json:"conversationId"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	Limit          int32            `json:"limit"`
}

type ListMessagesAfterRow struct {
	ID        string           `json:"id"`
	SenderID  string           `json:"sender_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

// Nouveaux messages STRICTEMENT postérieurs à `after` (polling), ordre
// ascendant prêt à être ajouté en fin de liste.
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter, arg.ConversationId, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesAfterRow{}
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, "senderId"::text AS sender_id, content, "createdAt"
FROM "Message"
WHERE "conversationId" = $1
  AND ($2::timestamp IS NULL OR "createdAt" < $2)
ORDER BY "createdAt" DESC, id DESC
LIMIT $3
`

type ListMessagesBeforeParams struct {
	ConversationId string           `json:"conversationId"`
	Column2        pgtype.Timestamp `json:"column_2"`
	Limit          int32            `json:"limit"`
}

type ListMessagesBeforeRow struct {
	ID        string           `json:"id"`
	SenderID  string           `json:"sender_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

// Messages STRICTEMENT antérieurs à `before` (curseur exclusif, NULL = depuis
// le début), les plus récents d'abord (le service inverse pour l'affichage).
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.ConversationId, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesBeforeRow{}
	for rows.Next() {
		var i ListMessagesBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
