// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOptionVotes = `-- name: CountOptionVotes :one
SELECT COUNT(*)::int AS count
FROM "PollVote"
WHERE "optionId" = $1
`

func (q *Queries) CountOptionVotes(ctx context.Context, optionid string) (int32, error) {
	row := q.db.QueryRow(ctx, countOptionVotes, optionid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countOptionVotesByIDs = `-- name: CountOptionVotesByIDs :many
SELECT o."pollId", v."optionId", COUNT(*)::int AS count
FROM "PollVote" v
JOIN "PollOption" o ON o.id = v."optionId"
WHERE o."pollId" = ANY($1::text[])
GROUP BY o."pollId", v."optionId"
`

type CountOptionVotesByIDsRow struct {
	PollId   string `json:"pollId"`
	OptionId string `json:"optionId"`
	Count    int32  `json:"count"`
}

func (q *Queries) CountOptionVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountOptionVotesByIDsRow, error) {
	rows, err := q.db.Query(ctx, countOptionVotesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOptionVotesByIDsRow{}
	for rows.Next() {
		var i CountOptionVotesByIDsRow
		if err := rows.Scan(&i.PollId, &i.OptionId, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPollVotes = `-- name: CountPollVotes :one
SELECT COUNT(*)::int AS count
FROM "PollVote"
WHERE "pollId" = $1
`

func (q *Queries) CountPollVotes(ctx context.Context, pollid string) (int32, error) {
	row := q.db.QueryRow(ctx, countPollVotes, pollid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countPollVotesByIDs = `-- name: CountPollVotesByIDs :many
SELECT "pollId", COUNT(*)::int AS count
FROM "PollVote"
WHERE "pollId" = ANY($1::text[])
GROUP BY "pollId"
`

type CountPollVotesByIDsRow struct {
	PollId string `json:"pollId"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountPollVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountPollVotesByIDsRow, error) {
	rows, err := q.db.Query(ctx, countPollVotesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPollVotesByIDsRow{}
	for rows.Next() {
		var i CountPollVotesByIDsRow
		if err := rows.Scan(&i.PollId, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPollVotesByPollID = `-- name: CountPollVotesByPollID :one
SELECT COUNT(*)::int AS count
FROM "PollVote"
WHERE "pollId" = $1
`

func (q *Queries) CountPollVotesByPollID(ctx context.Context, pollid string) (int32, error) {
	row := q.db.QueryRow(ctx, countPollVotesByPollID, pollid)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO "MediaAttachment" (id, "thoughtId", type, url, "altText", width, height, "order")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateAttachmentParams struct {
	ThoughtId string      `json:"thoughtId"`
	Type      string      `json:"type"`
	Url       string      `json:"url"`
	AltText   pgtype.Text `json:"altText"`
	Width     pgtype.Int4 `json:"width"`
	Height    pgtype.Int4 `json:"height"`
	Order     int32       `json:"order"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (string, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ThoughtId,
		arg.Type,
		arg.Url,
		arg.AltText,
		arg.Width,
		arg.Height,
		arg.Order,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPoll = `-- name: CreatePoll :one
INSERT INTO "Poll" (id, "thoughtId", "expiresAt")
VALUES (gen_random_uuid()::text, $1, $2)
RETURNING id, "thoughtId", "expiresAt"
`

type CreatePollParams struct {
	ThoughtId string           `json:"thoughtId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

type CreatePollRow struct {
	ID        string           `json:"id"`
	ThoughtId string           `json:"thoughtId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.ThoughtId, arg.ExpiresAt)
	var i CreatePollRow
	err := row.Scan(&i.ID, &i.ThoughtId, &i.ExpiresAt)
	return i, err
}

const createPollOption = `-- name: CreatePollOption :one
INSERT INTO "PollOption" (id, "pollId", text, "order")
VALUES (gen_random_uuid()::text, $1, $2, $3)
RETURNING id
`

type CreatePollOptionParams struct {
	PollId string `json:"pollId"`
	Text   string `json:"text"`
	Order  int32  `json:"order"`
}

func (q *Queries) CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (string, error) {
	row := q.db.QueryRow(ctx, createPollOption, arg.PollId, arg.Text, arg.Order)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deletePollVote = `-- name: DeletePollVote :exec
DELETE FROM "PollVote"
WHERE "pollId" = $1 AND "userId" = $2
`

type DeletePollVoteParams struct {
	PollId string      `json:"pollId"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) DeletePollVote(ctx context.Context, arg DeletePollVoteParams) error {
	_, err := q.db.Exec(ctx, deletePollVote, arg.PollId, arg.UserId)
	return err
}

const getAttachmentsByIDs = `-- name: GetAttachmentsByIDs :many
SELECT id, "thoughtId", type, url, "altText", width, height, "order"
FROM "MediaAttachment"
WHERE "thoughtId" = ANY($1::text[])
ORDER BY "order" ASC
`

type GetAttachmentsByIDsRow struct {
	ID        string      `json:"id"`
	ThoughtId string      `json:"thoughtId"`
	Type      string      `json:"type"`
	Url       string      `json:"url"`
	AltText   pgtype.Text `json:"altText"`
	Width     pgtype.Int4 `json:"width"`
	Height    pgtype.Int4 `json:"height"`
	Order     int32       `json:"order"`
}

func (q *Queries) GetAttachmentsByIDs(ctx context.Context, dollar_1 []string) ([]GetAttachmentsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttachmentsByIDsRow{}
	for rows.Next() {
		var i GetAttachmentsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThoughtId,
			&i.Type,
			&i.Url,
			&i.AltText,
			&i.Width,
			&i.Height,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollByThoughtID = `-- name: GetPollByThoughtID :one

SELECT id, "thoughtId", "expiresAt"
FROM "Poll"
WHERE "thoughtId" = $1
`

type GetPollByThoughtIDRow struct {
	ID        string           `json:"id"`
	ThoughtId string           `json:"thoughtId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

// Polls, votes, pièces jointes
func (q *Queries) GetPollByThoughtID(ctx context.Context, thoughtid string) (GetPollByThoughtIDRow, error) {
	row := q.db.QueryRow(ctx, getPollByThoughtID, thoughtid)
	var i GetPollByThoughtIDRow
	err := row.Scan(&i.ID, &i.ThoughtId, &i.ExpiresAt)
	return i, err
}

const getPollOptionByID = `-- name: GetPollOptionByID :one
SELECT id, "pollId", text, "order"
FROM "PollOption"
WHERE id = $1
`

func (q *Queries) GetPollOptionByID(ctx context.Context, id string) (PollOption, error) {
	row := q.db.QueryRow(ctx, getPollOptionByID, id)
	var i PollOption
	err := row.Scan(
		&i.ID,
		&i.PollId,
		&i.Text,
		&i.Order,
	)
	return i, err
}

const getPollOptions = `-- name: GetPollOptions :many
SELECT id, "pollId", text, "order"
FROM "PollOption"
WHERE "pollId" = $1
ORDER BY "order" ASC
`

func (q *Queries) GetPollOptions(ctx context.Context, pollid string) ([]PollOption, error) {
	rows, err := q.db.Query(ctx, getPollOptions, pollid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PollOption{}
	for rows.Next() {
		var i PollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollId,
			&i.Text,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollOptionsByIDs = `-- name: GetPollOptionsByIDs :many
SELECT id, "pollId", text, "order"
FROM "PollOption"
WHERE "pollId" = ANY($1::text[])
ORDER BY "order" ASC
`

func (q *Queries) GetPollOptionsByIDs(ctx context.Context, dollar_1 []string) ([]PollOption, error) {
	rows, err := q.db.Query(ctx, getPollOptionsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PollOption{}
	for rows.Next() {
		var i PollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollId,
			&i.Text,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollsByIDs = `-- name: GetPollsByIDs :many
SELECT id, "thoughtId", "expiresAt"
FROM "Poll"
WHERE "thoughtId" = ANY($1::text[])
`

type GetPollsByIDsRow struct {
	ID        string           `json:"id"`
	ThoughtId string           `json:"thoughtId"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

func (q *Queries) GetPollsByIDs(ctx context.Context, dollar_1 []string) ([]GetPollsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getPollsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPollsByIDsRow{}
	for rows.Next() {
		var i GetPollsByIDsRow
		if err := rows.Scan(&i.ID, &i.ThoughtId, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPollVote = `-- name: GetUserPollVote :one
SELECT "optionId"
FROM "PollVote"
WHERE "pollId" = $1 AND "userId" = $2
`

type GetUserPollVoteParams struct {
	PollId string      `json:"pollId"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) GetUserPollVote(ctx context.Context, arg GetUserPollVoteParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserPollVote, arg.PollId, arg.UserId)
	var optionId string
	err := row.Scan(&optionId)
	return optionId, err
}

const getUserVoteForPoll = `-- name: GetUserVoteForPoll :one
SELECT v."optionId"
FROM "PollVote" v
WHERE v."pollId" = $1 AND v."userId" = $2
LIMIT 1
`

type GetUserVoteForPollParams struct {
	PollId string      `json:"pollId"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) GetUserVoteForPoll(ctx context.Context, arg GetUserVoteForPollParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserVoteForPoll, arg.PollId, arg.UserId)
	var optionId string
	err := row.Scan(&optionId)
	return optionId, err
}

const getUserVotesByIDs = `-- name: GetUserVotesByIDs :many
SELECT "pollId", "optionId"
FROM "PollVote"
WHERE "pollId" = ANY($1::text[]) AND "userId" = $2
`

type GetUserVotesByIDsParams struct {
	Column1 []string    `json:"column_1"`
	UserId  pgtype.UUID `json:"userId"`
}

type GetUserVotesByIDsRow struct {
	PollId   string `json:"pollId"`
	OptionId string `json:"optionId"`
}

func (q *Queries) GetUserVotesByIDs(ctx context.Context, arg GetUserVotesByIDsParams) ([]GetUserVotesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getUserVotesByIDs, arg.Column1, arg.UserId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserVotesByIDsRow{}
	for rows.Next() {
		var i GetUserVotesByIDsRow
		if err := rows.Scan(&i.PollId, &i.OptionId); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPollVote = `-- name: InsertPollVote :one
INSERT INTO "PollVote" (id, "pollId", "optionId", "userId")
VALUES (gen_random_uuid()::text, $1, $2, $3)
ON CONFLICT ("pollId", "userId") DO UPDATE SET "optionId" = EXCLUDED."optionId"
RETURNING id
`

type InsertPollVoteParams struct {
	PollId   string      `json:"pollId"`
	OptionId string      `json:"optionId"`
	UserId   pgtype.UUID `json:"userId"`
}

// Vote (idempotent : ON CONFLICT DO UPDATE pour changer d'option).
func (q *Queries) InsertPollVote(ctx context.Context, arg InsertPollVoteParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPollVote, arg.PollId, arg.OptionId, arg.UserId)
	var id string
	err := row.Scan(&id)
	return id, err
}
