// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPinnedPosts = `-- name: ClearPinnedPosts :exec
UPDATE "Post"
SET "isPinned" = false
WHERE "authorId" = $1
  AND "isPinned" = true
  AND "deletedAt" IS NULL
`

func (q *Queries) ClearPinnedPosts(ctx context.Context, authorid string) error {
	_, err := q.db.Exec(ctx, clearPinnedPosts, authorid)
	return err
}

const countPureReposts = `-- name: CountPureReposts :one
SELECT COUNT(*)::int AS count
FROM "Post"
WHERE "authorId" = $1
  AND "repostId" = $2
  AND "deletedAt" IS NULL
  AND (content = '' OR content = ' ')
`

type CountPureRepostsParams struct {
	AuthorId string      `json:"authorId"`
	RepostId pgtype.Text `json:"repostId"`
}

func (q *Queries) CountPureReposts(ctx context.Context, arg CountPureRepostsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPureReposts, arg.AuthorId, arg.RepostId)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createModerationReport = `-- name: CreateModerationReport :one
INSERT INTO "ModerationReport" (id, "reporterId", "targetId", "targetType", "reason", "details", "createdAt", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, $5, now(), now())
RETURNING id
`

type CreateModerationReportParams struct {
	ReporterId pgtype.UUID `json:"reporterId"`
	TargetId   string      `json:"targetId"`
	TargetType string      `json:"targetType"`
	Reason     string      `json:"reason"`
	Details    pgtype.Text `json:"details"`
}

func (q *Queries) CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (string, error) {
	row := q.db.QueryRow(ctx, createModerationReport,
		arg.ReporterId,
		arg.TargetId,
		arg.TargetType,
		arg.Reason,
		arg.Details,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createThought = `-- name: CreateThought :one
INSERT INTO "Post" (id, "content", "authorId", "updatedAt", tags, "imageUrl", visibility, "contentVisibility", "isDraft", "scheduledAt", "triggerWarning", "parentId", "rootId", "repostId", "replyRestriction", "isPinned", "likeCount", "repostCount", "replyCount")
VALUES (gen_random_uuid()::text, $1, $2, now(), $3, $4, $5, $6, $7, $8, $9, NULLIF($10, ''), NULLIF($11, ''), NULLIF($12, ''), $13, false, 0, 0, 0)
RETURNING id, "content", "authorId", "createdAt", tags, "parentId", "rootId", "repostId", "isDraft", "visibility", "contentVisibility"
`

type CreateThoughtParams struct {
	Content           string            `json:"content"`
	AuthorId          string            `json:"authorId"`
	Tags              []string          `json:"tags"`
	ImageUrl          pgtype.Text       `json:"imageUrl"`
	Visibility        string            `json:"visibility"`
	ContentVisibility ContentVisibility `json:"contentVisibility"`
	IsDraft           bool              `json:"isDraft"`
	ScheduledAt       pgtype.Timestamp  `json:"scheduledAt"`
	TriggerWarning    pgtype.Text       `json:"triggerWarning"`
	ParentId          interface{}       `json:"parentId"`
	RootId            interface{}       `json:"rootId"`
	RepostId          interface{}       `json:"repostId"`
	ReplyRestriction  string            `json:"replyRestriction"`
}

type CreateThoughtRow struct {
	ID                string            `json:"id"`
	Content           string            `json:"content"`
	AuthorId          string            `json:"authorId"`
	CreatedAt         pgtype.Timestamp  `json:"createdAt"`
	Tags              []string          `json:"tags"`
	ParentId          pgtype.Text       `json:"parentId"`
	RootId            pgtype.Text       `json:"rootId"`
	RepostId          pgtype.Text       `json:"repostId"`
	IsDraft           bool              `json:"isDraft"`
	Visibility        string            `json:"visibility"`
	ContentVisibility ContentVisibility `json:"contentVisibility"`
}

func (q *Queries) CreateThought(ctx context.Context, arg CreateThoughtParams) (CreateThoughtRow, error) {
	row := q.db.QueryRow(ctx, createThought,
		arg.Content,
		arg.AuthorId,
		arg.Tags,
		arg.ImageUrl,
		arg.Visibility,
		arg.ContentVisibility,
		arg.IsDraft,
		arg.ScheduledAt,
		arg.TriggerWarning,
		arg.ParentId,
		arg.RootId,
		arg.RepostId,
		arg.ReplyRestriction,
	)
	var i CreateThoughtRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorId,
		&i.CreatedAt,
		&i.Tags,
		&i.ParentId,
		&i.RootId,
		&i.RepostId,
		&i.IsDraft,
		&i.Visibility,
		&i.ContentVisibility,
	)
	return i, err
}

const decrementLikeCount = `-- name: DecrementLikeCount :exec
UPDATE "Post"
SET "likeCount" = GREATEST("likeCount" - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementLikeCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrementLikeCount, id)
	return err
}

const decrementReplyCount = `-- name: DecrementReplyCount :exec
UPDATE "Post"
SET "replyCount" = GREATEST("replyCount" - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementReplyCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrementReplyCount, id)
	return err
}

const decrementRepostCount = `-- name: DecrementRepostCount :exec
UPDATE "Post"
SET "repostCount" = GREATEST("repostCount" - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementRepostCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, decrementRepostCount, id)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM "BlockedUser"
WHERE "creatorId" = $1 AND "readerId" = $2
`

type DeleteBlockParams struct {
	CreatorId pgtype.UUID `json:"creatorId"`
	ReaderId  pgtype.UUID `json:"readerId"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.CreatorId, arg.ReaderId)
	return err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM "Like"
WHERE "postId" = $1 AND "userId" = $2
`

type DeleteLikeParams struct {
	PostId string      `json:"postId"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.PostId, arg.UserId)
	return err
}

const deleteMute = `-- name: DeleteMute :exec
DELETE FROM "MutedUser"
WHERE "muterId" = $1 AND "mutedId" = $2
`

type DeleteMuteParams struct {
	MuterId pgtype.UUID `json:"muterId"`
	MutedId pgtype.UUID `json:"mutedId"`
}

func (q *Queries) DeleteMute(ctx context.Context, arg DeleteMuteParams) error {
	_, err := q.db.Exec(ctx, deleteMute, arg.MuterId, arg.MutedId)
	return err
}

const deletePureReposts = `-- name: DeletePureReposts :exec
DELETE FROM "Post"
WHERE "authorId" = $1
  AND "repostId" = $2
  AND "deletedAt" IS NULL
  AND (content = '' OR content = ' ')
`

type DeletePureRepostsParams struct {
	AuthorId string      `json:"authorId"`
	RepostId pgtype.Text `json:"repostId"`
}

func (q *Queries) DeletePureReposts(ctx context.Context, arg DeletePureRepostsParams) error {
	_, err := q.db.Exec(ctx, deletePureReposts, arg.AuthorId, arg.RepostId)
	return err
}

const getCanonicalThoughtID = `-- name: GetCanonicalThoughtID :one
SELECT COALESCE("repostId", id)::text AS id
FROM "Post"
WHERE id = $1
`

func (q *Queries) GetCanonicalThoughtID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getCanonicalThoughtID, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const getExistingBlock = `-- name: GetExistingBlock :one
SELECT 1 AS present
FROM "BlockedUser"
WHERE "creatorId" = $1 AND "readerId" = $2
`

type GetExistingBlockParams struct {
	CreatorId pgtype.UUID `json:"creatorId"`
	ReaderId  pgtype.UUID `json:"readerId"`
}

func (q *Queries) GetExistingBlock(ctx context.Context, arg GetExistingBlockParams) (int32, error) {
	row := q.db.QueryRow(ctx, getExistingBlock, arg.CreatorId, arg.ReaderId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getExistingLike = `-- name: GetExistingLike :one
SELECT 1 AS present
FROM "Like"
WHERE "postId" = $1 AND "userId" = $2
`

type GetExistingLikeParams struct {
	PostId string      `json:"postId"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) GetExistingLike(ctx context.Context, arg GetExistingLikeParams) (int32, error) {
	row := q.db.QueryRow(ctx, getExistingLike, arg.PostId, arg.UserId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getExistingMute = `-- name: GetExistingMute :one
SELECT 1 AS present
FROM "MutedUser"
WHERE "muterId" = $1 AND "mutedId" = $2
`

type GetExistingMuteParams struct {
	MuterId pgtype.UUID `json:"muterId"`
	MutedId pgtype.UUID `json:"mutedId"`
}

func (q *Queries) GetExistingMute(ctx context.Context, arg GetExistingMuteParams) (int32, error) {
	row := q.db.QueryRow(ctx, getExistingMute, arg.MuterId, arg.MutedId)
	var present int32
	err := row.Scan(&present)
	return present, err
}

const getThoughtByID = `-- name: GetThoughtByID :one
SELECT p.id,
       p.content,
       p."authorId",
       p."createdAt",
       p."updatedAt",
       p.tags,
       p."imageUrl",
       p."likeCount",
       p."repostCount",
       p."replyCount",
       p."parentId",
       p."rootId",
       p."repostId",
       p."replyRestriction",
       p."isPinned",
       p."isHiddenByAuthor",
       p."isDraft",
       p."scheduledAt",
       p."deletedAt",
       u.id::text   AS author_id,
       u.name       AS author_name,
       u.username   AS author_username,
       u."logoUrl"  AS author_logo,
       u."isCertified" AS author_certified
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
WHERE p.id = $1
  AND p."deletedAt" IS NULL
`

type GetThoughtByIDRow struct {
	ID               string           `json:"id"`
	Content          string           `json:"content"`
	AuthorId         string           `json:"authorId"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	UpdatedAt        pgtype.Timestamp `json:"updatedAt"`
	Tags             []string         `json:"tags"`
	ImageUrl         pgtype.Text      `json:"imageUrl"`
	LikeCount        int32            `json:"likeCount"`
	RepostCount      int32            `json:"repostCount"`
	ReplyCount       int32            `json:"replyCount"`
	ParentId         pgtype.Text      `json:"parentId"`
	RootId           pgtype.Text      `json:"rootId"`
	RepostId         pgtype.Text      `json:"repostId"`
	ReplyRestriction string           `json:"replyRestriction"`
	IsPinned         bool             `json:"isPinned"`
	IsHiddenByAuthor bool             `json:"isHiddenByAuthor"`
	IsDraft          bool             `json:"isDraft"`
	ScheduledAt      pgtype.Timestamp `json:"scheduledAt"`
	DeletedAt        pgtype.Timestamp `json:"deletedAt"`
	AuthorID         string           `json:"author_id"`
	AuthorName       pgtype.Text      `json:"author_name"`
	AuthorUsername   pgtype.Text      `json:"author_username"`
	AuthorLogo       pgtype.Text      `json:"author_logo"`
	AuthorCertified  bool             `json:"author_certified"`
}

func (q *Queries) GetThoughtByID(ctx context.Context, id string) (GetThoughtByIDRow, error) {
	row := q.db.QueryRow(ctx, getThoughtByID, id)
	var i GetThoughtByIDRow
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tags,
		&i.ImageUrl,
		&i.LikeCount,
		&i.RepostCount,
		&i.ReplyCount,
		&i.ParentId,
		&i.RootId,
		&i.RepostId,
		&i.ReplyRestriction,
		&i.IsPinned,
		&i.IsHiddenByAuthor,
		&i.IsDraft,
		&i.ScheduledAt,
		&i.DeletedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorUsername,
		&i.AuthorLogo,
		&i.AuthorCertified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, name, "logoUrl", "isCertified", "isShadowbanned", "isSuspended", role
FROM "User"
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             string      `json:"id"`
	Username       pgtype.Text `json:"username"`
	Name           pgtype.Text `json:"name"`
	LogoUrl        pgtype.Text `json:"logoUrl"`
	IsCertified    bool        `json:"isCertified"`
	IsShadowbanned bool        `json:"isShadowbanned"`
	IsSuspended    bool        `json:"isSuspended"`
	Role           string      `json:"role"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.LogoUrl,
		&i.IsCertified,
		&i.IsShadowbanned,
		&i.IsSuspended,
		&i.Role,
	)
	return i, err
}

const incrementLikeCount = `-- name: IncrementLikeCount :exec
UPDATE "Post"
SET "likeCount" = "likeCount" + 1
WHERE id = $1
`

func (q *Queries) IncrementLikeCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementLikeCount, id)
	return err
}

const incrementReplyCount = `-- name: IncrementReplyCount :exec
UPDATE "Post"
SET "replyCount" = "replyCount" + 1
WHERE id = $1
`

func (q *Queries) IncrementReplyCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementReplyCount, id)
	return err
}

const incrementRepostCount = `-- name: IncrementRepostCount :exec
UPDATE "Post"
SET "repostCount" = "repostCount" + 1
WHERE id = $1
`

func (q *Queries) IncrementRepostCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementRepostCount, id)
	return err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO "BlockedUser" (id, "creatorId", "readerId")
VALUES (gen_random_uuid()::text, $1, $2)
`

type InsertBlockParams struct {
	CreatorId pgtype.UUID `json:"creatorId"`
	ReaderId  pgtype.UUID `json:"readerId"`
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock, arg.CreatorId, arg.ReaderId)
	return err
}

const insertLike = `-- name: InsertLike :one
INSERT INTO "Like" (id, "postId", "userId")
VALUES (gen_random_uuid()::text, $1, $2)
RETURNING id
`

type InsertLikeParams struct {
	PostId string      `json:"postId"`
	UserId pgtype.UUID `json:"userId"`
}

func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) (string, error) {
	row := q.db.QueryRow(ctx, insertLike, arg.PostId, arg.UserId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertMute = `-- name: InsertMute :exec
INSERT INTO "MutedUser" (id, "muterId", "mutedId")
VALUES (gen_random_uuid()::text, $1, $2)
`

type InsertMuteParams struct {
	MuterId pgtype.UUID `json:"muterId"`
	MutedId pgtype.UUID `json:"mutedId"`
}

func (q *Queries) InsertMute(ctx context.Context, arg InsertMuteParams) error {
	_, err := q.db.Exec(ctx, insertMute, arg.MuterId, arg.MutedId)
	return err
}

const insertPureRepost = `-- name: InsertPureRepost :one
INSERT INTO "Post" (id, "content", "authorId", "updatedAt", "repostId", "replyRestriction", "visibility", "contentVisibility", "isDraft", "likeCount", "repostCount", "replyCount")
VALUES (gen_random_uuid()::text, '', $1, now(), $2, 'everyone', 'public', 'PUBLIC', false, 0, 0, 0)
RETURNING id
`

type InsertPureRepostParams struct {
	AuthorId string      `json:"authorId"`
	RepostId pgtype.Text `json:"repostId"`
}

func (q *Queries) InsertPureRepost(ctx context.Context, arg InsertPureRepostParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPureRepost, arg.AuthorId, arg.RepostId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listLikesForPost = `-- name: ListLikesForPost :many
SELECT u.id::text     AS user_id,
       u.name         AS user_name,
       u.username     AS user_username,
       u."logoUrl"    AS user_logo,
       u."isCertified" AS user_certified,
       l."createdAt"  AS liked_at
FROM "Like" l
JOIN "User" u ON u.id = l."userId"
WHERE l."postId" = $1
ORDER BY l."createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListLikesForPostParams struct {
	PostId string `json:"postId"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListLikesForPostRow struct {
	UserID        string           `json:"user_id"`
	UserName      pgtype.Text      `json:"user_name"`
	UserUsername  pgtype.Text      `json:"user_username"`
	UserLogo      pgtype.Text      `json:"user_logo"`
	UserCertified bool             `json:"user_certified"`
	LikedAt       pgtype.Timestamp `json:"liked_at"`
}

func (q *Queries) ListLikesForPost(ctx context.Context, arg ListLikesForPostParams) ([]ListLikesForPostRow, error) {
	rows, err := q.db.Query(ctx, listLikesForPost, arg.PostId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLikesForPostRow{}
	for rows.Next() {
		var i ListLikesForPostRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.UserUsername,
			&i.UserLogo,
			&i.UserCertified,
			&i.LikedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotePostIDs = `-- name: ListQuotePostIDs :many
SELECT r.id
FROM "Post" r
WHERE r."repostId" = $1
  AND r."deletedAt" IS NULL
  AND r."isDraft" = false
  AND (r.content <> '' AND r.content <> ' ')
ORDER BY r."createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListQuotePostIDsParams struct {
	RepostId pgtype.Text `json:"repostId"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListQuotePostIDs(ctx context.Context, arg ListQuotePostIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listQuotePostIDs, arg.RepostId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepostsForPost = `-- name: ListRepostsForPost :many
SELECT u.id::text     AS user_id,
       u.name         AS user_name,
       u.username     AS user_username,
       u."logoUrl"    AS user_logo,
       u."isCertified" AS user_certified,
       r."createdAt"  AS reposted_at
FROM "Post" r
JOIN "User" u ON u.id = r."authorId"
WHERE r."repostId" = $1
  AND r."deletedAt" IS NULL
  AND (r.content = '' OR r.content = ' ')
ORDER BY r."createdAt" DESC
LIMIT $2 OFFSET $3
`

type ListRepostsForPostParams struct {
	RepostId pgtype.Text `json:"repostId"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListRepostsForPostRow struct {
	UserID        string           `json:"user_id"`
	UserName      pgtype.Text      `json:"user_name"`
	UserUsername  pgtype.Text      `json:"user_username"`
	UserLogo      pgtype.Text      `json:"user_logo"`
	UserCertified bool             `json:"user_certified"`
	RepostedAt    pgtype.Timestamp `json:"reposted_at"`
}

func (q *Queries) ListRepostsForPost(ctx context.Context, arg ListRepostsForPostParams) ([]ListRepostsForPostRow, error) {
	rows, err := q.db.Query(ctx, listRepostsForPost, arg.RepostId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepostsForPostRow{}
	for rows.Next() {
		var i ListRepostsForPostRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.UserUsername,
			&i.UserLogo,
			&i.UserCertified,
			&i.RepostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinPost = `-- name: PinPost :one
UPDATE "Post"
SET "isPinned" = true
WHERE id = $1 AND "authorId" = $2 AND "deletedAt" IS NULL
RETURNING "isPinned"
`

type PinPostParams struct {
	ID       string `json:"id"`
	AuthorId string `json:"authorId"`
}

func (q *Queries) PinPost(ctx context.Context, arg PinPostParams) (bool, error) {
	row := q.db.QueryRow(ctx, pinPost, arg.ID, arg.AuthorId)
	var isPinned bool
	err := row.Scan(&isPinned)
	return isPinned, err
}

const softDeletePost = `-- name: SoftDeletePost :one
UPDATE "Post"
SET "deletedAt" = now()
WHERE id = $1 AND "authorId" = $2 AND "deletedAt" IS NULL
RETURNING id
`

type SoftDeletePostParams struct {
	ID       string `json:"id"`
	AuthorId string `json:"authorId"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeletePost, arg.ID, arg.AuthorId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const unpinPost = `-- name: UnpinPost :one
UPDATE "Post"
SET "isPinned" = false
WHERE id = $1 AND "authorId" = $2
RETURNING "isPinned"
`

type UnpinPostParams struct {
	ID       string `json:"id"`
	AuthorId string `json:"authorId"`
}

func (q *Queries) UnpinPost(ctx context.Context, arg UnpinPostParams) (bool, error) {
	row := q.db.QueryRow(ctx, unpinPost, arg.ID, arg.AuthorId)
	var isPinned bool
	err := row.Scan(&isPinned)
	return isPinned, err
}
