// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRecommendation(ctx context.Context, arg AddRecommendationParams) (Recommendation, error)
	AdminDashboardCounts(ctx context.Context) (AdminDashboardCountsRow, error)
	ArchiveLegalDocumentVersion(ctx context.Context, id string) (LegalDocumentVersion, error)
	ArchivePublishedLegalVersions(ctx context.Context, arg ArchivePublishedLegalVersionsParams) error
	// Vrai si l'un des deux a bloqué l'autre (les deux sens).
	AreUsersBlocked(ctx context.Context, arg AreUsersBlockedParams) (bool, error)
	CheckArticleSlugExists(ctx context.Context, arg CheckArticleSlugExistsParams) (bool, error)
	CheckCategorySlugExists(ctx context.Context, arg CheckCategorySlugExistsParams) (bool, error)
	CheckMediaSlugExists(ctx context.Context, slug string) (bool, error)
	CheckSubdomainExists(ctx context.Context, subdomain pgtype.Text) (bool, error)
	// Réclamation atomique (QUEUED → PROCESSING) : plusieurs instances du worker
	// peuvent tourner sans envoyer deux fois le même email.
	ClaimLegalNoticeDeliveries(ctx context.Context, batchSize int32) ([]ClaimLegalNoticeDeliveriesRow, error)
	ClaimLegalReviewReminders(ctx context.Context, batchSize int32) ([]ClaimLegalReviewRemindersRow, error)
	ClearArticleEditorPicks(ctx context.Context) error
	ClearPinnedPosts(ctx context.Context, authorid string) error
	// Publier le brouillon d'une revue clôt la revue : la boucle est bouclée sans
	// qu'un humain ait à cocher quoi que ce soit en plus.
	CompleteLegalReviewsForVersion(ctx context.Context, versionID pgtype.Text) error
	CompleteOnboardingUser(ctx context.Context, arg CompleteOnboardingUserParams) error
	ConfirmSubscriberByToken(ctx context.Context, arg ConfirmSubscriberByTokenParams) (string, error)
	ConsumeOAuthAuthorizationCode(ctx context.Context, id string) error
	CookieConsentStats(ctx context.Context) (CookieConsentStatsRow, error)
	CountActiveOAuthTokens(ctx context.Context, userid string) (int64, error)
	CountAllNotificationDeliveries(ctx context.Context) (int64, error)
	CountArticleReleaseDeliveries(ctx context.Context, articleid string) (CountArticleReleaseDeliveriesRow, error)
	CountArticlesByPublication(ctx context.Context, publicationid string) (int32, error)
	// Compte des articles d'une publication (mêmes filtres que ListCreatorArticles).
	CountCreatorArticles(ctx context.Context, arg CountCreatorArticlesParams) (int64, error)
	CountDevtoolsArticles(ctx context.Context) (int64, error)
	CountDevtoolsLikes(ctx context.Context) (int64, error)
	CountDevtoolsSubscribers(ctx context.Context) (int64, error)
	CountDevtoolsThoughts(ctx context.Context) (int64, error)
	CountDevtoolsUsers(ctx context.Context) (int64, error)
	CountDueScheduledLegalVersions(ctx context.Context) (int64, error)
	CountFollowers(ctx context.Context, publicationid string) (int32, error)
	CountFollowing(ctx context.Context, readerid pgtype.UUID) (int32, error)
	CountHighlightUpvotes(ctx context.Context, highlightid string) (int32, error)
	// Utilisateurs actifs qui doivent encore accepter un document « à accepter »
	// dans sa version publiée courante.
	CountLegalConsentGaps(ctx context.Context) (CountLegalConsentGapsRow, error)
	CountLegalDocuments(ctx context.Context) (int64, error)
	CountLegalEligibleUsers(ctx context.Context) (CountLegalEligibleUsersRow, error)
	CountLegalNotices(ctx context.Context) (int64, error)
	CountMediaApiKeys(ctx context.Context, id string) (int32, error)
	CountMediaMembers(ctx context.Context, mediaid string) (int32, error)
	CountModerationReportsByStatus(ctx context.Context) ([]CountModerationReportsByStatusRow, error)
	CountNewsletterDeliveriesByIssue(ctx context.Context, issueid string) (CountNewsletterDeliveriesByIssueRow, error)
	// ── Notifications & livraisons ───────────────────────────────────────────────
	CountNotificationDeliveriesByStatus(ctx context.Context) ([]CountNotificationDeliveriesByStatusRow, error)
	CountOAuthClientsByOwner(ctx context.Context, owneruserid string) (int64, error)
	CountOptionVotes(ctx context.Context, optionid string) (int32, error)
	CountOptionVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountOptionVotesByIDsRow, error)
	CountPendingReportsByReporter(ctx context.Context, arg CountPendingReportsByReporterParams) (int64, error)
	CountPollVotes(ctx context.Context, pollid string) (int32, error)
	CountPollVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountPollVotesByIDsRow, error)
	CountPollVotesByPollID(ctx context.Context, pollid string) (int32, error)
	CountPureReposts(ctx context.Context, arg CountPureRepostsParams) (int32, error)
	CountReadingSessionsByArticleId(ctx context.Context, arg CountReadingSessionsByArticleIdParams) (int32, error)
	// Variante batch pour provenance globale (tous les articleIds du créateur).
	CountReadingSessionsByArticleIds(ctx context.Context, arg CountReadingSessionsByArticleIdsParams) ([]int32, error)
	CountRecommendationsByPublication(ctx context.Context, recommenderid string) (int64, error)
	CountSubscribersByPublication(ctx context.Context, publicationid string) (int64, error)
	// Nombre de conversations avec au moins un message non lu (badge tab).
	// Les messages que l'on a SOI-MÊME envoyés ne comptent jamais comme non-lus ;
	// COUNT(DISTINCT conversation) : plusieurs messages ≠ plusieurs badges.
	CountUnreadConversations(ctx context.Context, userid pgtype.UUID) (int32, error)
	CreateAnnotationComment(ctx context.Context, arg CreateAnnotationCommentParams) (string, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (string, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (string, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// Les colonnes canoniques (offsets en code points dans le document canonique
	// de l'article + empreinte du contenu) sont ADDITIVES : NULL tant qu'une
	// ancre n'a pas pu être résolue (données héritées ou contenu changé).
	CreateHighlight(ctx context.Context, arg CreateHighlightParams) (string, error)
	CreateMedia(ctx context.Context, publicationid string) (string, error)
	// Nouvel asset orphelin (DRAFT_ORPHAN, purgé dans 3 jours si non attaché).
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error)
	CreateMediaMember(ctx context.Context, arg CreateMediaMemberParams) error
	CreateMediaPublication(ctx context.Context, arg CreateMediaPublicationParams) (string, error)
	CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (string, error)
	// =====================================================================
	// 📬 Newsletters créateurs (NewsletterIssue / NewsletterDelivery).
	// =====================================================================
	CreateNewsletterIssue(ctx context.Context, arg CreateNewsletterIssueParams) (NewsletterIssue, error)
	CreatePersonalPublication(ctx context.Context, arg CreatePersonalPublicationParams) (string, error)
	CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (string, error)
	CreateStarterPack(ctx context.Context, arg CreateStarterPackParams) (StarterPack, error)
	CreateThought(ctx context.Context, arg CreateThoughtParams) (CreateThoughtRow, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (string, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CreateWebhookRow, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (string, error)
	DeactivateSubscriber(ctx context.Context, arg DeactivateSubscriberParams) (string, error)
	DecrementLikeCount(ctx context.Context, id string) error
	DecrementReplyCount(ctx context.Context, id string) error
	DecrementRepostCount(ctx context.Context, id string) error
	DeleteAnnotationComment(ctx context.Context, arg DeleteAnnotationCommentParams) (int64, error)
	DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error
	DeleteArticle(ctx context.Context, id string) error
	DeleteArticleComment(ctx context.Context, id string) error
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error
	DeleteCategory(ctx context.Context, id string) error
	DeleteExpiredOAuthArtifacts(ctx context.Context) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteFollowNotification(ctx context.Context, arg DeleteFollowNotificationParams) error
	DeleteHighlight(ctx context.Context, arg DeleteHighlightParams) (int64, error)
	DeleteHighlightUpvote(ctx context.Context, arg DeleteHighlightUpvoteParams) error
	DeleteLegalDocument(ctx context.Context, id string) error
	DeleteLegalDocumentVersion(ctx context.Context, id string) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeleteLikeNotification(ctx context.Context, arg DeleteLikeNotificationParams) error
	DeleteMediaApiKey(ctx context.Context, arg DeleteMediaApiKeyParams) (int64, error)
	DeleteMediaMember(ctx context.Context, arg DeleteMediaMemberParams) error
	DeleteMute(ctx context.Context, arg DeleteMuteParams) error
	DeleteNavigationItems(ctx context.Context, publicationid string) error
	DeleteNewsletterIssueDraft(ctx context.Context, id string) error
	DeleteOAuthClient(ctx context.Context, arg DeleteOAuthClientParams) error
	DeletePollVote(ctx context.Context, arg DeletePollVoteParams) error
	DeletePromo(ctx context.Context, id string) error
	DeletePureReposts(ctx context.Context, arg DeletePureRepostsParams) error
	DeleteRepostNotification(ctx context.Context, arg DeleteRepostNotificationParams) error
	DeleteRevokedOAuthTokens(ctx context.Context) error
	DeleteSocialLinks(ctx context.Context, publicationid string) error
	DeleteSystemConfig(ctx context.Context, key string) error
	DeleteTrend(ctx context.Context, id string) error
	DeleteWebhook(ctx context.Context, id string) error
	DismissLegalReview(ctx context.Context, arg DismissLegalReviewParams) (LegalReview, error)
	ExistsUnreadCommentNotification(ctx context.Context, arg ExistsUnreadCommentNotificationParams) (int32, error)
	ExistsUnreadFollowNotification(ctx context.Context, arg ExistsUnreadFollowNotificationParams) (int32, error)
	ExistsUnreadLikeNotification(ctx context.Context, arg ExistsUnreadLikeNotificationParams) (int32, error)
	ExistsUnreadMentionNotification(ctx context.Context, arg ExistsUnreadMentionNotificationParams) (int32, error)
	ExistsUnreadReplyNotification(ctx context.Context, arg ExistsUnreadReplyNotificationParams) (int32, error)
	ExistsUnreadRepostNotification(ctx context.Context, arg ExistsUnreadRepostNotificationParams) (int32, error)
	FailArticleImportJob(ctx context.Context, id string) error
	FindFollowingFeed(ctx context.Context, arg FindFollowingFeedParams) ([]FindFollowingFeedRow, error)
	FindPostsByAuthor(ctx context.Context, arg FindPostsByAuthorParams) ([]FindPostsByAuthorRow, error)
	// Articles publiés classés par similarité cosinus avec un vecteur donné,
	// en excluant l'article source. Requête ANN via l'index HNSW.
	FindSimilarArticles(ctx context.Context, arg FindSimilarArticlesParams) ([]FindSimilarArticlesRow, error)
	FindTrending(ctx context.Context, arg FindTrendingParams) ([]FindTrendingRow, error)
	FinishArticleImportJob(ctx context.Context, arg FinishArticleImportJobParams) error
	FinishNewsletterIssue(ctx context.Context, arg FinishNewsletterIssueParams) (string, error)
	FollowPublications(ctx context.Context, arg FollowPublicationsParams) (int32, error)
	GetActiveSubscribersByPublication(ctx context.Context, arg GetActiveSubscribersByPublicationParams) ([]GetActiveSubscribersByPublicationRow, error)
	GetActiveSubscriptionForReply(ctx context.Context, arg GetActiveSubscriptionForReplyParams) (int32, error)
	GetActiveWebhooksByPublication(ctx context.Context, arg GetActiveWebhooksByPublicationParams) ([]GetActiveWebhooksByPublicationRow, error)
	GetAdminUser(ctx context.Context, id string) (GetAdminUserRow, error)
	GetAdminUserRevenue(ctx context.Context, userid pgtype.UUID) (int64, error)
	// Admin — console superadmin (modération & management).
	// Rôle : réservé au superadmin (vérifié côté service/handler).
	GetAdminUserRole(ctx context.Context, id string) (string, error)
	// API Créateur (migration depuis Hono apps/api) : clés API, catégories, users, follows, bookmarks.
	GetApiKeyByHash(ctx context.Context, keyhash string) (GetApiKeyByHashRow, error)
	GetArticleAuthor(ctx context.Context, id string) (string, error)
	GetArticleByID(ctx context.Context, id string) (GetArticleByIDRow, error)
	GetArticleBySlug(ctx context.Context, arg GetArticleBySlugParams) (GetArticleBySlugRow, error)
	// Lecture publique par slug SEUL (premier article publié) — parité avec
	// findFirstBySlug Prisma de la page autonome /article/[slug] du reader core.
	// Résout aussi les slugs personnalisés par auteur (ArticleSlug).
	GetArticleBySlugAny(ctx context.Context, slug string) (GetArticleBySlugAnyRow, error)
	GetArticleCommentAuthor(ctx context.Context, id string) (string, error)
	GetArticleCommentsConfig(ctx context.Context, id string) (GetArticleCommentsConfigRow, error)
	// Retourne le vecteur d'un article sous forme texte ('' si absent). Le scan
	// d'un type vector NULL n'est pas géré par pgvector-go → on cast en texte.
	GetArticleEmbeddingText(ctx context.Context, id string) (string, error)
	// Collaborations / attributions (migration de studio advanced/actions.ts).
	GetArticleForCollaboration(ctx context.Context, id string) (GetArticleForCollaborationRow, error)
	GetArticleForSearch(ctx context.Context, id string) (GetArticleForSearchRow, error)
	// Dédoublonnage import RSS : un article existe déjà si publicationId + slug matchent.
	GetArticleIdByPublicationAndSlug(ctx context.Context, arg GetArticleIdByPublicationAndSlugParams) (string, error)
	GetArticleImportJob(ctx context.Context, arg GetArticleImportJobParams) (GetArticleImportJobRow, error)
	GetArticleImportJobByID(ctx context.Context, id string) (GetArticleImportJobByIDRow, error)
	GetArticleReleaseInfo(ctx context.Context, id string) (GetArticleReleaseInfoRow, error)
	GetAttachmentsByIDs(ctx context.Context, dollar_1 []string) ([]GetAttachmentsByIDsRow, error)
	GetAudienceSummary(ctx context.Context, publicationid string) (GetAudienceSummaryRow, error)
	GetCanonicalThoughtID(ctx context.Context, id string) (string, error)
	// Catégories d'articles (éditeur dashboard).
	GetCategoryByID(ctx context.Context, id string) (Category, error)
	GetCollaborationRequestByID(ctx context.Context, id string) (GetCollaborationRequestByIDRow, error)
	GetCommentParentAuthor(ctx context.Context, id string) (string, error)
	GetCommentPrefs(ctx context.Context, userid pgtype.UUID) (GetCommentPrefsRow, error)
	GetCommentWithAuthor(ctx context.Context, id string) (GetCommentWithAuthorRow, error)
	GetConversationByDirectKey(ctx context.Context, directkey pgtype.Text) (string, error)
	// Détail d'une conversation (vérifie l'appartenance + résout l'autre participant).
	GetConversationForUser(ctx context.Context, arg GetConversationForUserParams) (GetConversationForUserRow, error)
	// Lecture d'un article PUBLIÉ d'une publication au format contrat créateurs
	// (clé API → publication du créateur), catégorie embarquée.
	GetCreatorArticleBySlug(ctx context.Context, arg GetCreatorArticleBySlugParams) (GetCreatorArticleBySlugRow, error)
	GetExistingBlock(ctx context.Context, arg GetExistingBlockParams) (int32, error)
	GetExistingBookmark(ctx context.Context, arg GetExistingBookmarkParams) (int32, error)
	GetExistingFollow(ctx context.Context, arg GetExistingFollowParams) (int32, error)
	GetExistingLike(ctx context.Context, arg GetExistingLikeParams) (int32, error)
	GetExistingMute(ctx context.Context, arg GetExistingMuteParams) (int32, error)
	GetFollowForReply(ctx context.Context, arg GetFollowForReplyParams) (int32, error)
	GetFollowPrefs(ctx context.Context, userid pgtype.UUID) (GetFollowPrefsRow, error)
	GetFollowedPersonalPublicationOwnerIDs(ctx context.Context, readerid pgtype.UUID) ([]string, error)
	GetFollowingStateByAuthorIDs(ctx context.Context, arg GetFollowingStateByAuthorIDsParams) ([]GetFollowingStateByAuthorIDsRow, error)
	GetFreeSubscriberCount(ctx context.Context, publicationid string) (int32, error)
	// Highlights & annotations : surlignage de passages d'articles, notes,
	// visibilité publique, upvotes et commentaires d'annotation.
	// Tables : Highlight, AnnotationComment, AnnotationUpvote.
	GetHighlightByID(ctx context.Context, id string) (GetHighlightByIDRow, error)
	GetLatestLegalConsentExport(ctx context.Context) (LegalConsentExport, error)
	GetLegalAcceptance(ctx context.Context, arg GetLegalAcceptanceParams) (LegalAcceptance, error)
	// ─── Rappels aux superadmins ─────────────────────────────────────────
	// L'email de l'auteur d'un export : le registre doit dire QUI a produit la
	// pièce, pas seulement quel compte technique.
	GetLegalActorEmail(ctx context.Context, id pgtype.UUID) (string, error)
	// Couverture du consentement par audience, pour repérer un segment oublié.
	GetLegalConsentCoverageByAudience(ctx context.Context) ([]GetLegalConsentCoverageByAudienceRow, error)
	GetLegalDocumentByID(ctx context.Context, id string) (LegalDocument, error)
	GetLegalDocumentBySlug(ctx context.Context, slug string) (LegalDocument, error)
	GetLegalDocumentBySlugAdmin(ctx context.Context, slug string) (LegalDocument, error)
	GetLegalDocumentVersion(ctx context.Context, id string) (LegalDocumentVersion, error)
	GetLegalNoticeEmailContext(ctx context.Context, arg GetLegalNoticeEmailContextParams) (GetLegalNoticeEmailContextRow, error)
	GetLegalReviewReminderContext(ctx context.Context, id string) (GetLegalReviewReminderContextRow, error)
	GetLikePrefs(ctx context.Context, userid pgtype.UUID) (GetLikePrefsRow, error)
	GetMediaApiKeyByID(ctx context.Context, arg GetMediaApiKeyByIDParams) (GetMediaApiKeyByIDRow, error)
	// Dédoublonnage CAS : cherche un asset existant par hash SHA-256.
	GetMediaAssetBySha256(ctx context.Context, sha256 string) (MediaAsset, error)
	// Administration Média (création, membres, invitations, réglages) — migration dashboard → Go.
	GetMediaMemberByID(ctx context.Context, arg GetMediaMemberByIDParams) (GetMediaMemberByIDRow, error)
	// RBAC Média (rôles + permissions) — partagé par settings, articles et media.
	GetMediaMemberContext(ctx context.Context, arg GetMediaMemberContextParams) (GetMediaMemberContextRow, error)
	GetMediaOwnerForCredit(ctx context.Context, publicationid string) (GetMediaOwnerForCreditRow, error)
	GetMediaRoleForUser(ctx context.Context, arg GetMediaRoleForUserParams) (string, error)
	GetMediaWithPublication(ctx context.Context, id string) (GetMediaWithPublicationRow, error)
	GetModerationReport(ctx context.Context, id string) (ModerationReport, error)
	GetNewsletterIssue(ctx context.Context, id string) (NewsletterIssue, error)
	GetNewsletterIssueWithPublication(ctx context.Context, id string) (GetNewsletterIssueWithPublicationRow, error)
	GetNotificationPreferences(ctx context.Context, userid pgtype.UUID) (GetNotificationPreferencesRow, error)
	// Centre de notifications : liste groupée, non-lus, lecture, préférences.
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error)
	GetOAuthAuthorizationCodeByHash(ctx context.Context, codehash string) (OAuthAuthorizationCode, error)
	// OAuth 2.1 / OIDC — clients, codes, tokens, consentement, quotas.
	GetOAuthClientByClientId(ctx context.Context, clientid string) (GetOAuthClientByClientIdRow, error)
	GetOAuthClientByID(ctx context.Context, id string) (GetOAuthClientByIDRow, error)
	GetOAuthConsent(ctx context.Context, arg GetOAuthConsentParams) (OAuthConsent, error)
	GetOAuthTokenByAccessHash(ctx context.Context, accesstokenhash string) (GetOAuthTokenByAccessHashRow, error)
	GetOAuthTokenByRefreshHash(ctx context.Context, refreshtokenhash pgtype.Text) (GetOAuthTokenByRefreshHashRow, error)
	GetOAuthUserClaims(ctx context.Context, id string) (GetOAuthUserClaimsRow, error)
	// =====================================================================
	// ✅ Double opt-in — email de confirmation des inscriptions publiques
	// =====================================================================
	GetPendingConfirmation(ctx context.Context, arg GetPendingConfirmationParams) (GetPendingConfirmationRow, error)
	GetPersonalOwnerForCredit(ctx context.Context, publicationid pgtype.Text) (GetPersonalOwnerForCreditRow, error)
	GetPersonalPublicationByUserID(ctx context.Context, id string) (pgtype.Text, error)
	GetPersonalPublicationForUser(ctx context.Context, id string) (GetPersonalPublicationForUserRow, error)
	GetPersonalPublicationID(ctx context.Context, id string) (pgtype.Text, error)
	// Polls, votes, pièces jointes
	GetPollByThoughtID(ctx context.Context, thoughtid string) (GetPollByThoughtIDRow, error)
	GetPollOptionByID(ctx context.Context, id string) (PollOption, error)
	GetPollOptions(ctx context.Context, pollid string) ([]PollOption, error)
	GetPollOptionsByIDs(ctx context.Context, dollar_1 []string) ([]PollOption, error)
	GetPollsByIDs(ctx context.Context, dollar_1 []string) ([]GetPollsByIDsRow, error)
	GetPostAuthor(ctx context.Context, id string) (string, error)
	// Retourne le contenu + tags + auteur d'une pensée pour calculer son vecteur.
	GetPostForEmbedding(ctx context.Context, id string) (GetPostForEmbeddingRow, error)
	GetPostThread(ctx context.Context, arg GetPostThreadParams) ([]GetPostThreadRow, error)
	GetPostsByIDs(ctx context.Context, arg GetPostsByIDsParams) ([]GetPostsByIDsRow, error)
	GetPremiumActiveSubscribers(ctx context.Context, publicationid string) ([]GetPremiumActiveSubscribersRow, error)
	GetPublicationByID(ctx context.Context, id string) (string, error)
	GetPublicationBySlugOrSubdomain(ctx context.Context, lower string) (GetPublicationBySlugOrSubdomainRow, error)
	// Identité par défaut de la publication (pré-remplissage du formulaire
	// email du studio) + réglages email stockés.
	GetPublicationEmailDefaults(ctx context.Context, id string) (GetPublicationEmailDefaultsRow, error)
	// Identité complète de la publication pour l'envoi d'un email de test
	// (POST /v1/settings/email/test) : mêmes colonnes que
	// GetSubscriberEmailDefaults + réglages stockés rendus par le moteur.
	GetPublicationForEmailTest(ctx context.Context, id string) (GetPublicationForEmailTestRow, error)
	// Page settings créateur (parité prisma.publication.findUnique include dans
	// apps/studio/src/app/(creator)/settings/page.tsx).
	GetPublicationForSettings(ctx context.Context, id string) (GetPublicationForSettingsRow, error)
	GetPublicationMetadataByID(ctx context.Context, id string) (GetPublicationMetadataByIDRow, error)
	GetPublicationOwner(ctx context.Context, id string) (string, error)
	GetPublicationTypeByID(ctx context.Context, id string) (GetPublicationTypeByIDRow, error)
	GetPublicationUmamiWebsiteId(ctx context.Context, id string) (pgtype.Text, error)
	// Contenu complet d'un document publié (markdown).
	GetPublishedLegalDocument(ctx context.Context, arg GetPublishedLegalDocumentParams) (GetPublishedLegalDocumentRow, error)
	GetQuotedArticlesByIDs(ctx context.Context, ids []string) ([]GetQuotedArticlesByIDsRow, error)
	GetReadingSessionDailySeries(ctx context.Context, arg GetReadingSessionDailySeriesParams) ([]GetReadingSessionDailySeriesRow, error)
	GetRecentArticlesForAnalytics(ctx context.Context, arg GetRecentArticlesForAnalyticsParams) ([]GetRecentArticlesForAnalyticsRow, error)
	GetRecentThoughtsForAnalytics(ctx context.Context, arg GetRecentThoughtsForAnalyticsParams) ([]GetRecentThoughtsForAnalyticsRow, error)
	// Version publiée de référence d'un document (FR en priorité : c'est le texte
	// qui fait foi). Sert de base au brouillon de revue.
	GetReferencePublishedVersion(ctx context.Context, documentID string) (LegalDocumentVersion, error)
	GetRepliesForThought(ctx context.Context, arg GetRepliesForThoughtParams) ([]GetRepliesForThoughtRow, error)
	GetReplyIDsForThought(ctx context.Context, parentid pgtype.Text) ([]string, error)
	// Notifications REPLY / MENTION
	GetReplyPrefs(ctx context.Context, userid pgtype.UUID) (GetReplyPrefsRow, error)
	GetStarterPackByID(ctx context.Context, id string) (GetStarterPackByIDRow, error)
	// Contexte complet pour les emails transactionnels (bienvenue) :
	// locale de l'abonné + personnalisation de la publication.
	GetSubscriberEmailContext(ctx context.Context, arg GetSubscriberEmailContextParams) (GetSubscriberEmailContextRow, error)
	// Identité d'une publication pour la prévisualisation des emails
	// transactionnels (POST /v1/settings/email/preview) : mêmes colonnes que
	// GetSubscriberEmailContext (newsletter.sql) sans ligne Subscriber — la
	// prévisualisation ne suppose aucun abonné réel.
	GetSubscriberEmailDefaults(ctx context.Context, id string) (GetSubscriberEmailDefaultsRow, error)
	GetSubscriberEntitlement(ctx context.Context, arg GetSubscriberEntitlementParams) (GetSubscriberEntitlementRow, error)
	GetSubscriberStatsByPublication(ctx context.Context, publicationid string) (GetSubscriberStatsByPublicationRow, error)
	GetSystemConfigsByKeys(ctx context.Context, dollar_1 []string) ([]SystemConfig, error)
	GetThoughtByID(ctx context.Context, id string) (GetThoughtByIDRow, error)
	// Threadgates & réponses
	GetThoughtReplyGate(ctx context.Context, id string) (GetThoughtReplyGateRow, error)
	// Racine du fil d'une pensée : la pensée de base à laquelle une réponse
	// doit être rattachée (rootId de la chaîne, sinon son id canonique).
	GetThreadRootID(ctx context.Context, id string) (string, error)
	GetUnreadCount(ctx context.Context, recipientid pgtype.UUID) (int32, error)
	GetUserApiAccessStatus(ctx context.Context, id string) (string, error)
	GetUserApiGrants(ctx context.Context, id string) ([]string, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByIDFull(ctx context.Context, id string) (GetUserByIDFullRow, error)
	// Profil créateur, onboarding, sous-domaine, liens, clés API (migration dashboard → Go).
	GetUserForSettings(ctx context.Context, id string) (GetUserForSettingsRow, error)
	GetUserIdentity(ctx context.Context, id string) (GetUserIdentityRow, error)
	GetUserMediaMemberships(ctx context.Context, userid pgtype.UUID) ([]GetUserMediaMembershipsRow, error)
	GetUserPersonalPublication(ctx context.Context, id string) (pgtype.Text, error)
	GetUserPollVote(ctx context.Context, arg GetUserPollVoteParams) (string, error)
	GetUserPronouns(ctx context.Context, id string) (pgtype.Text, error)
	GetUserPublicationID(ctx context.Context, id string) (string, error)
	// DevTools — inspecteur de données (panneau dev-only des apps).
	// Rôle : lecture seule, réservé au superadmin (vérifié côté handler).
	GetUserRole(ctx context.Context, id string) (string, error)
	GetUserUsername(ctx context.Context, id string) (pgtype.Text, error)
	GetUserVoteForPoll(ctx context.Context, arg GetUserVoteForPollParams) (string, error)
	GetUserVotesByIDs(ctx context.Context, arg GetUserVotesByIDsParams) ([]GetUserVotesByIDsRow, error)
	GetUserWithCollabPrefsByEmail(ctx context.Context, email string) (GetUserWithCollabPrefsByEmailRow, error)
	GetUserWithCollabPrefsByID(ctx context.Context, id string) (GetUserWithCollabPrefsByIDRow, error)
	GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]GetUsersByUsernamesRow, error)
	GetWebhook(ctx context.Context, id string) (Webhook, error)
	GroupByHostname(ctx context.Context, arg GroupByHostnameParams) ([]GroupByHostnameRow, error)
	GroupByReferrerUsername(ctx context.Context, arg GroupByReferrerUsernameParams) ([]GroupByReferrerUsernameRow, error)
	GroupReadingSessionsByArticleId(ctx context.Context, arg GroupReadingSessionsByArticleIdParams) ([]GroupReadingSessionsByArticleIdRow, error)
	// Analytics ReadingSession — migration Prisma → Go (sqlc + raw SQL fallback).
	// Remplace :
	//   prisma.readingSession.groupBy { by: ['source'|'hostname'|'referrerUsername'|'articleId'] }
	//   prisma.$queryRawUnsafe `SELECT to_char(date_trunc('day', "createdAt")...)`
	//   prisma.readingSession.count
	//   prisma.user.groupBy (demographie) — voir analytics_demographics.sql si besoin
	//   prisma.article.findMany + attributions — voir ListAttributedArticleIDs ci-dessous
	GroupReadingSessionsBySource(ctx context.Context, arg GroupReadingSessionsBySourceParams) ([]GroupReadingSessionsBySourceRow, error)
	GroupUsersByAgeRange(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByAgeRangeRow, error)
	GroupUsersByCountry(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByCountryRow, error)
	GroupUsersByGender(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByGenderRow, error)
	GroupUsersByLanguage(ctx context.Context, dollar_1 []pgtype.UUID) ([]GroupUsersByLanguageRow, error)
	HideArticleByModerator(ctx context.Context, id string) error
	HidePostByAuthor(ctx context.Context, arg HidePostByAuthorParams) (bool, error)
	HidePostByModerator(ctx context.Context, id string) error
	IncrementLikeCount(ctx context.Context, id string) error
	IncrementReplyCount(ctx context.Context, id string) error
	IncrementRepostCount(ctx context.Context, id string) error
	IncrementWalletBalance(ctx context.Context, arg IncrementWalletBalanceParams) error
	// ── Journal d'audit superadmin ──────────────────────────────────────────────
	// metadata est passé en texte puis casté en jsonb : le pool API force
	// QueryExecModeExec (PgBouncer), où pgx encoderait []byte en bytea → 22P02.
	InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error
	InsertArticleComment(ctx context.Context, arg InsertArticleCommentParams) (InsertArticleCommentRow, error)
	// Notification in-app (jamais perdue) : dédup par (recipient, sender, type,
	// articleId, non-lue) + pas d'auto-notification. Casts explicites : évite
	// l'ambiguïté uuid/text en protocole étendu (operator does not exist).
	InsertArticleContributorNotification(ctx context.Context, arg InsertArticleContributorNotificationParams) error
	// Import bulk d'articles — jobs asynq + rapports d'erreurs.
	InsertArticleImportJob(ctx context.Context, arg InsertArticleImportJobParams) (string, error)
	InsertArticleReleaseDeliveries(ctx context.Context, arg InsertArticleReleaseDeliveriesParams) error
	InsertBlock(ctx context.Context, arg InsertBlockParams) error
	InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error
	InsertCommentNotification(ctx context.Context, arg InsertCommentNotificationParams) error
	// ─── Consentement traceurs (journal serveur) ─────────────────────────
	// Journal append-only : un changement de choix ajoute une ligne, on n'écrase
	// jamais une preuve. `consent_id` est l'identifiant que le navigateur conserve
	// pour corréler ses choix successifs.
	InsertCookieConsentRecord(ctx context.Context, arg InsertCookieConsentRecordParams) (InsertCookieConsentRecordRow, error)
	// Messagerie directe : conversations (tranche 1 — direct à 2 participants).
	// Tables : Conversation, ConversationMember.
	// La paire (conversationId, userId) est la clé de ConversationMember : chaque
	// membre a son lastReadAt. directKey = « minId:maxId » triés (une seule
	// conversation par paire, création atomique via ON CONFLICT).
	// Crée la conversation directe si elle n'existe pas (idempotent).
	InsertDirectConversation(ctx context.Context, directkey pgtype.Text) (string, error)
	InsertFollow(ctx context.Context, arg InsertFollowParams) error
	InsertFollowNotification(ctx context.Context, arg InsertFollowNotificationParams) error
	InsertLegalConsentExport(ctx context.Context, arg InsertLegalConsentExportParams) (LegalConsentExport, error)
	InsertLegalDocument(ctx context.Context, arg InsertLegalDocumentParams) (LegalDocument, error)
	InsertLegalDocumentVersion(ctx context.Context, arg InsertLegalDocumentVersionParams) (LegalDocumentVersion, error)
	// ─── Avis de nouvelle version (outbox email) ─────────────────────────
	// Un avis par version publiée. ON CONFLICT revoie la ligne existante pour que
	// le service soit idempotent sans avoir à gérer un cas d'erreur particulier.
	InsertLegalNotice(ctx context.Context, arg InsertLegalNoticeParams) (LegalNotice, error)
	InsertLegalNoticeDelivery(ctx context.Context, arg InsertLegalNoticeDeliveryParams) error
	// Le nombre de lignes réellement insérées compte : un rappel déjà émis n'est
	// pas un rappel émis, et le rapport du cycle doit le dire honnêtement.
	InsertLegalReviewReminder(ctx context.Context, arg InsertLegalReviewReminderParams) (int64, error)
	InsertLike(ctx context.Context, arg InsertLikeParams) (string, error)
	InsertLikeNotification(ctx context.Context, arg InsertLikeNotificationParams) error
	InsertMediaApiKey(ctx context.Context, arg InsertMediaApiKeyParams) error
	InsertMediaArticlePublishedFanout(ctx context.Context, arg InsertMediaArticlePublishedFanoutParams) error
	InsertMediaArticleSubmittedFanout(ctx context.Context, arg InsertMediaArticleSubmittedFanoutParams) error
	// metadata est passé en texte puis casté en jsonb : le pool API force
	// QueryExecModeExec (PgBouncer), où pgx encoderait []byte en bytea → 22P02.
	InsertMediaAuditLog(ctx context.Context, arg InsertMediaAuditLogParams) error
	InsertMediaInviteNotification(ctx context.Context, arg InsertMediaInviteNotificationParams) error
	InsertMediaMemberJoinedNotification(ctx context.Context, arg InsertMediaMemberJoinedNotificationParams) error
	InsertMentionNotification(ctx context.Context, arg InsertMentionNotificationParams) error
	// Messagerie directe : messages (tranche 1).
	// Table : Message. Pagination arrière par curseur createdAt (exclusif),
	// plus récupération incrémentale des nouveaux messages pour le polling.
	InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error)
	InsertMute(ctx context.Context, arg InsertMuteParams) error
	InsertNavigationItem(ctx context.Context, arg InsertNavigationItemParams) error
	InsertNewsletterDeliveries(ctx context.Context, arg InsertNewsletterDeliveriesParams) error
	InsertOAuthAuthorizationCode(ctx context.Context, arg InsertOAuthAuthorizationCodeParams) error
	InsertOAuthClient(ctx context.Context, arg InsertOAuthClientParams) error
	InsertOAuthToken(ctx context.Context, arg InsertOAuthTokenParams) error
	// Vote (idempotent : ON CONFLICT DO UPDATE pour changer d'option).
	InsertPollVote(ctx context.Context, arg InsertPollVoteParams) (string, error)
	InsertPureRepost(ctx context.Context, arg InsertPureRepostParams) (string, error)
	InsertReplyNotification(ctx context.Context, arg InsertReplyNotificationParams) error
	InsertRepostNotification(ctx context.Context, arg InsertRepostNotificationParams) error
	InsertSocialLink(ctx context.Context, arg InsertSocialLinkParams) error
	InsertStarterPackItem(ctx context.Context, arg InsertStarterPackItemParams) error
	InsertWebhookDeliveryResult(ctx context.Context, arg InsertWebhookDeliveryResultParams) error
	IsActiveMediaMember(ctx context.Context, arg IsActiveMediaMemberParams) (bool, error)
	// Preuve d'acceptation agrégée par document : combien d'utilisateurs ont
	// accepté la version publiée courante (et combien ne l'ont pas encore fait).
	LegalAcceptanceStats(ctx context.Context) ([]LegalAcceptanceStatsRow, error)
	LinkUserPublication(ctx context.Context, arg LinkUserPublicationParams) error
	// ── Demandes d'accès API ─────────────────────────────────────────────────────
	ListAdminApiApplicants(ctx context.Context) ([]ListAdminApiApplicantsRow, error)
	// ── Widgets & Tendances ──────────────────────────────────────────────────────
	ListAdminArticles(ctx context.Context) ([]ListAdminArticlesRow, error)
	ListAdminAuditLogs(ctx context.Context, limit int32) ([]ListAdminAuditLogsRow, error)
	// ── OAuth ────────────────────────────────────────────────────────────────────
	ListAdminOAuthClients(ctx context.Context) ([]ListAdminOAuthClientsRow, error)
	ListAdminPromos(ctx context.Context) ([]PartnerPromo, error)
	ListAdminTrends(ctx context.Context) ([]Trend, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	// Commentaires d'un surlignage, avec auteur.
	ListAnnotationComments(ctx context.Context, highlightid string) ([]ListAnnotationCommentsRow, error)
	ListApiKeys(ctx context.Context, userid pgtype.UUID) ([]ListApiKeysRow, error)
	ListArticleComments(ctx context.Context, articleid string) ([]ListArticleCommentsRow, error)
	ListArticleImportJobs(ctx context.Context, arg ListArticleImportJobsParams) ([]ListArticleImportJobsRow, error)
	ListArticleSlugs(ctx context.Context, articleid string) ([]string, error)
	ListArticlesForSettings(ctx context.Context, publicationid string) ([]ListArticlesForSettingsRow, error)
	ListArticlesWithCategory(ctx context.Context, arg ListArticlesWithCategoryParams) ([]ListArticlesWithCategoryRow, error)
	// Articles attribués à un créateur : publication directe OU co-signés via ArticleAttribution ACCEPTED + visible.
	// Miroir de prisma.article.findMany { OR: [{publicationId}, {attributions: {some: {userId, consentStatus, isVisible}}}] } où published = true.
	ListAttributedArticleIDs(ctx context.Context, arg ListAttributedArticleIDsParams) ([]string, error)
	// Articles sauvegardés (bookmarks) d'un lecteur, avec titre/slug/publication
	// et la date de sauvegarde — pour la bibliothèque mobile.
	ListBookmarksByReader(ctx context.Context, arg ListBookmarksByReaderParams) ([]ListBookmarksByReaderRow, error)
	ListCategoriesByPublication(ctx context.Context, publicationid string) ([]ListCategoriesByPublicationRow, error)
	ListCategoriesForPublication(ctx context.Context, publicationid string) ([]ListCategoriesForPublicationRow, error)
	// Conversations de l'utilisateur (directes : un seul autre participant),
	// avec le dernier message et le nombre de non-lus, triées par activité.
	ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]ListConversationsForUserRow, error)
	// Journal des choix de traceurs. Le consent_id est un identifiant aléatoire de
	// navigateur, pas une personne : il permet de reconstituer une suite de choix.
	ListCookieConsentForExport(ctx context.Context, arg ListCookieConsentForExportParams) ([]CookieConsentRecord, error)
	ListCookieConsentRecords(ctx context.Context, arg ListCookieConsentRecordsParams) ([]ListCookieConsentRecordsRow, error)
	// Liste des articles d'une publication au format contrat créateurs (Hono) :
	// filtres `published` (défaut true) et `category` (slug), catégorie embarquée.
	ListCreatorArticles(ctx context.Context, arg ListCreatorArticlesParams) ([]ListCreatorArticlesRow, error)
	ListDevtoolsUsers(ctx context.Context) ([]ListDevtoolsUsersRow, error)
	// Abonnés d'une publication (profil), paginés — avec état follow du viewer.
	ListFollowersByPublication(ctx context.Context, arg ListFollowersByPublicationParams) ([]ListFollowersByPublicationRow, error)
	// Abonnements d'un utilisateur (profil), résolus vers les propriétaires des
	// publications suivies (PERSONAL/MEDIA), paginés — avec état follow du viewer.
	ListFollowingByUser(ctx context.Context, arg ListFollowingByUserParams) ([]ListFollowingByUserRow, error)
	// Surlignages d'un article : publics + les siens (privés) + état upvote du viewer.
	ListHighlightsByArticle(ctx context.Context, arg ListHighlightsByArticleParams) ([]ListHighlightsByArticleRow, error)
	ListLegalAcceptancesAdmin(ctx context.Context, arg ListLegalAcceptancesAdminParams) ([]ListLegalAcceptancesAdminRow, error)
	// Preuves de consentement. L'IP et l'agent utilisateur sont inclus : c'est
	// précisément ce qu'une autorité de contrôle demande pour établir qu'une
	// acceptation vient d'un vrai parcours, et l'export est nominatif par nature.
	ListLegalAcceptancesForExport(ctx context.Context, arg ListLegalAcceptancesForExportParams) ([]ListLegalAcceptancesForExportRow, error)
	// ─── Conformité ──────────────────────────────────────────────────────
	// Vue conformité : pour chaque document, la version publiée, la couverture du
	// consentement sur la version courante, et l'activité d'édition.
	ListLegalComplianceDocuments(ctx context.Context) ([]ListLegalComplianceDocumentsRow, error)
	ListLegalConsentExports(ctx context.Context, limitCount int32) ([]LegalConsentExport, error)
	// Chaîne complète, du plus ancien au plus récent : c'est l'ordre dans lequel
	// les signatures doivent être recomputées pour vérifier qu'aucun maillon n'a
	// été retiré ni réécrit.
	ListLegalConsentExportsForVerify(ctx context.Context) ([]LegalConsentExport, error)
	ListLegalDocumentVersions(ctx context.Context, documentID string) ([]ListLegalDocumentVersionsRow, error)
	// ─── Superadmin ─────────────────────────────────────────────────────
	ListLegalDocumentsAdmin(ctx context.Context) ([]ListLegalDocumentsAdminRow, error)
	// Destinataires d'un avis : les comptes qui avaient accepté une AUTRE version
	// du même document (ceux dont le consentement doit être renouvelé). Un compte
	// suspendu ou sans email est exclu : l'email ne part pas dans le vide.
	ListLegalNoticeRecipients(ctx context.Context, arg ListLegalNoticeRecipientsParams) ([]ListLegalNoticeRecipientsRow, error)
	ListLegalNoticesAdmin(ctx context.Context, limitCount int32) ([]ListLegalNoticesAdminRow, error)
	ListLegalReviewsAdmin(ctx context.Context, limitCount int32) ([]ListLegalReviewsAdminRow, error)
	ListLegalSuperadmins(ctx context.Context) ([]ListLegalSuperadminsRow, error)
	// ═══════════════════════════════════════════════════════════════════
	// ⚖️ Legal — cycle de vie (revues, publication planifiée, rappels)
	//            et registre des exports signés du consentement
	// ═══════════════════════════════════════════════════════════════════
	// ─── Exports signés du registre du consentement ──────────────────────
	// Le texte accepté fait partie de la preuve : on exporte la version complète
	// (corps inclus) et son empreinte SHA-256, pour qu'un vérificateur puisse
	// contrôler l'intégrité sans dépendre de notre base.
	ListLegalVersionsForExport(ctx context.Context, slug pgtype.Text) ([]ListLegalVersionsForExportRow, error)
	ListLikesForPost(ctx context.Context, arg ListLikesForPostParams) ([]ListLikesForPostRow, error)
	// ============================================================================
	// Clés API Média (gestion par le média, délégation api_keys:manage)
	// ============================================================================
	ListMediaApiKeys(ctx context.Context, id string) ([]ListMediaApiKeysRow, error)
	ListMediaMembers(ctx context.Context, mediaid string) ([]ListMediaMembersRow, error)
	// Nouveaux messages STRICTEMENT postérieurs à `after` (polling), ordre
	// ascendant prêt à être ajouté en fin de liste.
	ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error)
	// Messages STRICTEMENT antérieurs à `before` (curseur exclusif, NULL = depuis
	// le début), les plus récents d'abord (le service inverse pour l'affichage).
	ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]ListMessagesBeforeRow, error)
	// =====================================================================
	// 🛡️ File de modération (ModerationReport) — surface superadmin.
	// =====================================================================
	ListModerationReportsWithCount(ctx context.Context, arg ListModerationReportsWithCountParams) ([]ListModerationReportsWithCountRow, error)
	// Tous les surlignages d'un lecteur (bibliothèque), avec l'article associé.
	ListMyHighlights(ctx context.Context, arg ListMyHighlightsParams) ([]ListMyHighlightsRow, error)
	ListNavigationForPublication(ctx context.Context, publicationid string) ([]ListNavigationForPublicationRow, error)
	ListNewsletterDeliveriesByIssue(ctx context.Context, arg ListNewsletterDeliveriesByIssueParams) ([]ListNewsletterDeliveriesByIssueRow, error)
	ListNewsletterIssuesByPublication(ctx context.Context, publicationid string) ([]NewsletterIssue, error)
	ListNotificationDeliveries(ctx context.Context) ([]ListNotificationDeliveriesRow, error)
	ListOAuthClientsByOwner(ctx context.Context, owneruserid string) ([]ListOAuthClientsByOwnerRow, error)
	ListOAuthConfig(ctx context.Context) ([]ListOAuthConfigRow, error)
	ListOpenLegalReviews(ctx context.Context) ([]ListOpenLegalReviewsRow, error)
	// Documents qui exigent une acceptation et que l'utilisateur n'a pas encore
	// acceptés dans leur version publiée courante (déclencheur de re-consentement
	// après une nouvelle version).
	ListPendingLegalAcceptances(ctx context.Context, arg ListPendingLegalAcceptancesParams) ([]ListPendingLegalAcceptancesRow, error)
	// Provisionnement automatique des websites Umami par publication.
	// Chaque publication (blog créateur) a son propre website Umami pour que
	// le créateur voie SES stats (visites, sources, pages, temps passé) sans
	// aucun lien manuel — le worker `provisioner` crée le website et stocke
	// l'id dans Publication."umamiWebsiteId".
	ListPublicationsWithoutUmami(ctx context.Context, limit int32) ([]ListPublicationsWithoutUmamiRow, error)
	// Articles publiés d'une publication (profil), résolue par slug OU subdomain
	// (insensible à la casse). Même shape que ListRecentPublishedArticles.
	ListPublishedArticlesByPublication(ctx context.Context, arg ListPublishedArticlesByPublicationParams) ([]ListPublishedArticlesByPublicationRow, error)
	// ═══════════════════════════════════════════════════════════════════
	// ⚖️ Legal — documents juridiques versionnés
	//   Public  : lecture des versions publiées + consentement du lecteur
	//   Admin   : CRUD superadmin (brouillons, publication, archivage, preuves)
	// ═══════════════════════════════════════════════════════════════════
	// ─── Public ─────────────────────────────────────────────────────────
	// Sommaire public : uniquement les documents actifs ayant une version
	// publiée dans la locale demandée.
	ListPublishedLegalDocuments(ctx context.Context, locale string) ([]ListPublishedLegalDocumentsRow, error)
	// Historique public (transparence) : versions publiées/archivées, jamais les brouillons.
	ListPublishedLegalVersions(ctx context.Context, arg ListPublishedLegalVersionsParams) ([]ListPublishedLegalVersionsRow, error)
	ListQueuedArticleReleaseDeliveries(ctx context.Context, arg ListQueuedArticleReleaseDeliveriesParams) ([]ListQueuedArticleReleaseDeliveriesRow, error)
	ListQuotePostIDs(ctx context.Context, arg ListQuotePostIDsParams) ([]string, error)
	ListReceivedCollaborationRequests(ctx context.Context, inviteeid pgtype.UUID) ([]ListReceivedCollaborationRequestsRow, error)
	// Articles publiés récents (feed mobile « écran principal »), avec auteur /
	// publication / catégorie dénormalisés. Public, trié par date décroissante.
	ListRecentPublishedArticles(ctx context.Context, arg ListRecentPublishedArticlesParams) ([]ListRecentPublishedArticlesRow, error)
	// =====================================================================
	// 🤝 Recommandations croisées entre créateurs (Substack Killer)
	// =====================================================================
	ListRecommendationsByPublication(ctx context.Context, recommenderid string) ([]ListRecommendationsByPublicationRow, error)
	ListRepostsForPost(ctx context.Context, arg ListRepostsForPostParams) ([]ListRepostsForPostRow, error)
	ListSentCollaborationRequests(ctx context.Context, inviterid pgtype.UUID) ([]ListSentCollaborationRequestsRow, error)
	ListSocialLinksForPublication(ctx context.Context, publicationid string) ([]ListSocialLinksForPublicationRow, error)
	ListStarterPackItems(ctx context.Context, starterpackid string) ([]ListStarterPackItemsRow, error)
	ListStarterPacks(ctx context.Context, arg ListStarterPacksParams) ([]ListStarterPacksRow, error)
	ListSubscribers(ctx context.Context, publicationid string) ([]ListSubscribersRow, error)
	ListSubscribersByPublication(ctx context.Context, arg ListSubscribersByPublicationParams) ([]ListSubscribersByPublicationRow, error)
	// ── Feature Flags / Config / Frontend / Translations ────────────────────────
	ListSystemConfigs(ctx context.Context) ([]SystemConfig, error)
	ListUserDrafts(ctx context.Context, arg ListUserDraftsParams) ([]ListUserDraftsRow, error)
	ListUserLegalAcceptances(ctx context.Context, userID pgtype.UUID) ([]ListUserLegalAcceptancesRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	ListWebhooksByPublication(ctx context.Context, publicationid string) ([]ListWebhooksByPublicationRow, error)
	// Réclame UN brouillon arrivé à échéance, verrouillé jusqu'à la fin de la
	// transaction : la publication et le déverrouillage sont donc atomiques, et
	// deux workers ne peuvent pas publier la même version.
	LockDueScheduledLegalVersion(ctx context.Context) (LockDueScheduledLegalVersionRow, error)
	MarkArticleImportJobRunning(ctx context.Context, id string) error
	MarkArticleReleaseDelivery(ctx context.Context, arg MarkArticleReleaseDeliveryParams) error
	// Marque TOUS les messages comme lus (upsert du lastReadAt à maintenant).
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error
	MarkLegalNoticeDelivery(ctx context.Context, arg MarkLegalNoticeDeliveryParams) error
	MarkLegalReviewReminder(ctx context.Context, arg MarkLegalReviewReminderParams) error
	MarkNewsletterDelivery(ctx context.Context, arg MarkNewsletterDeliveryParams) error
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error
	PinPost(ctx context.Context, arg PinPostParams) (bool, error)
	PublishArticleDraft(ctx context.Context, id string) (string, error)
	PublishLegalDocumentVersion(ctx context.Context, id string) (LegalDocumentVersion, error)
	// Réactive un asset purgé/supprimé (nouvelle fenêtre de 3 jours).
	ReactivateMediaAsset(ctx context.Context, id string) (MediaAsset, error)
	RemoveRecommendation(ctx context.Context, arg RemoveRecommendationParams) error
	ResetNewsletterIssueToDraft(ctx context.Context, id string) error
	ResolvePublicationIDBySlugOrID(ctx context.Context, id string) (string, error)
	RetryNotificationDelivery(ctx context.Context, id string) error
	RevokeCollaborationRequestsForArticle(ctx context.Context, arg RevokeCollaborationRequestsForArticleParams) error
	RevokeOAuthTokenByAccessHash(ctx context.Context, accesstokenhash string) error
	RevokeOAuthTokenByRefreshHash(ctx context.Context, refreshtokenhash pgtype.Text) error
	RevokeOAuthTokensByUserClient(ctx context.Context, arg RevokeOAuthTokensByUserClientParams) error
	// ─── Publication planifiée ───────────────────────────────────────────
	// Programme (ou déprogramme, si la date est nulle) la publication automatique
	// d'un brouillon. Refusé sur une version déjà publiée.
	ScheduleLegalDocumentVersion(ctx context.Context, arg ScheduleLegalDocumentVersionParams) (LegalDocumentVersion, error)
	// Recherche sémantique plein corpus (ordre par similarité cosinus).
	SearchSemanticArticles(ctx context.Context, arg SearchSemanticArticlesParams) ([]SearchSemanticArticlesRow, error)
	SearchThoughts(ctx context.Context, arg SearchThoughtsParams) ([]SearchThoughtsRow, error)
	SetApiApplication(ctx context.Context, arg SetApiApplicationParams) error
	SetArticleEditorPick(ctx context.Context, arg SetArticleEditorPickParams) (SetArticleEditorPickRow, error)
	SetArticleStatus(ctx context.Context, arg SetArticleStatusParams) (string, error)
	// L'identifiant et le numéro de séquence ne sont connus qu'après insertion :
	// on écrit donc d'abord la ligne (dans la transaction), puis on y scelle
	// l'empreinte du contenu, le maillon précédent et la signature. Tant que la
	// transaction n'est pas validée, personne ne voit d'export non signé.
	SetLegalConsentExportSignature(ctx context.Context, arg SetLegalConsentExportSignatureParams) (LegalConsentExport, error)
	SetLegalReviewDraft(ctx context.Context, arg SetLegalReviewDraftParams) (LegalReview, error)
	SetNewsletterIssueSending(ctx context.Context, id string) (string, error)
	SetPublicationUmamiWebsite(ctx context.Context, arg SetPublicationUmamiWebsiteParams) error
	SetSubscriberPremiumStatus(ctx context.Context, arg SetSubscriberPremiumStatusParams) error
	SetUserApiGrants(ctx context.Context, arg SetUserApiGrantsParams) error
	SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (string, error)
	// Ajoute un upvote (idempotent). ⚠️ Le retrait et le comptage sont gérés
	// séparément dans le service (les CTE PostgreSQL sont matérialisés, un
	// COUNT dans le même statement ne verrait pas l'insertion).
	ToggleHighlightUpvote(ctx context.Context, arg ToggleHighlightUpvoteParams) (int32, error)
	UnhideArticleByModerator(ctx context.Context, id string) error
	UnhidePostByModerator(ctx context.Context, id string) error
	UnpinPost(ctx context.Context, arg UnpinPostParams) (bool, error)
	UnsubscribeNewsletterSubscriber(ctx context.Context, arg UnsubscribeNewsletterSubscriberParams) error
	UpdateAdminOAuthClientStatus(ctx context.Context, arg UpdateAdminOAuthClientStatusParams) (UpdateAdminOAuthClientStatusRow, error)
	UpdateAdminUserApiAccess(ctx context.Context, arg UpdateAdminUserApiAccessParams) (UpdateAdminUserApiAccessRow, error)
	UpdateAdminUserModeration(ctx context.Context, arg UpdateAdminUserModerationParams) (UpdateAdminUserModerationRow, error)
	UpdateApiKeyLastUsed(ctx context.Context, id string) error
	UpdateApiKeySecret(ctx context.Context, arg UpdateApiKeySecretParams) (int64, error)
	UpdateArticleAttributionConsent(ctx context.Context, arg UpdateArticleAttributionConsentParams) error
	UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) (string, error)
	UpdateArticleDraft(ctx context.Context, arg UpdateArticleDraftParams) (string, error)
	UpdateArticleFull(ctx context.Context, arg UpdateArticleFullParams) (string, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateCollaborationRequestResponse(ctx context.Context, arg UpdateCollaborationRequestResponseParams) error
	UpdateHighlight(ctx context.Context, arg UpdateHighlightParams) (UpdateHighlightRow, error)
	UpdateLegalDocument(ctx context.Context, arg UpdateLegalDocumentParams) (LegalDocument, error)
	// Un brouillon est éditable ; une version publiée est immuable (on publie une
	// nouvelle version, l'ancienne reste archivée comme preuve légale).
	UpdateLegalDocumentVersion(ctx context.Context, arg UpdateLegalDocumentVersionParams) (LegalDocumentVersion, error)
	UpdateMediaApiKeyName(ctx context.Context, arg UpdateMediaApiKeyNameParams) (int64, error)
	UpdateMediaApiKeySecret(ctx context.Context, arg UpdateMediaApiKeySecretParams) (int64, error)
	UpdateMediaMemberPermissions(ctx context.Context, arg UpdateMediaMemberPermissionsParams) error
	UpdateMediaMemberRole(ctx context.Context, arg UpdateMediaMemberRoleParams) error
	UpdateModerationReportResolution(ctx context.Context, arg UpdateModerationReportResolutionParams) (UpdateModerationReportResolutionRow, error)
	UpdateNewsletterIssueDraft(ctx context.Context, arg UpdateNewsletterIssueDraftParams) (NewsletterIssue, error)
	UpdateOAuthClientSecret(ctx context.Context, arg UpdateOAuthClientSecretParams) error
	UpdateOAuthClientStatus(ctx context.Context, arg UpdateOAuthClientStatusParams) error
	UpdateOAuthTokenLastUsed(ctx context.Context, id string) error
	UpdatePersonalPublication(ctx context.Context, arg UpdatePersonalPublicationParams) error
	UpdatePromoActive(ctx context.Context, arg UpdatePromoActiveParams) (UpdatePromoActiveRow, error)
	UpdatePublicationCertified(ctx context.Context, arg UpdatePublicationCertifiedParams) (UpdatePublicationCertifiedRow, error)
	// =====================================================================
	// ✅ Réglages email transactionnels par publication (double opt-in,
	//    bienvenue) — personnalisation + délivrabilité.
	// =====================================================================
	UpdatePublicationEmailSettings(ctx context.Context, arg UpdatePublicationEmailSettingsParams) error
	UpdatePublicationSubdomain(ctx context.Context, arg UpdatePublicationSubdomainParams) error
	UpdateTrendCount(ctx context.Context, arg UpdateTrendCountParams) (UpdateTrendCountRow, error)
	UpdateUserOnboardingText(ctx context.Context, arg UpdateUserOnboardingTextParams) error
	UpdateWebhookActive(ctx context.Context, arg UpdateWebhookActiveParams) error
	UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error
	UpsertArticleAttribution(ctx context.Context, arg UpsertArticleAttributionParams) error
	// Écrit le vecteur d'un article (généré par le worker jina-embeddings-v3).
	UpsertArticleEmbedding(ctx context.Context, arg UpsertArticleEmbeddingParams) error
	UpsertCollaborationRequest(ctx context.Context, arg UpsertCollaborationRequestParams) (UpsertCollaborationRequestRow, error)
	// Ajoute un membre s'il manque (conversation existante re-ouverte).
	UpsertConversationMember(ctx context.Context, arg UpsertConversationMemberParams) error
	// Idempotent : un re-clic ne crée pas de doublon, il rafraîchit la preuve.
	// La preuve est immuable : un re-clic renvoie la première acceptation sans
	// la réécrire (sinon une source par défaut écraserait la preuve d'origine).
	UpsertLegalAcceptance(ctx context.Context, arg UpsertLegalAcceptanceParams) (LegalAcceptance, error)
	// ─── Revues périodiques ──────────────────────────────────────────────
	// Ouvre (ou retrouve) la revue d'une échéance. `DO UPDATE` sans effet permet
	// de récupérer la ligne existante : une même échéance n'ouvre qu'une revue,
	// quel que soit le nombre de passages du worker.
	UpsertLegalReview(ctx context.Context, arg UpsertLegalReviewParams) (LegalReview, error)
	UpsertMediaMember(ctx context.Context, arg UpsertMediaMemberParams) error
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) error
	UpsertOAuthConsent(ctx context.Context, arg UpsertOAuthConsentParams) error
	// Écrit le vecteur d'une pensée (généré par le worker jina-embeddings-v3).
	UpsertPostEmbedding(ctx context.Context, arg UpsertPostEmbeddingParams) error
	UpsertPromo(ctx context.Context, arg UpsertPromoParams) (UpsertPromoRow, error)
	// =====================================================================
	// 👥 Gestion des abonnés (Subscribers API & Headless integrations)
	// =====================================================================
	// Double opt-in : les canaux authentifiés (studio, API clé) confirment
	// d'office l'email — pas de friction là où la relation est déjà vérifiée.
	UpsertSubscriber(ctx context.Context, arg UpsertSubscriberParams) (UpsertSubscriberRow, error)
	// Double opt-in : Stripe/paiement confirme d'office l'email (relation facturée
	// authentifiée) — receiveArticles reste actif sans confirmation email.
	UpsertSubscriberPayment(ctx context.Context, arg UpsertSubscriberPaymentParams) (string, error)
	UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error)
	UpsertTrend(ctx context.Context, arg UpsertTrendParams) (UpsertTrendRow, error)
	// Écrit le vecteur d'un utilisateur/publication (profil).
	UpsertUserEmbedding(ctx context.Context, arg UpsertUserEmbeddingParams) error
	UserExists(ctx context.Context, id string) (bool, error)
	UserOwnsPublication(ctx context.Context, arg UserOwnsPublicationParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
