// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckArticleSlugExists(ctx context.Context, arg CheckArticleSlugExistsParams) (bool, error)
	CheckCategorySlugExists(ctx context.Context, arg CheckCategorySlugExistsParams) (bool, error)
	CheckMediaSlugExists(ctx context.Context, slug string) (bool, error)
	CheckSubdomainExists(ctx context.Context, subdomain pgtype.Text) (bool, error)
	ClearPinnedPosts(ctx context.Context, authorid string) error
	CompleteOnboardingUser(ctx context.Context, arg CompleteOnboardingUserParams) error
	ConsumeOAuthAuthorizationCode(ctx context.Context, id string) error
	CountActiveOAuthTokens(ctx context.Context, userid string) (int64, error)
	CountArticlesByPublication(ctx context.Context, publicationid string) (int32, error)
	// Compte des articles d'une publication (mêmes filtres que ListCreatorArticles).
	CountCreatorArticles(ctx context.Context, arg CountCreatorArticlesParams) (int64, error)
	CountFollowers(ctx context.Context, publicationid string) (int32, error)
	CountFollowing(ctx context.Context, readerid pgtype.UUID) (int32, error)
	CountHighlightUpvotes(ctx context.Context, highlightid string) (int32, error)
	CountOAuthClientsByOwner(ctx context.Context, owneruserid string) (int64, error)
	CountOptionVotes(ctx context.Context, optionid string) (int32, error)
	CountOptionVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountOptionVotesByIDsRow, error)
	CountPollVotes(ctx context.Context, pollid string) (int32, error)
	CountPollVotesByIDs(ctx context.Context, dollar_1 []string) ([]CountPollVotesByIDsRow, error)
	CountPollVotesByPollID(ctx context.Context, pollid string) (int32, error)
	CountPureReposts(ctx context.Context, arg CountPureRepostsParams) (int32, error)
	CreateAnnotationComment(ctx context.Context, arg CreateAnnotationCommentParams) (string, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (string, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (string, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateHighlight(ctx context.Context, arg CreateHighlightParams) (string, error)
	CreateMedia(ctx context.Context, publicationid string) (string, error)
	CreateMediaInvite(ctx context.Context, arg CreateMediaInviteParams) (string, error)
	CreateMediaMember(ctx context.Context, arg CreateMediaMemberParams) error
	CreateMediaPublication(ctx context.Context, arg CreateMediaPublicationParams) (string, error)
	CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (string, error)
	CreatePersonalPublication(ctx context.Context, arg CreatePersonalPublicationParams) (string, error)
	CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (string, error)
	CreateThought(ctx context.Context, arg CreateThoughtParams) (CreateThoughtRow, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (string, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CreateWebhookRow, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (string, error)
	DecrementLikeCount(ctx context.Context, id string) error
	DecrementReplyCount(ctx context.Context, id string) error
	DecrementRepostCount(ctx context.Context, id string) error
	DeleteAnnotationComment(ctx context.Context, arg DeleteAnnotationCommentParams) error
	DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error
	DeleteArticle(ctx context.Context, id string) error
	DeleteArticleComment(ctx context.Context, id string) error
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error
	DeleteCategory(ctx context.Context, id string) error
	DeleteExpiredOAuthArtifacts(ctx context.Context) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteFollowNotification(ctx context.Context, arg DeleteFollowNotificationParams) error
	DeleteHighlight(ctx context.Context, arg DeleteHighlightParams) error
	DeleteHighlightUpvote(ctx context.Context, arg DeleteHighlightUpvoteParams) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeleteLikeNotification(ctx context.Context, arg DeleteLikeNotificationParams) error
	DeleteMediaMember(ctx context.Context, arg DeleteMediaMemberParams) error
	DeleteMute(ctx context.Context, arg DeleteMuteParams) error
	DeleteNavigationItems(ctx context.Context, publicationid string) error
	DeleteOAuthClient(ctx context.Context, arg DeleteOAuthClientParams) error
	DeletePollVote(ctx context.Context, arg DeletePollVoteParams) error
	DeletePureReposts(ctx context.Context, arg DeletePureRepostsParams) error
	DeleteRepostNotification(ctx context.Context, arg DeleteRepostNotificationParams) error
	DeleteRevokedOAuthTokens(ctx context.Context) error
	DeleteSocialLinks(ctx context.Context, publicationid string) error
	DeleteWebhook(ctx context.Context, id string) error
	ExistsUnreadCommentNotification(ctx context.Context, arg ExistsUnreadCommentNotificationParams) (int32, error)
	ExistsUnreadFollowNotification(ctx context.Context, arg ExistsUnreadFollowNotificationParams) (int32, error)
	ExistsUnreadLikeNotification(ctx context.Context, arg ExistsUnreadLikeNotificationParams) (int32, error)
	ExistsUnreadMentionNotification(ctx context.Context, arg ExistsUnreadMentionNotificationParams) (int32, error)
	ExistsUnreadReplyNotification(ctx context.Context, arg ExistsUnreadReplyNotificationParams) (int32, error)
	ExistsUnreadRepostNotification(ctx context.Context, arg ExistsUnreadRepostNotificationParams) (int32, error)
	FindFollowingFeed(ctx context.Context, arg FindFollowingFeedParams) ([]FindFollowingFeedRow, error)
	FindPostsByAuthor(ctx context.Context, arg FindPostsByAuthorParams) ([]FindPostsByAuthorRow, error)
	// Articles publiés classés par similarité cosinus avec un vecteur donné,
	// en excluant l'article source. Requête ANN via l'index HNSW.
	FindSimilarArticles(ctx context.Context, arg FindSimilarArticlesParams) ([]FindSimilarArticlesRow, error)
	FindTrending(ctx context.Context, arg FindTrendingParams) ([]FindTrendingRow, error)
	GetActiveSubscribersByPublication(ctx context.Context, arg GetActiveSubscribersByPublicationParams) ([]GetActiveSubscribersByPublicationRow, error)
	GetActiveSubscriptionForReply(ctx context.Context, arg GetActiveSubscriptionForReplyParams) (int32, error)
	GetActiveWebhooksByPublication(ctx context.Context, arg GetActiveWebhooksByPublicationParams) ([]GetActiveWebhooksByPublicationRow, error)
	// API Créateur (migration depuis Hono apps/api) : clés API, catégories, users, follows, bookmarks.
	GetApiKeyByHash(ctx context.Context, keyhash string) (GetApiKeyByHashRow, error)
	GetArticleByID(ctx context.Context, id string) (GetArticleByIDRow, error)
	GetArticleBySlug(ctx context.Context, arg GetArticleBySlugParams) (GetArticleBySlugRow, error)
	GetArticleCommentAuthor(ctx context.Context, id string) (string, error)
	GetArticleCommentsConfig(ctx context.Context, id string) (GetArticleCommentsConfigRow, error)
	// Retourne le vecteur d'un article sous forme texte ('' si absent). Le scan
	// d'un type vector NULL n'est pas géré par pgvector-go → on cast en texte.
	GetArticleEmbeddingText(ctx context.Context, id string) (string, error)
	GetArticleForSearch(ctx context.Context, id string) (GetArticleForSearchRow, error)
	GetAttachmentsByIDs(ctx context.Context, dollar_1 []string) ([]GetAttachmentsByIDsRow, error)
	GetAudienceSummary(ctx context.Context, publicationid string) (GetAudienceSummaryRow, error)
	GetCanonicalThoughtID(ctx context.Context, id string) (string, error)
	// Catégories d'articles (éditeur dashboard).
	GetCategoryByID(ctx context.Context, id string) (Category, error)
	GetCommentParentAuthor(ctx context.Context, id string) (string, error)
	GetCommentPrefs(ctx context.Context, userid pgtype.UUID) (GetCommentPrefsRow, error)
	GetCommentWithAuthor(ctx context.Context, id string) (GetCommentWithAuthorRow, error)
	// Lecture d'un article PUBLIÉ d'une publication au format contrat créateurs
	// (clé API → publication du créateur), catégorie embarquée.
	GetCreatorArticleBySlug(ctx context.Context, arg GetCreatorArticleBySlugParams) (GetCreatorArticleBySlugRow, error)
	GetExistingBlock(ctx context.Context, arg GetExistingBlockParams) (int32, error)
	GetExistingBookmark(ctx context.Context, arg GetExistingBookmarkParams) (int32, error)
	GetExistingFollow(ctx context.Context, arg GetExistingFollowParams) (int32, error)
	GetExistingLike(ctx context.Context, arg GetExistingLikeParams) (int32, error)
	GetExistingMute(ctx context.Context, arg GetExistingMuteParams) (int32, error)
	GetFollowForReply(ctx context.Context, arg GetFollowForReplyParams) (int32, error)
	GetFollowPrefs(ctx context.Context, userid pgtype.UUID) (GetFollowPrefsRow, error)
	GetFollowedPersonalPublicationOwnerIDs(ctx context.Context, readerid pgtype.UUID) ([]string, error)
	GetFollowingStateByAuthorIDs(ctx context.Context, arg GetFollowingStateByAuthorIDsParams) ([]GetFollowingStateByAuthorIDsRow, error)
	GetFreeSubscriberCount(ctx context.Context, publicationid string) (int32, error)
	// Highlights & annotations : surlignage de passages d'articles, notes,
	// visibilité publique, upvotes et commentaires d'annotation.
	// Tables : Highlight, AnnotationComment, AnnotationUpvote.
	GetHighlightByID(ctx context.Context, id string) (GetHighlightByIDRow, error)
	GetLikePrefs(ctx context.Context, userid pgtype.UUID) (GetLikePrefsRow, error)
	GetMediaInviteByToken(ctx context.Context, token string) (GetMediaInviteByTokenRow, error)
	// Administration Média (création, membres, invitations, réglages) — migration dashboard → Go.
	GetMediaMemberByID(ctx context.Context, arg GetMediaMemberByIDParams) (GetMediaMemberByIDRow, error)
	// RBAC Média (rôles + permissions) — partagé par settings, articles et media.
	GetMediaMemberContext(ctx context.Context, arg GetMediaMemberContextParams) (GetMediaMemberContextRow, error)
	GetMediaOwnerForCredit(ctx context.Context, publicationid string) (GetMediaOwnerForCreditRow, error)
	GetMediaRoleForUser(ctx context.Context, arg GetMediaRoleForUserParams) (string, error)
	GetMediaWithPublication(ctx context.Context, id string) (GetMediaWithPublicationRow, error)
	GetNotificationPreferences(ctx context.Context, userid pgtype.UUID) (GetNotificationPreferencesRow, error)
	// Centre de notifications : liste groupée, non-lus, lecture, préférences.
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]GetNotificationsRow, error)
	GetOAuthAuthorizationCodeByHash(ctx context.Context, codehash string) (OAuthAuthorizationCode, error)
	// OAuth 2.1 / OIDC — clients, codes, tokens, consentement, quotas.
	GetOAuthClientByClientId(ctx context.Context, clientid string) (GetOAuthClientByClientIdRow, error)
	GetOAuthClientByID(ctx context.Context, id string) (GetOAuthClientByIDRow, error)
	GetOAuthConsent(ctx context.Context, arg GetOAuthConsentParams) (OAuthConsent, error)
	GetOAuthTokenByAccessHash(ctx context.Context, accesstokenhash string) (GetOAuthTokenByAccessHashRow, error)
	GetOAuthTokenByRefreshHash(ctx context.Context, refreshtokenhash pgtype.Text) (GetOAuthTokenByRefreshHashRow, error)
	GetOAuthUserClaims(ctx context.Context, id string) (GetOAuthUserClaimsRow, error)
	GetPersonalOwnerForCredit(ctx context.Context, publicationid pgtype.Text) (GetPersonalOwnerForCreditRow, error)
	GetPersonalPublicationByUserID(ctx context.Context, id string) (pgtype.Text, error)
	GetPersonalPublicationForUser(ctx context.Context, id string) (GetPersonalPublicationForUserRow, error)
	GetPersonalPublicationID(ctx context.Context, id string) (pgtype.Text, error)
	// Polls, votes, pièces jointes
	GetPollByThoughtID(ctx context.Context, thoughtid string) (GetPollByThoughtIDRow, error)
	GetPollOptionByID(ctx context.Context, id string) (PollOption, error)
	GetPollOptions(ctx context.Context, pollid string) ([]PollOption, error)
	GetPollOptionsByIDs(ctx context.Context, dollar_1 []string) ([]PollOption, error)
	GetPollsByIDs(ctx context.Context, dollar_1 []string) ([]GetPollsByIDsRow, error)
	GetPostAuthor(ctx context.Context, id string) (string, error)
	GetPostThread(ctx context.Context, arg GetPostThreadParams) ([]GetPostThreadRow, error)
	GetPostsByIDs(ctx context.Context, arg GetPostsByIDsParams) ([]GetPostsByIDsRow, error)
	GetPremiumActiveSubscribers(ctx context.Context, publicationid string) ([]GetPremiumActiveSubscribersRow, error)
	GetPublicationByID(ctx context.Context, id string) (string, error)
	GetPublicationBySlugOrSubdomain(ctx context.Context, lower string) (GetPublicationBySlugOrSubdomainRow, error)
	GetPublicationOwner(ctx context.Context, id string) (string, error)
	GetPublicationTypeByID(ctx context.Context, id string) (GetPublicationTypeByIDRow, error)
	GetPublicationUmamiWebsiteId(ctx context.Context, id string) (pgtype.Text, error)
	GetRecentArticlesForAnalytics(ctx context.Context, arg GetRecentArticlesForAnalyticsParams) ([]GetRecentArticlesForAnalyticsRow, error)
	GetRecentThoughtsForAnalytics(ctx context.Context, arg GetRecentThoughtsForAnalyticsParams) ([]GetRecentThoughtsForAnalyticsRow, error)
	GetRepliesForThought(ctx context.Context, arg GetRepliesForThoughtParams) ([]GetRepliesForThoughtRow, error)
	GetReplyIDsForThought(ctx context.Context, parentid pgtype.Text) ([]string, error)
	// Notifications REPLY / MENTION
	GetReplyPrefs(ctx context.Context, userid pgtype.UUID) (GetReplyPrefsRow, error)
	GetSubscriberEntitlement(ctx context.Context, arg GetSubscriberEntitlementParams) (GetSubscriberEntitlementRow, error)
	GetThoughtByID(ctx context.Context, id string) (GetThoughtByIDRow, error)
	// Threadgates & réponses
	GetThoughtReplyGate(ctx context.Context, id string) (GetThoughtReplyGateRow, error)
	GetUnreadCount(ctx context.Context, recipientid pgtype.UUID) (int32, error)
	GetUserApiAccessStatus(ctx context.Context, id string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByIDFull(ctx context.Context, id string) (GetUserByIDFullRow, error)
	// Profil créateur, onboarding, sous-domaine, liens, clés API (migration dashboard → Go).
	GetUserForSettings(ctx context.Context, id string) (GetUserForSettingsRow, error)
	GetUserMediaMemberships(ctx context.Context, userid pgtype.UUID) ([]GetUserMediaMembershipsRow, error)
	GetUserPersonalPublication(ctx context.Context, id string) (pgtype.Text, error)
	GetUserPollVote(ctx context.Context, arg GetUserPollVoteParams) (string, error)
	GetUserPronouns(ctx context.Context, id string) (pgtype.Text, error)
	GetUserUsername(ctx context.Context, id string) (pgtype.Text, error)
	GetUserVoteForPoll(ctx context.Context, arg GetUserVoteForPollParams) (string, error)
	GetUserVotesByIDs(ctx context.Context, arg GetUserVotesByIDsParams) ([]GetUserVotesByIDsRow, error)
	GetUsersByUsernames(ctx context.Context, dollar_1 []string) ([]GetUsersByUsernamesRow, error)
	GetWebhook(ctx context.Context, id string) (Webhook, error)
	IncrementLikeCount(ctx context.Context, id string) error
	IncrementReplyCount(ctx context.Context, id string) error
	IncrementRepostCount(ctx context.Context, id string) error
	IncrementWalletBalance(ctx context.Context, arg IncrementWalletBalanceParams) error
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error
	InsertArticleComment(ctx context.Context, arg InsertArticleCommentParams) (InsertArticleCommentRow, error)
	InsertBlock(ctx context.Context, arg InsertBlockParams) error
	InsertBookmark(ctx context.Context, arg InsertBookmarkParams) error
	InsertCommentNotification(ctx context.Context, arg InsertCommentNotificationParams) error
	InsertFollow(ctx context.Context, arg InsertFollowParams) error
	InsertFollowNotification(ctx context.Context, arg InsertFollowNotificationParams) error
	InsertLike(ctx context.Context, arg InsertLikeParams) (string, error)
	InsertLikeNotification(ctx context.Context, arg InsertLikeNotificationParams) error
	InsertMediaArticlePublishedFanout(ctx context.Context, arg InsertMediaArticlePublishedFanoutParams) error
	InsertMediaArticleSubmittedFanout(ctx context.Context, arg InsertMediaArticleSubmittedFanoutParams) error
	InsertMediaAuditLog(ctx context.Context, arg InsertMediaAuditLogParams) error
	InsertMediaInviteNotification(ctx context.Context, arg InsertMediaInviteNotificationParams) error
	InsertMediaMemberJoinedNotification(ctx context.Context, arg InsertMediaMemberJoinedNotificationParams) error
	InsertMentionNotification(ctx context.Context, arg InsertMentionNotificationParams) error
	InsertMute(ctx context.Context, arg InsertMuteParams) error
	InsertNavigationItem(ctx context.Context, arg InsertNavigationItemParams) error
	InsertOAuthAuthorizationCode(ctx context.Context, arg InsertOAuthAuthorizationCodeParams) error
	InsertOAuthClient(ctx context.Context, arg InsertOAuthClientParams) error
	InsertOAuthToken(ctx context.Context, arg InsertOAuthTokenParams) error
	// Vote (idempotent : ON CONFLICT DO UPDATE pour changer d'option).
	InsertPollVote(ctx context.Context, arg InsertPollVoteParams) (string, error)
	InsertPureRepost(ctx context.Context, arg InsertPureRepostParams) (string, error)
	InsertReplyNotification(ctx context.Context, arg InsertReplyNotificationParams) error
	InsertRepostNotification(ctx context.Context, arg InsertRepostNotificationParams) error
	InsertSocialLink(ctx context.Context, arg InsertSocialLinkParams) error
	InsertWebhookDeliveryResult(ctx context.Context, arg InsertWebhookDeliveryResultParams) error
	LinkUserPublication(ctx context.Context, arg LinkUserPublicationParams) error
	// Commentaires d'un surlignage, avec auteur.
	ListAnnotationComments(ctx context.Context, highlightid string) ([]ListAnnotationCommentsRow, error)
	ListArticleComments(ctx context.Context, articleid string) ([]ListArticleCommentsRow, error)
	ListArticlesWithCategory(ctx context.Context, arg ListArticlesWithCategoryParams) ([]ListArticlesWithCategoryRow, error)
	// Articles sauvegardés (bookmarks) d'un lecteur, avec titre/slug/publication
	// et la date de sauvegarde — pour la bibliothèque mobile.
	ListBookmarksByReader(ctx context.Context, arg ListBookmarksByReaderParams) ([]ListBookmarksByReaderRow, error)
	ListCategoriesByPublication(ctx context.Context, publicationid string) ([]ListCategoriesByPublicationRow, error)
	// Liste des articles d'une publication au format contrat créateurs (Hono) :
	// filtres `published` (défaut true) et `category` (slug), catégorie embarquée.
	ListCreatorArticles(ctx context.Context, arg ListCreatorArticlesParams) ([]ListCreatorArticlesRow, error)
	// Abonnés d'une publication (profil), paginés — avec état follow du viewer.
	ListFollowersByPublication(ctx context.Context, arg ListFollowersByPublicationParams) ([]ListFollowersByPublicationRow, error)
	// Abonnements d'un utilisateur (profil), résolus vers les propriétaires des
	// publications suivies (PERSONAL/MEDIA), paginés — avec état follow du viewer.
	ListFollowingByUser(ctx context.Context, arg ListFollowingByUserParams) ([]ListFollowingByUserRow, error)
	// Surlignages d'un article : publics + les siens (privés) + état upvote du viewer.
	ListHighlightsByArticle(ctx context.Context, arg ListHighlightsByArticleParams) ([]ListHighlightsByArticleRow, error)
	ListLikesForPost(ctx context.Context, arg ListLikesForPostParams) ([]ListLikesForPostRow, error)
	ListMediaMembers(ctx context.Context, mediaid string) ([]ListMediaMembersRow, error)
	// Tous les surlignages d'un lecteur (bibliothèque), avec l'article associé.
	ListMyHighlights(ctx context.Context, arg ListMyHighlightsParams) ([]ListMyHighlightsRow, error)
	ListOAuthClientsByOwner(ctx context.Context, owneruserid string) ([]ListOAuthClientsByOwnerRow, error)
	ListOAuthConfig(ctx context.Context) ([]ListOAuthConfigRow, error)
	// Provisionnement automatique des websites Umami par publication.
	// Chaque publication (blog créateur) a son propre website Umami pour que
	// le créateur voie SES stats (visites, sources, pages, temps passé) sans
	// aucun lien manuel — le worker `provisioner` crée le website et stocke
	// l'id dans Publication."umamiWebsiteId".
	ListPublicationsWithoutUmami(ctx context.Context, limit int32) ([]ListPublicationsWithoutUmamiRow, error)
	// Articles publiés d'une publication (profil), résolue par slug OU subdomain
	// (insensible à la casse). Même shape que ListRecentPublishedArticles.
	ListPublishedArticlesByPublication(ctx context.Context, arg ListPublishedArticlesByPublicationParams) ([]ListPublishedArticlesByPublicationRow, error)
	ListQuotePostIDs(ctx context.Context, arg ListQuotePostIDsParams) ([]string, error)
	// Articles publiés récents (feed mobile « écran principal »), avec auteur /
	// publication / catégorie dénormalisés. Public, trié par date décroissante.
	ListRecentPublishedArticles(ctx context.Context, arg ListRecentPublishedArticlesParams) ([]ListRecentPublishedArticlesRow, error)
	ListRepostsForPost(ctx context.Context, arg ListRepostsForPostParams) ([]ListRepostsForPostRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	ListWebhooksByPublication(ctx context.Context, publicationid string) ([]ListWebhooksByPublicationRow, error)
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error
	PinPost(ctx context.Context, arg PinPostParams) (bool, error)
	RevokeOAuthTokenByAccessHash(ctx context.Context, accesstokenhash string) error
	RevokeOAuthTokenByRefreshHash(ctx context.Context, refreshtokenhash pgtype.Text) error
	RevokeOAuthTokensByUserClient(ctx context.Context, arg RevokeOAuthTokensByUserClientParams) error
	// Recherche sémantique plein corpus (ordre par similarité cosinus).
	SearchSemanticArticles(ctx context.Context, arg SearchSemanticArticlesParams) ([]SearchSemanticArticlesRow, error)
	SetApiApplication(ctx context.Context, arg SetApiApplicationParams) error
	SetArticleStatus(ctx context.Context, arg SetArticleStatusParams) (string, error)
	SetPublicationUmamiWebsite(ctx context.Context, arg SetPublicationUmamiWebsiteParams) error
	SetSubscriberPremiumStatus(ctx context.Context, arg SetSubscriberPremiumStatusParams) error
	SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) (string, error)
	// Ajoute un upvote (idempotent). ⚠️ Le retrait et le comptage sont gérés
	// séparément dans le service (les CTE PostgreSQL sont matérialisés, un
	// COUNT dans le même statement ne verrait pas l'insertion).
	ToggleHighlightUpvote(ctx context.Context, arg ToggleHighlightUpvoteParams) (int32, error)
	UnpinPost(ctx context.Context, arg UnpinPostParams) (bool, error)
	UpdateApiKeyLastUsed(ctx context.Context, id string) error
	UpdateArticleContent(ctx context.Context, arg UpdateArticleContentParams) (string, error)
	UpdateArticleFull(ctx context.Context, arg UpdateArticleFullParams) (string, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateMediaInviteStatus(ctx context.Context, arg UpdateMediaInviteStatusParams) error
	UpdateMediaMemberPermissions(ctx context.Context, arg UpdateMediaMemberPermissionsParams) error
	UpdateMediaMemberRole(ctx context.Context, arg UpdateMediaMemberRoleParams) error
	UpdateOAuthClientSecret(ctx context.Context, arg UpdateOAuthClientSecretParams) error
	UpdateOAuthClientStatus(ctx context.Context, arg UpdateOAuthClientStatusParams) error
	UpdateOAuthTokenLastUsed(ctx context.Context, id string) error
	UpdatePersonalPublication(ctx context.Context, arg UpdatePersonalPublicationParams) error
	UpdatePublicationSubdomain(ctx context.Context, arg UpdatePublicationSubdomainParams) error
	UpdateUserOnboardingText(ctx context.Context, arg UpdateUserOnboardingTextParams) error
	UpdateWebhookActive(ctx context.Context, arg UpdateWebhookActiveParams) error
	UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error
	// Écrit le vecteur d'un article (généré par le worker jina-embeddings-v3).
	UpsertArticleEmbedding(ctx context.Context, arg UpsertArticleEmbeddingParams) error
	UpsertMediaMember(ctx context.Context, arg UpsertMediaMemberParams) error
	UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) error
	UpsertOAuthConsent(ctx context.Context, arg UpsertOAuthConsentParams) error
	UpsertSubscriberPayment(ctx context.Context, arg UpsertSubscriberPaymentParams) (string, error)
	// Écrit le vecteur d'un utilisateur/publication (profil).
	UpsertUserEmbedding(ctx context.Context, arg UpsertUserEmbeddingParams) error
}

var _ Querier = (*Queries)(nil)
