// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArticleForSearch = `-- name: GetArticleForSearch :one
SELECT id, title, content, slug, "authorId", "categoryId", "publicationId", published, "isPremium",
       "seoTitle", "seoDescription", "createdAt", "updatedAt"
FROM "Article"
WHERE id = $1
`

type GetArticleForSearchRow struct {
	ID             string           `json:"id"`
	Title          string           `json:"title"`
	Content        string           `json:"content"`
	Slug           string           `json:"slug"`
	AuthorId       pgtype.UUID      `json:"authorId"`
	CategoryId     pgtype.Text      `json:"categoryId"`
	PublicationId  string           `json:"publicationId"`
	Published      bool             `json:"published"`
	IsPremium      bool             `json:"isPremium"`
	SeoTitle       pgtype.Text      `json:"seoTitle"`
	SeoDescription pgtype.Text      `json:"seoDescription"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}

func (q *Queries) GetArticleForSearch(ctx context.Context, id string) (GetArticleForSearchRow, error) {
	row := q.db.QueryRow(ctx, getArticleForSearch, id)
	var i GetArticleForSearchRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Slug,
		&i.AuthorId,
		&i.CategoryId,
		&i.PublicationId,
		&i.Published,
		&i.IsPremium,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArticleSlugs = `-- name: ListArticleSlugs :many
SELECT slug FROM "ArticleSlug" WHERE "articleId" = $1
`

func (q *Queries) ListArticleSlugs(ctx context.Context, articleid string) ([]string, error) {
	rows, err := q.db.Query(ctx, listArticleSlugs, articleid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchThoughts = `-- name: SearchThoughts :many
SELECT p.id, p.content, p.tags, p."imageUrl", p."createdAt", p."authorId"::text AS author_id,
       u.name AS author_name, u.username AS author_username, u."logoUrl" AS author_logo,
       u."isCertified" AS author_certified,
       p."likeCount", p."repostCount", p."replyCount"
FROM "Post" p
JOIN "User" u ON u.id = p."authorId"
WHERE p."isDraft" = false
  AND p."deletedAt" IS NULL
  AND p.visibility = 'public'
  AND u."isShadowbanned" = false
  AND u."isSuspended" = false
  AND (
    p.content ILIKE '%' || $1 || '%'
    OR EXISTS (SELECT 1 FROM unnest(p.tags) AS tag WHERE tag ILIKE $1)
  )
ORDER BY p."createdAt" DESC, p.id DESC
LIMIT $2
`

type SearchThoughtsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type SearchThoughtsRow struct {
	ID              string           `json:"id"`
	Content         string           `json:"content"`
	Tags            []string         `json:"tags"`
	ImageUrl        pgtype.Text      `json:"imageUrl"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	AuthorID        string           `json:"author_id"`
	AuthorName      pgtype.Text      `json:"author_name"`
	AuthorUsername  pgtype.Text      `json:"author_username"`
	AuthorLogo      pgtype.Text      `json:"author_logo"`
	AuthorCertified bool             `json:"author_certified"`
	LikeCount       int32            `json:"likeCount"`
	RepostCount     int32            `json:"repostCount"`
	ReplyCount      int32            `json:"replyCount"`
}

func (q *Queries) SearchThoughts(ctx context.Context, arg SearchThoughtsParams) ([]SearchThoughtsRow, error) {
	rows, err := q.db.Query(ctx, searchThoughts, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchThoughtsRow{}
	for rows.Next() {
		var i SearchThoughtsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Tags,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorUsername,
			&i.AuthorLogo,
			&i.AuthorCertified,
			&i.LikeCount,
			&i.RepostCount,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
