// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: starterpacks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStarterPack = `-- name: CreateStarterPack :one
INSERT INTO "StarterPack" (id, title, description, icon, "publicationId", "updatedAt")
VALUES (gen_random_uuid()::text, $1, $2, $3, $4, now())
RETURNING id, title, description, icon, "publicationId", "createdAt", "updatedAt"
`

type CreateStarterPackParams struct {
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	Icon          pgtype.Text `json:"icon"`
	PublicationId string      `json:"publicationId"`
}

func (q *Queries) CreateStarterPack(ctx context.Context, arg CreateStarterPackParams) (StarterPack, error) {
	row := q.db.QueryRow(ctx, createStarterPack,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.PublicationId,
	)
	var i StarterPack
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.PublicationId,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const followPublications = `-- name: FollowPublications :one
WITH inserted AS (
  INSERT INTO "Follows" (id, "readerId", "publicationId")
  SELECT gen_random_uuid()::text, $2, u."publicationId"
  FROM "StarterPackItem" i
  JOIN "User" u ON u.id = i."userId"
  WHERE i."starterPackId" = $1 AND u."publicationId" IS NOT NULL
  GROUP BY u."publicationId"
  ON CONFLICT ("readerId", "publicationId") DO NOTHING
  RETURNING 1
)
SELECT count(*)::int AS followed_count FROM inserted
`

type FollowPublicationsParams struct {
	StarterPackId string      `json:"starterPackId"`
	ReaderId      pgtype.UUID `json:"readerId"`
}

func (q *Queries) FollowPublications(ctx context.Context, arg FollowPublicationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, followPublications, arg.StarterPackId, arg.ReaderId)
	var followed_count int32
	err := row.Scan(&followed_count)
	return followed_count, err
}

const getStarterPackByID = `-- name: GetStarterPackByID :one
SELECT sp.id, sp.title, sp.description, sp.icon, sp."createdAt", sp."updatedAt",
       p.id::text AS pub_id, p.name AS pub_name, p.slug AS pub_slug,
       p."subdomain" AS pub_subdomain, p."customDomain" AS pub_custom_domain,
       p."logoUrl" AS pub_logo, p."isCertified" AS pub_certified,
       (SELECT count(*)::int FROM "StarterPackItem" i WHERE i."starterPackId" = sp.id) AS item_count
FROM "StarterPack" sp
JOIN "Publication" p ON p.id = sp."publicationId"
WHERE sp.id = $1
`

type GetStarterPackByIDRow struct {
	ID              string           `json:"id"`
	Title           string           `json:"title"`
	Description     pgtype.Text      `json:"description"`
	Icon            pgtype.Text      `json:"icon"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
	PubID           string           `json:"pub_id"`
	PubName         string           `json:"pub_name"`
	PubSlug         string           `json:"pub_slug"`
	PubSubdomain    pgtype.Text      `json:"pub_subdomain"`
	PubCustomDomain pgtype.Text      `json:"pub_custom_domain"`
	PubLogo         pgtype.Text      `json:"pub_logo"`
	PubCertified    bool             `json:"pub_certified"`
	ItemCount       int32            `json:"item_count"`
}

func (q *Queries) GetStarterPackByID(ctx context.Context, id string) (GetStarterPackByIDRow, error) {
	row := q.db.QueryRow(ctx, getStarterPackByID, id)
	var i GetStarterPackByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PubID,
		&i.PubName,
		&i.PubSlug,
		&i.PubSubdomain,
		&i.PubCustomDomain,
		&i.PubLogo,
		&i.PubCertified,
		&i.ItemCount,
	)
	return i, err
}

const insertStarterPackItem = `-- name: InsertStarterPackItem :exec
INSERT INTO "StarterPackItem" (id, "starterPackId", "userId")
VALUES (gen_random_uuid()::text, $1, $2)
ON CONFLICT ("starterPackId", "userId") DO NOTHING
`

type InsertStarterPackItemParams struct {
	StarterPackId string      `json:"starterPackId"`
	UserId        pgtype.UUID `json:"userId"`
}

func (q *Queries) InsertStarterPackItem(ctx context.Context, arg InsertStarterPackItemParams) error {
	_, err := q.db.Exec(ctx, insertStarterPackItem, arg.StarterPackId, arg.UserId)
	return err
}

const listStarterPackItems = `-- name: ListStarterPackItems :many
SELECT i."starterPackId" AS starter_pack_id, i."userId"::text AS user_id,
       u.name AS user_name, u.username AS user_username, u."logoUrl" AS user_logo,
       u."isCertified" AS user_certified,
       p.id::text AS pub_id, p.slug AS pub_slug, p."subdomain" AS pub_subdomain,
       (SELECT count(*)::int FROM "Follows" f WHERE f."publicationId" = p.id) AS follower_count
FROM "StarterPackItem" i
JOIN "User" u ON u.id = i."userId"
LEFT JOIN "Publication" p ON p.id = u."publicationId"
WHERE i."starterPackId" = $1
ORDER BY i."createdAt" ASC
`

type ListStarterPackItemsRow struct {
	StarterPackID string      `json:"starter_pack_id"`
	UserID        string      `json:"user_id"`
	UserName      pgtype.Text `json:"user_name"`
	UserUsername  pgtype.Text `json:"user_username"`
	UserLogo      pgtype.Text `json:"user_logo"`
	UserCertified bool        `json:"user_certified"`
	PubID         string      `json:"pub_id"`
	PubSlug       pgtype.Text `json:"pub_slug"`
	PubSubdomain  pgtype.Text `json:"pub_subdomain"`
	FollowerCount int32       `json:"follower_count"`
}

func (q *Queries) ListStarterPackItems(ctx context.Context, starterpackid string) ([]ListStarterPackItemsRow, error) {
	rows, err := q.db.Query(ctx, listStarterPackItems, starterpackid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStarterPackItemsRow{}
	for rows.Next() {
		var i ListStarterPackItemsRow
		if err := rows.Scan(
			&i.StarterPackID,
			&i.UserID,
			&i.UserName,
			&i.UserUsername,
			&i.UserLogo,
			&i.UserCertified,
			&i.PubID,
			&i.PubSlug,
			&i.PubSubdomain,
			&i.FollowerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarterPacks = `-- name: ListStarterPacks :many
SELECT sp.id, sp.title, sp.description, sp.icon, sp."createdAt", sp."updatedAt",
       p.id::text AS pub_id, p.name AS pub_name, p.slug AS pub_slug,
       p."subdomain" AS pub_subdomain, p."customDomain" AS pub_custom_domain,
       p."logoUrl" AS pub_logo, p."isCertified" AS pub_certified,
       (SELECT count(*)::int FROM "StarterPackItem" i WHERE i."starterPackId" = sp.id) AS item_count
FROM "StarterPack" sp
JOIN "Publication" p ON p.id = sp."publicationId"
ORDER BY sp."createdAt" DESC
LIMIT $1 OFFSET $2
`

type ListStarterPacksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListStarterPacksRow struct {
	ID              string           `json:"id"`
	Title           string           `json:"title"`
	Description     pgtype.Text      `json:"description"`
	Icon            pgtype.Text      `json:"icon"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
	PubID           string           `json:"pub_id"`
	PubName         string           `json:"pub_name"`
	PubSlug         string           `json:"pub_slug"`
	PubSubdomain    pgtype.Text      `json:"pub_subdomain"`
	PubCustomDomain pgtype.Text      `json:"pub_custom_domain"`
	PubLogo         pgtype.Text      `json:"pub_logo"`
	PubCertified    bool             `json:"pub_certified"`
	ItemCount       int32            `json:"item_count"`
}

func (q *Queries) ListStarterPacks(ctx context.Context, arg ListStarterPacksParams) ([]ListStarterPacksRow, error) {
	rows, err := q.db.Query(ctx, listStarterPacks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStarterPacksRow{}
	for rows.Next() {
		var i ListStarterPacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PubID,
			&i.PubName,
			&i.PubSlug,
			&i.PubSubdomain,
			&i.PubCustomDomain,
			&i.PubLogo,
			&i.PubCertified,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
