ALTER TABLE "CollaborationRequest"
  ADD COLUMN "requestedRole" TEXT NOT NULL DEFAULT 'CO_AUTHOR',
  ADD COLUMN "requestedOrder" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "acceptedAt" TIMESTAMP(3);

ALTER TABLE "NotificationPreference"
  ADD COLUMN "emailCollaborations" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "pushCollaborations" BOOLEAN NOT NULL DEFAULT true;

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ARTICLE_CONTRIBUTOR_INVITED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ARTICLE_CONTRIBUTOR_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ARTICLE_CONTRIBUTOR_DECLINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ARTICLE_CONTRIBUTOR_REMOVED';
